External 58 versioning
thrackle-io/forte-rules-engine-v1 pull request #116
Opened 2023-08-18 08:47 UTC by oscarsernarosero

Version fields added to handlers, AppManager, RuleStorage, RuleProcessor, Data contracts and Pricers. The strategy used is described [here](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/166133773/Tron+Versioning)

2023-08-18 16:34 UTC, TJ-Everett reviewed
Should the versions be at 1.0.0 ? Since we will be cutting these changes over to rules then deploying in this sprint?

2023-08-21 18:05 UTC, ShaneDuncan602 commented
I think this PR should point to external

2023-08-21 18:06 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> -    uint8 public constant VERSION = 1;
Good thinking removing these old ones.

2023-08-21 18:08 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/RuleProcessorDiamond.sol
> +    function VERSION() external view returns(string memory){
Are we sure we want this version to be all caps? I usually only see that with enums. For instance, OZ has similar functions for name, owner, etc and they are all lower or camel.

2023-08-21 18:25 UTC, oscarsernarosero commented
> Should the versions be at 1.0.0 ? Since we will be cutting these changes over to rules then deploying in this sprint?

Good point. Im debating if I should do that in this ticket, or if I should leave it here as 0.0.6, and then create another ticket dedicated only for upgrading the version as we should do from here onwards.

2023-08-21 18:28 UTC, ShaneDuncan602 commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +import {ERC173Facet} from "diamond-std/implementations/ERC173/ERC173Facet.sol";
I don't think we need this in here. ProtocolRawFacet contains 165 and 173 and is always added to the diamonds. That should make the 173 functions available. In [Mudgen's newest examples](https://github.com/mudgen/diamond-1-hardhat/commits?author=mudgen)  he defines the interfaces, IERC165 and IERC173, in the diamond but has the code for them in a facet. We should probably do the same. I think we need to remove 165 and 173 from any remaining facets and define the interfaces in the storage and processor diamonds.

2023-08-21 18:28 UTC, ShaneDuncan602 commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +contract RuleStorageDiamond is IRuleStorageDiamondEvents, ERC173Facet {
see above

2023-08-21 18:29 UTC, ShaneDuncan602 commented on src/token/ProtocolHandlerCommon.sol
> +    string public constant VERSION="0.0.6";
Great spot for this.

2023-08-21 18:31 UTC, ShaneDuncan602 requested changes
Just some questions about implementation and capitolization.

2023-08-21 18:31 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorDiamond.sol
> +    function VERSION() external view returns(string memory){
Since constants are conventionally named in all caps, and since these constants were made public in the application side, their getters will automatically be VERSION(), so I just tried to make it all the same. However, you bring up a good point which is that the version is not constant in the protocol side. So we can make VERSION constant private in the application side, and create a version() getter for those, and that way we can have all getters be lower case.

2023-08-21 18:34 UTC, oscarsernarosero commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +import {ERC173Facet} from "diamond-std/implementations/ERC173/ERC173Facet.sol";
I had to add it cuz it was complaining when I was trying to make the `updateVersion` function onlyOwner. Unless there is another way of doing it, and Im not aware of.

2023-08-21 18:37 UTC, ShaneDuncan602 commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +import {ERC173Facet} from "diamond-std/implementations/ERC173/ERC173Facet.sol";
Will it work with just the interface defined?

2023-08-21 18:46 UTC, ShaneDuncan602 commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +import {ERC173Facet} from "diamond-std/implementations/ERC173/ERC173Facet.sol";
I think that the version stuff should be in its own facet rather than in the diamond itself. We should probably keep the diamond as clean as possible. If you look at his [OwnershipFacet](https://github.com/mudgen/diamond-1-hardhat/blob/main/contracts/facets/OwnershipFacet.sol) you can see an example.

2023-08-21 19:00 UTC, oscarsernarosero commented on src/economic/ruleStorage/RuleStorageDiamond.sol
> +import {ERC173Facet} from "diamond-std/implementations/ERC173/ERC173Facet.sol";
great point. Will do.

2023-08-22 18:23 UTC, ShaneDuncan602 commented
Can you add some testing to make sure that the ownership logic works as expected in the diamonds?

2023-08-24 13:59 UTC, ShaneDuncan602 commented
I looked through the existing test for ownership transfer. It doesn't really test it. It calls the transferOwnership but there is no assertion that the new owner is truly the owner. It also seems to transfer ownership from superAdmin to superAdmin. All I think it needs is for the ownership to be transferred to a different address and then that address try to upgrade. These functions are in RuleProcessorDiamond.t.sol and RuleStorageDiamond.t.sol - testUpgrade().

2023-08-24 15:00 UTC, oscarsernarosero commented
> I looked through the existing test for ownership transfer. It doesn't really test it. It calls the transferOwnership but there is no assertion that the new owner is truly the owner. It also seems to transfer ownership from superAdmin to superAdmin. All I think it needs is for the ownership to be transferred to a different address and then that address try to upgrade. These functions are in RuleProcessorDiamond.t.sol and RuleStorageDiamond.t.sol - testUpgrade().

ohh ok I see what you're saying. You're right. I haven't tested the ownership transfer. Will do.

2023-08-24 15:41 UTC, ShaneDuncan602 approved these changes
Looks great.

2023-08-24 15:53 UTC, merged