Audit 26 - Added custom error to handle fees over 100 percent
thrackle-io/forte-rules-engine-v1 pull request #127
Opened 2023-08-21 18:01 UTC by ShaneDuncan602

This closes #81

2023-08-21 18:47 UTC, oscarsernarosero requested changes
An unexplored scenario here is discounts exceeding fees which might cause unexpected behaviors.

2023-08-21 18:47 UTC, oscarsernarosero commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
is there any chances that the discount total is greater than the fees total? If that is a possibility, then we have to check for that scenario before carrying out the substraction since this will cause an underflow.

2023-08-21 18:47 UTC, oscarsernarosero commented on test/ApplicationERC20.t.sol
> +    }
A test for discounts being greater than fees must be included.

2023-08-21 18:49 UTC, ShaneDuncan602 commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
Shouldn't be a problem since they are signed integers.

2023-08-21 19:50 UTC, TJ-Everett commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
I agree it would not be a problem on this check specifically if the discount is greater than the fees, where it would be an underflow is when subtracted from the total token amount in the transfer (I think this is what concerns Oscar as well) where you would then, essentially, be owned tokens in the transfer from since you would be adding a negative to the transfer amount. 
Oscar is that a correct summary?

2023-08-21 21:31 UTC, ShaneDuncan602 commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
It always checks to ensure that the fee is larger than the discount slice. I can add a test for this scenario though just to be certain.

2023-08-22 15:05 UTC, TJ-Everett approved these changes
This looks great Shane. Approved

2023-08-23 03:13 UTC, oscarsernarosero approved these changes
Looks great Shane. Now there's no room for doubt.

2023-08-23 03:13 UTC, oscarsernarosero commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
ah ok. The only problem with that is the gas cost. I went ahead and tested the gas in remix like this:
```

    function signedSub(int a, uint24 b) external pure returns (int z){
        return a - int24(b);
    }

    function unsignedSub(uint a, uint24 b) external pure returns (uint z){
        if(a > b)
            return a - b;
        else
            return 0;
    }
```
    
The input was 1000 for A and 2000 for B. The gas cost for using unsigned integers was 814 and 1105 for using the signed version (35% increase), and that's not even counting the variable creation. I would try to use unsigned integers when possible.

2023-08-23 03:13 UTC, oscarsernarosero commented on src/token/ProtocolERC20Handler.sol
> +        if (totalFeePercent - int24(discount) > 10000) {
yes. I think the most important factor here is the test to make sure there is no issues in that scenario. And if the code always checks that the fees are greater than discounts, then there is no need to use the more expensive signed integer over the unsigned integer.

2023-08-23 03:13 UTC, oscarsernarosero commented on test/ApplicationERC20.t.sol
> +
Looks great

2023-08-24 14:42 UTC, merged