SE 187 access module global rules pause rules toggle on off
thrackle-io/forte-rules-engine-v1 pull request #137
Opened 2023-08-29 17:58 UTC by TJ-Everett

2023-08-29 18:46 UTC, oscarsernarosero requested changes
Looks good. I do see some opportunities for improvements, and I would also add some tests to prove that current implementation works as expected.

2023-08-29 18:46 UTC, oscarsernarosero commented on src/application/AppManager.sol
> +        /// retieve pause rule array
misspelling

2023-08-29 18:46 UTC, oscarsernarosero commented on src/application/AppManager.sol
> +        }
This over here is better to do in the data contract for gas reasons. You can create a function in PauseRules data contract that will return something like `return pauseRules.length == 0;`. It would have the same effect, but returning a boolean instead of returning an array which is really expensive.

2023-08-29 18:46 UTC, oscarsernarosero commented on src/application/ProtocolApplicationHandler.sol
> +        }
This can be improved by making an OR conditional: `if (msg.sender == address(appManagerAddress) || !appManager.isRuleAdministrator(msg.sender))`

2023-08-29 20:16 UTC, oscarsernarosero requested changes

2023-08-29 20:16 UTC, oscarsernarosero commented on src/application/ProtocolApplicationHandler.sol
> +        }
not sure why there is negation in the second if tho.

2023-08-29 20:16 UTC, oscarsernarosero commented on src/data/PauseRules.sol
> +    }
This works perfectly fine. I just think we can avoid 4 lines of code if you simply return the result of the conditional:

```
function isPauseRulesEmpty() external view virtual onlyOwner returns(bool) {
        return pauseRules.length == 0;
        }
```
Im being a bit of a stickler here since one of the audit observations was that sometimes we had unnecessarily long chunks of code which makes it less readable.

2023-08-29 20:16 UTC, oscarsernarosero commented on src/application/ProtocolApplicationHandler.sol
> +        if (msg.sender == address(appManagerAddress) || appManager.isRuleAdministrator(msg.sender)) {
ok. I had to look at the code, but I think it's better if this function is an onlyOwner fucntion since `appManagerAddress` is the owner, but you will need to force the devs to call this function through the AppManager as we do in other functions.

2023-08-29 22:56 UTC, oscarsernarosero approved these changes
Looks perfect!

2023-08-31 13:44 UTC, ShaneDuncan602 commented on docs/userGuides/rules/RULE-GUIDE.md
> +| Pause Window                                   | At times, it may be necessary to disable transactions on a particular token while maintenance functions or other activities are performed on a suppo
actiavte

2023-08-31 13:46 UTC, ShaneDuncan602 commented on docs/userGuides/rules/RULE-GUIDE.md
> +| Pause Window                                   | At times, it may be necessary to disable transactions on a particular token while maintenance functions or other activities are performed on a suppo
You might also add something about the ability to toggle off the pause checks for efficiency as well as for unpausing without the need for pause rule deletion prior to the window closing.

2023-08-31 13:48 UTC, ShaneDuncan602 commented on src/data/PauseRules.sol
> +    }
Does this need the onlyOwner?

2023-08-31 13:50 UTC, ShaneDuncan602 requested changes
Just a minor typo and couple suggestions.

2023-08-31 13:50 UTC, TJ-Everett commented on src/data/PauseRules.sol
> +    }
My thought was that we might not want users to be able to call this and see if there is no upcoming pause rules, but otherwise no.

2023-08-31 16:07 UTC, TJ-Everett commented on docs/userGuides/rules/RULE-GUIDE.md
> +| Pause Window                                   | At times, it may be necessary to disable transactions on a particular token while maintenance functions or other activities are performed on a suppo
This lead me to realize that I missed a function to do just this. Since the activate function was onlyOwner that meant only the appManager can call the activate function to skip/enable the check. So I added that function and some testing to the most recent commit to address the additional description and the functions match that.

2023-08-31 19:22 UTC, ShaneDuncan602 commented on src/data/PauseRules.sol
> +    }
Good thinking.

2023-08-31 19:23 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-08-31 20:01 UTC, merged