SE-153-Merge-external-into-internal
thrackle-io/forte-rules-engine-v1 pull request #141
Opened 2023-09-01 20:47 UTC by ShaneDuncan602

You will probably have to filter out the md files.

2023-09-05 15:08 UTC, TJ-Everett commented on src/data/PauseRules.sol
> +    function getPauseRules() external view virtual onlyOwner returns (PauseRule[] memory) {
This is missing the isPauseRulesEmpty() from the pause rules bool branch that was just merged with JB.

2023-09-05 16:01 UTC, TJ-Everett commented on src/token/ProtocolERC20Handler.sol
>          _balanceFrom;
Looks like the remove unused variables didn't get picked up either. I see in the history that this was added into the branch this morning but the variables are still here.

2023-09-05 16:44 UTC, TJ-Everett commented on test/ApplicationAMM.t.sol
>          ///create new pause rule to check that swaps and trasnfers are paused
transfers**

2023-09-05 16:52 UTC, TJ-Everett commented on test/ERC20AutoMintStaking.t.sol
> -// SPDX-License-Identifier: UNLICENSED
Are we removing all staking from internal intentionally?

2023-09-05 16:56 UTC, TJ-Everett requested changes
This looks great Shane. I notated that we are missing the pause rules bool and unused variables changes it seems. It also looks like we have completely removed staking from this branch, is that intentional?

2023-09-05 18:40 UTC, ShaneDuncan602 commented on test/ERC20AutoMintStaking.t.sol
> -// SPDX-License-Identifier: UNLICENSED
No, good find. It looks like this was deleted during the merge. I'll add them back.

2023-09-05 21:16 UTC, ShaneDuncan602 commented on src/data/PauseRules.sol
> +    function getPauseRules() external view virtual onlyOwner returns (PauseRule[] memory) {
Added the pause rule bool stuff

2023-09-05 21:17 UTC, ShaneDuncan602 commented on test/ApplicationAMM.t.sol
>          ///create new pause rule to check that swaps and trasnfers are paused
done

2023-09-05 21:17 UTC, ShaneDuncan602 commented on test/ERC20AutoMintStaking.t.sol
> -// SPDX-License-Identifier: UNLICENSED
added them

2023-09-06 01:11 UTC, oscarsernarosero approved these changes
Looks good Shane

2023-09-06 01:11 UTC, oscarsernarosero commented on .env.production
> +
I think I saw Tayler asking about this, but yeah. I think GitHub assumes we are trying to get rid of the staking pieces which we are not trying to do. Idk how to solve that tho. Maybe trying to merge internal into external first in a separate branch, and then merge that branch back into internal? JB for sure knows a better way.

2023-09-06 13:26 UTC, TJ-Everett commented on src/token/ProtocolERC20Handler.sol
> +        // _registerInterface(type(IAdminWithdrawalRuleCapable).interfaceId);
Looks like this duplicated in the newest merge

2023-09-06 13:30 UTC, TJ-Everett approved these changes
Just one line of duped code otherwise this looks great!

2023-09-06 13:59 UTC, ShaneDuncan602 commented on .env.production
> +
Added

2023-09-06 14:00 UTC, ShaneDuncan602 commented on src/token/ProtocolERC20Handler.sol
> +        // _registerInterface(type(IAdminWithdrawalRuleCapable).interfaceId);
Fixed

2023-09-06 14:01 UTC, ShaneDuncan602 commented
Just to be sure that everything actually go into this branch, I went ahead and used a comparison tool(BeyondCompare) to check. It was also missing the example staking contract deployment scripts. I added them. Everything is merged, functioning, and ready.

2023-09-06 14:45 UTC, merged