CREATE-NFT-RULES.md addNFTTransferCounterRule:
thrackle-io/forte-rules-engine-v1 pull request #148
Opened 2023-09-06 21:14 UTC by TJ-Everett

added start time param
DEPLOY-APPMANAGER:
create command refactored
DEPLOY-NFT.md:
connectHandlerToToken command refactored

2023-09-07 14:12 UTC, ShaneDuncan602 requested changes
This is now the valid deployment of Mumbai for v1.0.1. It needs to be added to DEPLOYMENT-DIRECTORY.md as well as environment variables in the .env file. Also, I think we need to take some of the protocol unit tests(the diamond tests) and put them into a Deployment.t.sol. In there, the setup function would use the .env variables to link to the existing contracts during a fork test. We need a way to test our deployments that is reusable for all environments.

2023-09-07 23:20 UTC, ShaneDuncan602 commented on test/DeploymentProcessor.t.sol
> +contract RuleProcessorDiamondTest is Test, RuleProcessorDiamondTestUtil, TestCommon {
You should only need the TestCommon here. RuleProcessorDiamondTestUtil is being phased out

2023-09-07 23:22 UTC, ShaneDuncan602 commented on test/DeploymentProcessor.t.sol
> +        ruleProcessor.setRuleDataDiamond(address(ruleStorageDiamond));
All of this protocol setup is handled in TestCommon. You can refer to some of the other tests to see how the stuff should be set up now. We no longer have to repeat this. It’s done with one function call

2023-09-07 23:23 UTC, ShaneDuncan602 commented on test/DeploymentStorage.t.sol
> +import {TaggedRuleDataFacet as TaggedRuleDataFacet} from "../src/economic/ruleStorage/TaggedRuleDataFacet.sol";
Many of these imports are already defined in TestCommon

2023-09-07 23:23 UTC, ShaneDuncan602 commented on test/DeploymentStorage.t.sol
> +        // Deploy app manager
See the comments from the other test

2023-09-07 23:24 UTC, ShaneDuncan602 requested changes
It is very close. Everything is there, but the test need to be modernized to use the new way. We do the test. Great job though. I would recommend that you look at some of the other tests and see how the set up function is and then that way you can see how simplified it is now

2023-09-08 02:46 UTC, ShaneDuncan602 approved these changes
Looks awesome. Thanks for all the hard work in this.

2023-09-08 05:20 UTC, oscarsernarosero approved these changes
Looks really good overall Tayler. Im just not sure if the superAdmin is a good address to test against, so Im gonna hold on approving until we are sure. The failing test should use the expectRevert so we are sure about them failing. If the failing tests do fail with the superAdmin then we are good.

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        // add empty rule at ruleId 0
I think this comment is a fossil from millions of years ago since we don't do empty rules at position 0 since late Precambrian age.

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        ERC20TaggedRuleProcessorFacet(address(ruleProcessor)).minAccountBalanceCheck(applicationCoin.balanceOf(superAdmin), tags, amount, ruleId);
is superAdmin a good test actor? Im not sure if the superAdmin will bypass the rules like previous appAdmin.

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        // add empty rule at ruleId 0
fossil

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +            applicationAppManager.addGeneralTag(superAdmin, bytes32(i)); //add tag
same questions about superAdmin being able to bypass rules.

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        ERC20TaggedRuleProcessorFacet(address(ruleProcessor)).minAccountBalanceCheck(applicationCoin.balanceOf(superAdmin), tags, amount, ruleId);
I guess it does fail even with superAdmin since the test name indicates this call will revert, but could you test this with an "expectRevert" instead so we know for sure it is failing as expected?

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        ERC20TaggedRuleProcessorFacet(address(ruleProcessor)).maxAccountBalanceCheck(applicationCoin.balanceOf(superAdmin), tags, amount, ruleId);
I'll just keep highlighting superAdmins just in case, but feel free to ignore these if superAdmin turns out to be ok for tests

2023-09-08 05:20 UTC, oscarsernarosero commented on test/DeploymentProcessor.t.sol
> +        bytes32[] memory tags = applicationAppManager.getAllTags(superAdmin);
superAdmin

2023-09-08 05:22 UTC, oscarsernarosero requested changes
Sorry I meant to request changes

2023-09-08 13:41 UTC, TJ-Everett commented on test/DeploymentProcessor.t.sol
> +        bytes32[] memory tags = applicationAppManager.getAllTags(superAdmin);
I have swapped out the super admins for users and we are getting failures when we expect them. The super admins were technically fine since the rule was being checked directly and bypassing the admin checks in the handlers.

2023-09-08 13:43 UTC, TJ-Everett commented on test/DeploymentProcessor.t.sol
> +        ERC20TaggedRuleProcessorFacet(address(ruleProcessor)).minAccountBalanceCheck(applicationCoin.balanceOf(superAdmin), tags, amount, ruleId);
The expect revert doesn't work here since the expected reversion (for foundry) tries to fail at the balanceOf() function. So marking the testFails in the title works the best. I did remove the fail and ensure that the expectedly passing test fails with the BalBelowMin error we want though.

2023-09-08 22:11 UTC, oscarsernarosero approved these changes
Great job!

2023-09-08 22:59 UTC, merged