Se 171 code quality comments and function parameters external
thrackle-io/forte-rules-engine-v1 pull request #154
Opened 2023-09-19 15:47 UTC by oscarsernarosero

2023-09-19 16:14 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol
> +                        return;
Doesn't it still need to hit lines 65-70 once it is matched? For the situation where the score matches the highest value? If not, we should get rid of those lines.

2023-09-19 16:14 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol
> +        /// reseting the "tradesWithinPeriod", unless we have been in current period for longer than the last update
resetting

2023-09-19 16:15 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol
> +
Great use of the ternary here

2023-09-19 16:18 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +             if (max > 0 && balanceTo + amount > max) revert MaxBalanceExceeded();
nice

2023-09-19 16:21 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +        uint finalBalance = balance - amount;
Is creating this variable in memory cheaper than the single operation? I could see if the expression was evaluated multiple times but I'm not sure it would be more efficient for single use.

2023-09-19 16:25 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC721RuleProcessorFacet.sol
> +                    cumulativeTotal = rule.startTs.isWithinPeriod(period, lastTransferTime) ?
Are these ternaries more efficient than standard if-else blocks? IMO they are harder to read and easier to overlook.

2023-09-19 16:28 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/RiskTaggedRuleProcessorFacet.sol
> +                    return;
Same question as above.

2023-09-19 16:29 UTC, ShaneDuncan602 commented on src/example/ERC721/not-upgradeable/ApplicationERC721MintForAFee.sol
> +        // withdrawMintFees(msg.value); // uncomment this is automatic withdrawal is desired. withdrawMintFees should be marked as private
uncomment this is automatic withdrawal if desired

2023-09-19 16:35 UTC, ShaneDuncan602 commented on src/example/ERC721/upgradeable/ApplicationERC721UpgAdminMint.sol
> +contract ApplicationERC721Upgradeable is ProtocolERC721U {
I think ProtocolERC721U.sol safeMint is missing the appAdministratorOrOwnerOnly modifier

2023-09-19 16:39 UTC, ShaneDuncan602 commented on src/example/script/ApplicationERC721.s.sol
I think we will need matching deploy scripts for each of the newly created example 721's. It will be confusing for users to try and match the example to the generic script and change it.

2023-09-19 16:42 UTC, ShaneDuncan602 commented on test/ERC721Examples.t.sol
Love this

2023-09-19 17:47 UTC, ShaneDuncan602 requested changes
Really good stuff. I just have a couple of questions and comments. Also, it looks like the tests are failing.

2023-09-19 19:15 UTC, TJ-Everett commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +        uint finalBalance = balance - amount;
also for code consistency we should use uint256 (even though it is the same thing)...

2023-09-19 19:16 UTC, TJ-Everett commented on src/example/ERC721/not-upgradeable/ApplicationERC721MintForAFee.sol
> +        // withdrawMintFees(msg.value); // uncomment this is automatic withdrawal is desired. withdrawMintFees should be marked as private
if? Not is?

2023-09-19 19:17 UTC, TJ-Everett commented on src/example/ERC721/not-upgradeable/ApplicationERc721AdminOrOwnerMint.sol
> +// SPDX-License-Identifier: UNLICENSED
the C in the name of this file should be capitalized

2023-09-19 19:18 UTC, TJ-Everett requested changes
Added my thoughts to the current PR. Shane's questions and then a few typos.

2023-09-19 20:15 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol
> +                        return;
not if it is inside this block because this means we found the risk score range we are looking for (the conditional of line 52) so there is no need to check for the last range. It will get to lines 65-70 if the risk score was not less than the any of the rules risk-score limits which means it is in the highest range.

2023-09-19 20:31 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +        uint finalBalance = balance - amount;
It is not created in memory, but in the stack, and yes, it is cheaper than calculating the result once per tag. Although you got me thinking, so I went ahead and tested it:

```
contract StackA{

    uint constant x = 10;
    /// gas: 1660 with a=7, b=4, c=10
    function test(uint a, uint b, uint c) external pure{
        uint d = a + b;
        for(uint i; i < c;){
            bool r = d < x;
            unchecked{
                ++i;
            }
        }
    }
}

contract StackB{

    uint constant x = 10;
    /// gas: 3469 with a=7, b=4, c=10
    function test(uint a, uint b, uint c) external pure{
        
        for(uint i; i < c;){
            uint d = a + b;
            bool r = d < x;
            unchecked{
                ++i;
            }
        }
    }
}
```

And the test shows that it is way cheaper to do the math once since it reduces the operation gas cost by 52%.

2023-09-19 20:46 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC721RuleProcessorFacet.sol
> +                    cumulativeTotal = rule.startTs.isWithinPeriod(period, lastTransferTime) ?
You got me thinking again, so I went ahead and tested the gas efficiency:
```
contract WithTernary{
    /// gas: 614 with a=5; gas: 604 with a =12
    function test(uint a) external pure returns (uint r){
        r = a > 10 ? 10 : a;
    }
}

contract WithoutTernary{
    /// gas: 607 with a=5; gas: 617 with a =12
    function test(uint a) external pure returns (uint r){
        if (a > 10){
            r = 10;
        }else{
            r = a;
        }
    }
}
``` 

So it looks like the gas efficiency is the same in average since the ternary is slightly more efficient in the negative cases, but the if-else is slightly more efficient in the positive cases. Although the gap in efficiency is greater when the ternary beats the if-else, the efficiency difference is too small to consider it a factor. So I personally think that the ternary assignment saves us a lot of code lines, and it makes the code more readable imo.

2023-09-19 20:49 UTC, oscarsernarosero commented on src/example/ERC721/not-upgradeable/ApplicationERC721MintForAFee.sol
> +        // withdrawMintFees(msg.value); // uncomment this is automatic withdrawal is desired. withdrawMintFees should be marked as private
yeah it was supposed to be "if". Should I leave it? Would that be confusing for devs?

2023-09-19 20:49 UTC, oscarsernarosero commented on src/example/ERC721/upgradeable/ApplicationERC721UpgAdminMint.sol
> +contract ApplicationERC721Upgradeable is ProtocolERC721U {
Great catch!

2023-09-19 20:52 UTC, oscarsernarosero commented on src/example/ERC721/upgradeable/ApplicationERC721UpgAdminMint.sol
> +contract ApplicationERC721Upgradeable is ProtocolERC721U {
Oh! actually it is there.

2023-09-19 20:52 UTC, oscarsernarosero commented on test/ERC721Examples.t.sol
Thank you!

2023-09-19 20:57 UTC, oscarsernarosero commented on src/example/ERC721/not-upgradeable/ApplicationERc721AdminOrOwnerMint.sol
> +// SPDX-License-Identifier: UNLICENSED
Great catch!

2023-09-19 21:06 UTC, ShaneDuncan602 commented on src/example/ERC721/not-upgradeable/ApplicationERC721MintForAFee.sol
> +        // withdrawMintFees(msg.value); // uncomment this is automatic withdrawal is desired. withdrawMintFees should be marked as private
Ha, yeah. That's what I meant. I changed the wrong is!

2023-09-19 21:09 UTC, ShaneDuncan602 commented on src/example/ERC721/upgradeable/ApplicationERC721UpgAdminMint.sol
> +contract ApplicationERC721Upgradeable is ProtocolERC721U {
Yep, sorry. My external branch was behind the last couple of merges.

2023-09-19 21:15 UTC, oscarsernarosero commented on src/example/ERC721/not-upgradeable/ApplicationERc721AdminOrOwnerMint.sol
> +// SPDX-License-Identifier: UNLICENSED
This is what was causing the build to fail in GitHub. Thanks for saving me a ton of frustration.

2023-09-20 14:15 UTC, ShaneDuncan602 approved these changes
Looks really good.

2023-09-20 14:21 UTC, TJ-Everett approved these changes
Looks great Oscar!

2023-09-20 16:50 UTC, merged