External docker fixes
thrackle-io/forte-rules-engine-v1 pull request #155
Opened 2023-09-26 08:15 UTC by bfcoursewool

Some things in the docker stack broke due to new versions of stuff, and these are the fixes. Foundry must have updated, requiring a higher version of GLIBC than was provided by the "bullseye" release of Debian (which was the base image for the tron docker container). Upgrading from "bullseye" to "bookworm" introduced some issues with python... apparently python 3.11 requires the use of virtual environments, so I added that. Additionally, our one python dependency in the requirements.txt file, eth-abi, was pretty old, and that was also causing issues with python3.11 so I updated that as well. After lots of retries, it seems to be finally working again, huzzah!

2023-10-02 18:38 UTC, TJ-Everett commented on Dockerfile.tron
>  WORKDIR /usr/local/src/delylah
Can we rename this to tron from delylah?

2023-10-02 18:39 UTC, TJ-Everett requested changes
This is failing the GH tests - then also found a reference to Delylah

2023-10-02 21:27 UTC, bfcoursewool commented
> This is failing the GH tests - then also found a reference to Delylah

Ahh, so the same problem is happening on the GH workflow server... it's using Ubuntu 20.04 and it looks like the GLIBC version on that OS is also behind what we need. Gonna try to update the workflow to use a newer Ubuntu...

2023-10-02 21:40 UTC, bfcoursewool commented on Dockerfile.tron
>  WORKDIR /usr/local/src/delylah
Done

2023-10-03 13:25 UTC, TJ-Everett approved these changes
Looks good!

2023-10-04 18:24 UTC, oscarsernarosero approved these changes
Mental note: now we are using eth-abi 4.2.1 so expect some things to crash.

2023-10-04 18:24 UTC, merged