Se 286 break the application deployment into mutliple scripts
thrackle-io/forte-rules-engine-v1 pull request #158
Opened 2023-10-10 21:47 UTC by TJ-Everett

2023-10-11 15:24 UTC, ShaneDuncan602 commented on src/example/script/Application_Deploy_01_AppMangerAndAssets.s.sol
> +        nft1.connectHandlerToToken(address(applicationNFTHandler));
These assets need to be registered with the AppManager or none of the rules will work.

2023-10-11 15:25 UTC, ShaneDuncan602 commented on src/example/script/Application_Deploy_02_OracleAndPricing.s.sol
> +        applicationAppManager.registerToken("Frankenstein Picture", vm.envAddress("APPLICATION_ERC721_ADDRESS_1"));
Nevermind! It's here. Seems like maybe it should be in the other script though.

2023-10-11 15:44 UTC, ShaneDuncan602 approved these changes
One suggestion but it's not a big deal and will work either way. Also, when this goes to internal, it will be a difficult merge because staking and AMM's will need to be added.

2023-10-12 03:54 UTC, oscarsernarosero requested changes
I think splitting the script_01 is necessary to make sure it would be a successful and clean deployment on mainnet (testnet might behave much better so we can't really assume that mainnet will be just as smooth), Or! you could experiment with vm.sleep() cheatcode from Foundry to basically achieve the same result as splitting the script. If you go with the vm.sleep route, you could even rearrange  the order of deployment to better use the inactive (like deploy first all the token contracts, then wait, then deploy all the token handlers, then wait, then connect them all, etc.)

2023-10-12 03:54 UTC, oscarsernarosero commented on src/example/script/Application_Deploy_01_AppMangerAndAssets.s.sol
> + * @title Application Deploy App Manager Script
add 01 here somewhere

2023-10-12 03:54 UTC, oscarsernarosero commented on src/example/script/Application_Deploy_02_OracleAndPricing.s.sol
> + * @title Application Deploy All Script
add 02 here somewhere

2023-10-12 03:54 UTC, oscarsernarosero commented on src/example/script/Application_Deploy_01_AppMangerAndAssets.s.sol
> +        applicationAppManager.registerToken("Clyde Picture", address(nft1));
I only have an issue with these 3 tokens being deployed all at the same time since from previous experience this seems too much for the blockchain to handle all at once. I would suggest going as granular as deploying token by token. Might seem too conservative, but I think that way we can secure a good result. 

Another option here, and this might be something you want to play with, is introducing some inactive periods of time between the deployments of the tokens using [vm.sleep()](https://book.getfoundry.sh/cheatcodes/sleep). I have never used it, and I don't know if that would work, but I think it's worth the shot if you don't think splitting this in 4 pieces is a good idea.

2023-10-12 13:22 UTC, TJ-Everett commented on src/example/script/Application_Deploy_01_AppMangerAndAssets.s.sol
> +        applicationAppManager.registerToken("Clyde Picture", address(nft1));
Given that this is most likely going to be used on mainnet next, I don't want to try anything too risky / new. I can happily break these up into per token if you think that is necessary, however my concern with a per token script is that you might as well use the individual forge create commands at that point instead of a script. 

In the user guides we tell devs to go this route as these scripts would be just for internal use.

2023-10-12 13:37 UTC, ShaneDuncan602 commented
> I think splitting the script_01 is necessary to make sure it would be a successful and clean deployment on mainnet (testnet might behave much better so we can't really assume that mainnet will be just as smooth), Or! you could experiment with vm.sleep() cheatcode from Foundry to basically achieve the same result as splitting the script. If you go with the vm.sleep route, you could even rearrange the order of deployment to better use the inactive (like deploy first all the token contracts, then wait, then deploy all the token handlers, then wait, then connect them all, etc.)

Hmm, this is very interesting. First, I agree that it might be a good idea to even split the first script up more. It may be a little overkill but I'd rather do too much than too little. However, the vm.sleep seems like a route we should investigate. I didn't even know it existed. Shouldn't be too hard to put it into the UI script and test it.

2023-10-12 14:54 UTC, TJ-Everett commented
Further broke out the scripts so that each token is deployed via its own script as well as broke up the oracle and pricing scripts to ensure they are as light as possible. 

When trying to use vm.sleep() in the ApplicationDeployAll.s.sol file it looks like we do not have that function in the VM.sol list in the lib. This needs to be added to the lib > forge-std > src > VM.sol functions list.

2023-10-12 16:04 UTC, TJ-Everett commented
Updating to the newest release of Foundry will also solve this issue and be significantly less "hacky".

2023-10-12 18:54 UTC, oscarsernarosero approved these changes
Looks great Tayler

2023-10-12 18:56 UTC, merged