Se 291 create foss style oracle and rule structure
thrackle-io/forte-rules-engine-v1 pull request #159
Opened 2023-10-11 06:46 UTC by oscarsernarosero

### Don't merge this branch!

A list of assumptions and design guidelines alongside a diagram of the interaction of the different parts can be found [here](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/195362829/FOSS+Style+Oracle). 

Besides the doc, the unit test is very telling.

I understand now the necessity for 2 separate oracles since there are 2 very different processes (validation of address and staking process), and separating them might even simplify a bit the current oracle contract. For right now tho, this is a good proof of concept.

2023-10-11 13:44 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
Probably doesn't matter for this POC, but we will need to change the name of this in the future. It will need to be more generic.

2023-10-11 13:57 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
> +            _status = uint8(statusPerAccount[account]) - 1;
What if the status is 0 here?

2023-10-11 14:02 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
> +        if(balance < gasUsed) revert NotEnoughDeposit(gasUsed);
Would we really want to revert this if the client didn't send enough gas to begin with? They sent the minimum amount so that is really on the dev. If this reverts, the user would have no way of knowing their request is in limbo. Also, I wonder if the offchain would send a single check at a time or if it would send a batch of them.

2023-10-11 14:04 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
> +    function withdrawAmount(uint256 _amount) external onlyOwner(){
Why is this modifier different than the other onlyOwners? It has onlyOwner() where the others are just onlyOwner with no parenthesis.

2023-10-11 14:05 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
> +        if (oracleOrigin == address(0x00)) revert OracleOriginNotSet();
So they could only withdraw the funds to by transferring them to the token contract?

2023-10-11 14:12 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +        if (status == 0) revert OracleCheckFailed("ACCOUNT DENIED");
We wouldn't want this to revert here. This oracle check needs to only send back the result unless it blows up. If they are denied, the handler or token could decide to revert, but I think it's best to leave that decision to that point. That would probably be better than making them use a try/catch because they may need to change some state. The scenario I'm thinking of is if they are already staked and this is a recheck.

2023-10-11 14:18 UTC, ShaneDuncan602 commented on src/example/ApplicationERC721HandlerWStatusOracle.sol
> +            (status, _requestId) = ruleProcessor.checkStatusOraclePasses{value: msg.value}(statusOracleRuleId, account, msg.sender);
Does it save gas to not have the return statements? I see a lot of people omitting these so it makes me wonder.

2023-10-11 14:23 UTC, ShaneDuncan602 commented on src/token/ProtocolERC721WSoftStaking.sol
> +}
I don't think we would need this contract. This would be a minimal implementation that would only need the interface. We currently only have the IProtocolERC721UMin.sol which is for upgradeable but it could be easily modified to work by changing the import. The way you have this works but we will eventually use this to get more accurate gas assessments so we probably want to keep the protocol footprint as small as possible.

2023-10-11 14:25 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("HandlerFailed(bytes)", abi.encodeWithSignature("OracleCheckFailed(bytes)", abi.encodeWithSignature("NotEnoughDeposit(uint256)",MIN_GAS_DEPOSIT ))));
this is pretty cool

2023-10-11 14:27 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +        softStakingNft.stakeNFT{value: MIN_GAS_DEPOSIT}(1);
We should add a check to make sure the event it emitted since it's so important to the whole process.

2023-10-11 14:28 UTC, ShaneDuncan602 requested changes
Great job, dude. I have a few suggestions and quite a few questions, but you killed this. The test is very thorough too.

2023-10-11 16:31 UTC, TJ-Everett reviewed
I don't have any additional changes/questions other than what Shane has already asked.

2023-10-11 18:25 UTC, oscarsernarosero commented on src/Oracle/SoftStakingOracle.sol
> +            _status = uint8(statusPerAccount[account]) - 1;
it would return a 255, but it never actually gets there because that would trigger an offchain check which then would result in returning a PENDING status or "2".

2023-10-11 18:28 UTC, oscarsernarosero commented on src/Oracle/SoftStakingOracle.sol
> +        if(balance < gasUsed) revert NotEnoughDeposit(gasUsed);
I see it as a malicious/extremeGasPrice security measure. We can build a function to deposit more gas to a Request in case this happens (would also need a frontend to notify about this). I didn't want to spend more time on it since JB has made it clear this is just a POC. Good to through if we decide to take this on tho.

2023-10-11 18:30 UTC, oscarsernarosero commented on src/Oracle/SoftStakingOracle.sol
> +    function withdrawAmount(uint256 _amount) external onlyOwner(){
ah! That was just me. It is the same since the parenthesis has no effect. Im removing them.

2023-10-11 18:33 UTC, oscarsernarosero commented on src/Oracle/SoftStakingOracle.sol
> +        if (oracleOrigin == address(0x00)) revert OracleOriginNotSet();
They are sending it to the offchain signer of the oracle since that is the contract that is actually paying for the gas. I named that account as OracleOrigin although maybe a better name would be DataProvider. You would prob come up with a better name, so Im opened to suggestions there.

2023-10-11 18:38 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +        if (status == 0) revert OracleCheckFailed("ACCOUNT DENIED");
Ok. I disagree here but let's take this to @jjbailey-io. I personally think a try catch is a good idea since that way we don't break the pattern of the other rules and we have effectively the same functionality. Also, a _recheck_ wouldn't cause a revert since the address would have an APPROVED/DENIED state.

2023-10-11 18:41 UTC, oscarsernarosero commented on src/example/ApplicationERC721HandlerWStatusOracle.sol
> +            (status, _requestId) = ruleProcessor.checkStatusOraclePasses{value: msg.value}(statusOracleRuleId, account, msg.sender);
I don't think it saves gas. To me it's just less lines of code. It has the return statement and the variable creation implicit in the `returns (uint8 status, uint128 _requestId)`

2023-10-11 18:46 UTC, oscarsernarosero commented on src/token/ProtocolERC721WSoftStaking.sol
> +}
ok. So you're saying I should delete some of these functions? maybe the pause functions?

2023-10-11 18:48 UTC, oscarsernarosero commented on test/ApplicationERC721.t.sol
> +        softStakingNft.stakeNFT{value: MIN_GAS_DEPOSIT}(1);
I did try this but foundry didn't recognize the vm.expectEmit cheatcode. I'll try again, although I did check in the logs that it was emitting the event.

2023-10-12 13:40 UTC, ShaneDuncan602 commented on src/Oracle/SoftStakingOracle.sol
> +        if (oracleOrigin == address(0x00)) revert OracleOriginNotSet();
Ok, I was thinking oracleOrigin was the asset.

2023-10-12 13:40 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +        if (status == 0) revert OracleCheckFailed("ACCOUNT DENIED");
It was decided to keep the revert in order to not stray too far from the current rule logic.

2023-10-12 13:54 UTC, ShaneDuncan602 commented on src/token/ProtocolERC721WSoftStaking.sol
> +contract ProtocolERC721 is IProtocolERC721Min, ERC721Enumerable, ProtocolTokenCommon, Ownable {
I was thinking that the IProtocolERC721Min would be implemented directly by the Application example but I guess it really isn't much different than this. This should provide comparable gas tests. Good job.

2023-10-12 13:58 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +        softStakingNft.stakeNFT{value: MIN_GAS_DEPOSIT}(1);
It seems strange that Foundry makes you put line 320 in there. That's how it works but it seems odd. I think Foundry needs to put some extra work into it.

2023-10-12 13:59 UTC, ShaneDuncan602 approved these changes
Looks really good. Great job on this.

2023-10-12 14:11 UTC, TJ-Everett approved these changes
Looks Great Oscar, very well done.

2023-11-21 06:27 UTC, closed without merging