Se 287 rbac restructure
thrackle-io/forte-rules-engine-v1 pull request #162
Opened 2023-10-16 16:53 UTC by oscarsernarosero

Implemented the migration for superAdmin role and the at-least-one-admin policy for all the other admins.

Highlights:

- Only-one-super-admin-per-app rule was implemented. `grantRole` function had to be overridden to revert when invoked to effectively force all role grants to be done through the appropriate functions in the appManager.
- A new internal role was created to make the transition of the super-admin role possible: PROPOSED_SUPER_ADMIN. This role doesn't emit any events because of its internal nature.
- The super-admin role can be migrated to another address through a 2-step propose-confirm mechanism for security reasons.
- The functions `revokeRole` and `renounceRole` were overridden to enforce the at-least-one-admin policy.
- The docs were updated and a table with the role hashes was added.

# Update

After some iterations with the team, it was decided that only the SupeAdmins would have the restriction of at least 1 superAdmin account. All other roles can have 0 members.

2023-10-16 18:38 UTC, TJ-Everett commented on src/application/AppManager.sol
> +     * @param account address losing to the role.
address of revoked role*

2023-10-16 18:38 UTC, TJ-Everett commented on src/application/AppManager.sol
> +        if(role != PROPOSED_SUPER_ADMIN_ROLE && getRoleMemberCount(role) < 2) revert CannotRenounceIfOnlyOneAdmin();
This should not be a magic number and in my opinion we (SUPER_ADMINs)  should be able to set this threshold for their ecosystem.

2023-10-16 18:38 UTC, TJ-Everett commented on src/interfaces/IErrors.sol
>  }
If we change to a threshold variable that is settable, we may want to change this to CannotRenounceIfBelowMinAdminThreshold() or something similar.

2023-10-16 18:38 UTC, TJ-Everett commented on test/AppManager.t.sol
> +        /// now let's porpose some superAdmins to make sure that only one will ever be in the app
propose*

2023-10-16 18:38 UTC, TJ-Everett commented on test/AppManager.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x420));
We shouldn't use meme addresses to this level, in my opinion (We should assume everything we add to the repo is a public reflection of Thrackle. Sorry to be fun police here)

2023-10-16 18:38 UTC, TJ-Everett commented on test/AppManager.t.sol
> +        /// now let's confirm it, but let's make sure only the porposed
proposed

2023-10-16 18:38 UTC, TJ-Everett commented on test/ApplicationAppManager.t.sol
> +        /// now let's porpose some superAdmins to make sure that only one will ever be in the app
propose

2023-10-16 18:38 UTC, TJ-Everett commented on test/ApplicationAppManager.t.sol
> +        /// now let's confirm it, but let's make sure only the porposed
Proposed

2023-10-16 18:39 UTC, TJ-Everett commented on test/ApplicationAppManager.t.sol
>      }
Is the reason to have this test duplicated in two test files in order too ensure the Application contract inherits the RBAC structure correctly?

2023-10-16 18:40 UTC, TJ-Everett requested changes
This is really good Oscar. I have a suggestion on the threshold amount for admins and a few typos but others great work. This is exactly what the roles needed.

2023-10-16 18:45 UTC, ShaneDuncan602 commented on src/application/AppManager.sol
> +    }
This is good. We need to control access to these roles to only be our allowed channels.

2023-10-16 18:46 UTC, ShaneDuncan602 commented on src/application/AppManager.sol
> +        if(role != PROPOSED_SUPER_ADMIN_ROLE && getRoleMemberCount(role) < 2) revert CannotRenounceIfOnlyOneAdmin();
I agree about the magic number. It should be a constant. As for if they can set it, it was decided that there should only be 1. That was to appease ToB.

2023-10-16 18:50 UTC, oscarsernarosero commented on src/application/AppManager.sol
> +        if(role != PROPOSED_SUPER_ADMIN_ROLE && getRoleMemberCount(role) < 2) revert CannotRenounceIfOnlyOneAdmin();
That makes sense. The check is for any admin tho (except for PROPOSED_SUPER_ADMIN_ROLE).

2023-10-16 18:50 UTC, ShaneDuncan602 commented on src/application/AppManager.sol
> +        super.grantRole(PROPOSED_SUPER_ADMIN_ROLE, account);
This was a good way to fix this. The PROPOSED_SUPER_ADMIN_ROLE is an elegant solution.

2023-10-16 18:52 UTC, ShaneDuncan602 commented on src/application/AppManager.sol
> +        }
This is better than reverting and forcing them to revoke the proposed super. Good idea.

2023-10-16 18:52 UTC, oscarsernarosero commented on test/AppManager.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x420));
you just have to suck the fun out everything, don't you. Jk. You're right

2023-10-16 18:52 UTC, oscarsernarosero commented on src/application/AppManager.sol
> +        super.grantRole(PROPOSED_SUPER_ADMIN_ROLE, account);
Thank you Shane

2023-10-16 18:53 UTC, TJ-Everett commented on test/AppManager.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x420));
🚔

2023-10-16 18:55 UTC, ShaneDuncan602 commented on src/interfaces/IErrors.sol
>  }
Agreed. Something generic would probably be better.

2023-10-16 18:56 UTC, ShaneDuncan602 commented on test/AppManager.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x420));
Agreed. Probably better to use less risque numbers.

2023-10-16 18:58 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x420));
Same as above

2023-10-16 18:58 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
We need to add the error to this. ToB flagged non-specific expectReverts as an issue.

2023-10-16 19:01 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
>      }
That was the original intention behind not getting rid of AppManager.t.sol. I don't think it's necessary to have this test in both but I don't think it will hurt either.

2023-10-16 19:01 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
Can we add the error here?

2023-10-16 19:02 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
Specific error?

2023-10-16 19:05 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
I'm not sure we wanted to restrict them from having 0 RiskAdmins and AccessTierAdmins. Wasn't it just for SuperAdmins and AppAdmins? Maybe we should get clarification on this from @jjbailey-io

2023-10-16 19:08 UTC, ShaneDuncan602 requested changes
Just a few things and a question for JB.

2023-10-16 19:26 UTC, jjbailey-io commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
I agree, we shouldn't enforce >0 Risk/AccessTier admins. I think if they aren't using that feature they shouldn't be required to populate it. We wanted this implemented for Super Admins because it's detrimental and there is no way to recover the system if that happens. Risk/AccessTier admins could be re-added by the AppAdmins if they lose access.

2023-10-16 19:37 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
>      }
Yeah I just did it in both tests, but Im not sure why we have two tests for the appManager

2023-10-16 19:45 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
ok. So the restriction is only for super admins and app admins? The document related to the ticket does mention all admin roles, but Im ok to limit the check to those admins. Just to make sure we are making an informed decision here, this doesn't mean necessarily that risk or tier admins have to have at least 1 admin since the requirement is only enforced when renouncing/revoking which means that if you never set an admin then this will never apply to your app. It only becomes relevant when you have already added accounts to these roles and then you want to renounce/revoke.

2023-10-16 20:07 UTC, TJ-Everett commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
I too want to clarify. So we would have:
Minimum of 1 in these roles always: 
SUPER_ADMIN
APP_ADMIN

No minimum number of admins: 
ACCESS_TIER_ADMIN
RISK_ADMIN
RULE_ADMIN
?

2023-10-16 20:48 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
added

2023-10-16 20:48 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
added

2023-10-16 20:48 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert();
added

2023-10-17 14:02 UTC, jjbailey-io commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
I don't think we should enforce a minimum for any admin accounts except super admin. The minimum check on super admins is to ensure we never get into a state where we can't add/remove new admins. This is still an issue if we lose access to keys, but we're assuming we're not losing access to accounts for this. So I'm proposing:
- Minimum of 1 in these roles always:
    - SUPER_ADMIN
- No minimum number of admins:
    - APP_ADMIN
    - ACCESS_TIER_ADMIN
    - RISK_ADMIN
    - RULE_ADMIN

As long as the developer has access to SUPER_ADMIN they should be able to recover access to the other roles. Thoughts?

2023-10-17 14:30 UTC, ShaneDuncan602 commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
Technically, we wouldn't need to enforce a minimum on AppAdmin either. They wouldn't be able to really do anything in their assets but that's on them. They would be fine as long as the SuperAdmin exists and is usable. If they lose their SuperAdmin, they are in big trouble unless they have all the admins defined that they need.

2023-10-17 18:37 UTC, oscarsernarosero commented on test/ApplicationAppManager.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("CannotRenounceIfOnlyOneAdmin()"));
Ok. Only superAdmins have such restriction now.

2023-10-17 18:42 UTC, ShaneDuncan602 approved these changes
Looks great!

2023-10-17 19:01 UTC, TJ-Everett approved these changes
Approved. Looks great Oscar, well done.

2023-10-17 19:02 UTC, merged