Se 356 create a markdown for the minimum account balance by date rule
thrackle-io/forte-rules-engine-v1 pull request #169
Opened 2023-10-25 20:50 UTC by oscarsernarosero

2023-10-25 21:06 UTC, TJ-Everett commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +
These should either all start with a capitol letter or none should. My vote is for capitols.

2023-10-25 21:10 UTC, TJ-Everett commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +4. The processor will evaluate if such sub-rule's period is still active. If it is, the processor will then evaluate if the final balance of the account will be less than the minimum balance set in t
If the final balance after transaction is less than the minimum, the transaction will revert. *

2023-10-25 21:14 UTC, TJ-Everett commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +This rule doesn't have any dependency.
Would the rule be dependent on the account being tagged as well as the dates for the rule? IDK how we want to define dependencies for rules vs other sections of the protocol.

2023-10-25 21:14 UTC, TJ-Everett reviewed
Just a few spelling suggestions and a question. Otherwise I like this a lot Oscar.

2023-10-25 21:48 UTC, anne-thrackle reviewed
Overall this was quite good, I left some phrasing suggestions for clarity.

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The purpose of this rule is to avoid ERC20 token holders to flood the market with their new tokens since this could effectively drive the supply up dramatically and, with it, cause a token price cras
```suggestion
The purpose of the minimum-balance-by-date rule is to prevent ERC20 token holders from rapidly flooding the market with newly acquired tokens. A dramatic increase in supply over a short time frame can cause a token price crash; this rule mitigates this scenario. This rule attempts to cool down traders by making them wait some period of time before they can sell their new tokens. The length of time depends on the account's tags. Different accounts may need to wait different periods of time depending on their tags, or even no time at all.
```
What are tags? 
I'm not sure what is meant by "cool down".

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +This rule works at a token level which means that it has to be activated and configured in each token handler it is desired to enforce this rule.
```suggestion
This rule works at a token level. It must be activated and configured for each token desired in the corresponding token handler.  
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +Due to the tagged nature of this rule, you can think of it as a collection of rules, where each "sub-rule" is totally independent from each other, and where each "sub-rule" is indexed by its tag. The
I might be getting this wrong since I'm guessing what "tags" are. 
```suggestion
As this is a tag-based rule, you can think of it as a collection of rules, where all "sub-rules" are independent from each other, and where each "sub-rule" is indexed by its tag. A minumum-balance-by-date "sub-rule" is specified by 3 variables:
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +- Hold amount (uint256).
```suggestion
- hold amount (uint256).
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +- Hold amount (uint256).
might be useful here to briefly say what these variables are for. Particularly for "hold amount", it isn't obvious to me what it means. From reading the "Rule Processing" section at the end I understand it's the minimum balance the account has to maintain.

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +There is no limit in the amount of sub-rules that a rule can have other than at least one sub-rule.
```suggestion
A minimum-balance-by-date rule must have at least one sub-rule. There is no maximum number of sub-rules. 
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +### Rule Registering
```suggestion
### Registering the Rule
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The registering function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges.
is this true across all rules?

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The function will return the protocol id of the rule.
```suggestion
The registering function will return the protocol id of the rule.
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +## Rule Processing
I wonder if this section should be higher up in the doc, like maybe after the Data Structure section? I think I'd want to understand this before understanding how to register it. 

Also debating whether I like the wording, vs. something like "Rule Logic" or "What this Rule Does"

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +2. The processor will receive these tags alongside the id of the minimum-balance-by-date rule set in the token handler.
```suggestion
2. The processor will receive these tags along with the ID of the minimum-balance-by-date rule set in the token handler. 
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +3. The processor then will try to retrieve the sub-rule associated with each tag of the account.
```suggestion
3. The processor will then try to retrieve the sub-rule associated with each tag.
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +4. The processor will evaluate if such sub-rule's period is still active. If it is, the processor will then evaluate if the final balance of the account will be less than the minimum balance set in t
```suggestion
4. The processor will evaluate whether each sub-rule's hold period is still active (if the current time is within `hold period` from the `starting timestamp`). If it is, the processor will then evaluate if the final balance of the account would be less than the `hold amount` if the transaction completed. If yes, then the transaction will revert.
```

2023-10-25 21:48 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +5. The step 4 is repeated for each tag of the account.
```suggestion
5. Step 4 is repeated for each of the account's tags. 
```

2023-10-26 17:54 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +### Rule Registering
just noticed in https://github.com/thrackle-io/tron/blob/internal/docs/userGuides/rules/APP-RULE-DIRECTORY.md we refer to this as "Create Function" (I think it's the same thing?). Perhaps we should decide whether to use the words create/creation or register and be consistent (especially because register <> activate, right?)

2023-10-26 19:19 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The purpose of this rule is to avoid ERC20 token holders to flood the market with their new tokens since this could effectively drive the supply up dramatically and, with it, cause a token price cras
Ok. I mostly accepted your suggestion. I deleted the "cool down" part (it means to calm down someone that is in a excited or frantic stage). Interesting to see you using the ";". I replaced it with a simple "." tho. I think it is not used anymore here. Don't ask me why.

2023-10-26 19:33 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +### Rule Registering
Yes. Great catch!

2023-10-26 19:33 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The registering function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges.
it is.

2023-10-26 20:38 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The registering function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges.
```suggestion
The create function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges. 
```

2023-10-26 20:38 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The registering function will return the protocol ID of the rule.
```suggestion
The create function will return the protocol ID of the rule.
```

2023-10-26 20:38 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +Registering a minimum-balance-by-date rule is done through the function:
```suggestion
Adding a minimum-balance-by-date rule is done through the function:
```
or "creating"

2023-10-26 20:39 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +Registering a minimum-balance-by-date rule is done through the function:
```suggestion
Adding a minimum-balance-by-date rule is done through the function:
```
or "creating"

2023-10-26 20:56 UTC, TJ-Everett approved these changes
Looks great Oscar

2023-10-26 20:56 UTC, anne-thrackle approved these changes
looks good to me at far as content, clarity, organization. Not being that familiar with the logic itself I'm not confirming the correctness here but someone else can do that

2023-10-27 13:54 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The purpose of the minimum-balance-by-date rule is to prevent ERC20 token holders from rapidly flooding the market with newly acquired tokens since a dramatic increase in supply over a short time fra
This can also be applied to 721's. The intention there would be to force holders to keep the asset for a specified minimum amount of time. This could be for earned assets or achievements so they aren't immediately traded.

"mitigates" should be "mitigate". 

We should probably say, "before they can transfer their tokens" instead of "sell their tokens"

2023-10-27 13:57 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +- ERC20
Also ERC721

2023-10-27 14:00 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +
Shouldn't the tags parameter be here as well?

2023-10-27 14:03 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +    }
We need to be careful about how we define this for clients. This struct is on a per-tag basis so we should make that clear or it might get confusing.

2023-10-27 14:04 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +Additionally, each one of these data structures will be under a tag (bytes32):
Ok, I see that distinction here. I'm not sure that it's clear though. We need to set a good example for this now because it will repeat quite a bit.

2023-10-27 14:05 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +    - This rule doesn't apply when a **registered treasury** address is in the *to* side of the transaction.
Only for ERC20 transfers

2023-10-27 14:08 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> + ```javascript
Is there a reason we are labelling some code snippets as javascript or C?

2023-10-27 14:08 UTC, ShaneDuncan602 requested changes
Some small suggestions and additions. Each one of these keeps getting better than the last.

2023-10-27 14:46 UTC, anne-thrackle commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +5. Step 4 is repeated for each of the account's tags.
You can take or leave these comments. 

I was a little bothered by the phrasing "the account will pass the tags to the protocol" which made it seem like the account could send false information about its tags (which I'm sure is not the case in practice). 

I also wondered what the point of the processor receiving the ID of the rule was, since it wasn't mentioned as being used in the rest of the steps. Should it be that it retrieves the sub-rule for each tag _for that rule ID_? 

When you wrote "the process will try to retrieve..." - is it important to include here what happens if it fails to retrieve them? Or can we just say "it retrieves" and the failure case is obvious/implied (i.e. the transaction fails). 

```suggestion
1. The processor receives the following information: 
    - for the account being evaluated, the tags registered to its address in the application manager. 
    - the ID of the minimum-balance-by-date rule set in the token handler. 
2. The processor retrieves the sub-rule associated with each tag.
3. The processor evaluates whether each sub-rule's hold period is still active (if the current time is within `hold period` from the `starting timestamp`). If it is, the processor then evaluates whether the final balance of the account would be less than the `hold amount` in the case of the transaction succeeding. If yes, then the transaction will revert.
4. Step 3 is repeated for each of the account's tags. 
```

2023-10-27 17:38 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> + ```javascript
yes. It's because it doesn't recognize solidity, so I try to play with it to have the most amount of colors

2023-10-27 17:39 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +The purpose of the minimum-balance-by-date rule is to prevent ERC20 token holders from rapidly flooding the market with newly acquired tokens since a dramatic increase in supply over a short time fra
ah ok. I got confused by the rule being processed in the ERC20TaggedRules

2023-10-27 17:42 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +
that's in the Create Function section

2023-10-27 17:46 UTC, oscarsernarosero commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +    }
I honestly think I made it very clear since I spend the rest of the section explaining just that.

2023-10-27 19:20 UTC, ShaneDuncan602 approved these changes
Looks great!

2023-10-30 14:58 UTC, jjbailey-io approved these changes

2023-10-30 15:09 UTC, merged