Se 381 research ERC721C and implement an example integration in tron
thrackle-io/forte-rules-engine-v1 pull request #170
Opened 2023-10-26 15:11 UTC by TJ-Everett

DO NOT MERGE BRANCH 

This branch serves as a POC for the ERC721C and ERC721CW integration into the protocol. This is a rough first pass to ensure this was even possible. Many more iterations and improvements should be made prior to full integration into the external branch. 
Additional gas testing should also be conducted to fully understand the impacts of this contract suite compared to the current versions of ERC721 the protocol is utilizing

DO NOT MERGE BRANCH

2023-10-26 21:16 UTC, oscarsernarosero reviewed
This is really good in general. Im not sure if this within the scope of the ticket, but since you are already doing some tests in here, I think some tests on the functionality of the ERC721C should be added. You can demonstrate how to configure the operator whitelists and some of the security configurations, for example. I think a gas analysis with those configurations on would be much more realistic than without them.

2023-10-26 21:16 UTC, oscarsernarosero commented on src/example/ERC721/NonProtocolERC721.sol
> +    error PriceNotSet();
These errors suggest you need to buy the NFTs, but that's not the case here. It's kinda confusing.

2023-10-26 21:16 UTC, oscarsernarosero commented on src/example/ERC721/NonProtocolERC721.sol
> +    error TreasuryAddressNotSet();
Same with these and others down below. It suggests you have withdrawal functions and a treasury, but there is non of these.

2023-10-26 21:16 UTC, oscarsernarosero commented on src/example/StakingWrapper.sol
> +        require(handler.checkAllRules(from == address(0) ? 0 : balanceOf(from), to == address(0) ? 0 : balanceOf(to), from, to, batchSize, tokenId, ActionTypes.TRADE));
Not relevant for this PR, but Im just noticing we don't have this in the ERC20. Might be worth it revisiting this later.

2023-10-26 21:16 UTC, oscarsernarosero commented on src/token/ERC721/ProtocolERC721.sol
> +contract ProtocolERC721 is ERC721Burnable, ERC721URIStorage, ERC721Enumerable, Pausable, ProtocolTokenCommon, AppAdministratorOrOwnerOnly, ERC721C {
So we are using now ERC721C as our default and official ERC721 token? I think we should have ProtocolERC721 and ProtocolERC721C since the C is heavier in gas consumption.

2023-10-26 21:16 UTC, oscarsernarosero commented on test/ERC721/ApplicationERC721.t.sol
I would say, you need some dedicated tests for the ERC721C in this file to test the functionalities.

2023-10-26 21:16 UTC, oscarsernarosero commented on test/ERC721/ERC721CGasTest.t.sol
For what I know about the ERC721C, you can set some operator whitelists and you can have some security configurations (restrict NFT receivers to be only EOAs or contracts with no code, or senders cannot be contracts, etc). I think the gas should be analyzed with those configurations on since that's most likely how this is going to be used.

2023-10-26 21:16 UTC, oscarsernarosero commented on src/token/ERC721/ProtocolERC721.sol
> +contract ProtocolERC721 is ERC721Burnable, ERC721URIStorage, ERC721Enumerable, Pausable, ProtocolTokenCommon, AppAdministratorOrOwnerOnly, ERC721C {
ok never mind. We are not merging this branch so you're good.

2023-10-27 13:30 UTC, TJ-Everett commented on test/ERC721/ApplicationERC721.t.sol
I agree that we should test out functionality more than this, however I think that should be an additional ticket. Since this was just to ensure protocol integration. They have some really interesting royalty payment splitting going on also that we should further test if we are going to fully integrate this version of ERC721.

2023-10-27 14:24 UTC, ShaneDuncan602 commented on src/example/ERC721/NonProtocolERC721.sol
> +     * @dev Function mints a new token to anybody. Don't enabled this function if you are not sure about what you're doing.
The second statement needs reworked

2023-10-27 14:32 UTC, ShaneDuncan602 commented on test/ERC721/ApplicationERC721.t.sol
I'm not sure if it's a full POC if the royalties aren't in here. We have proven a rule can be applied to ERC721C, but I think we also need to know for certain that a 2981 royalty can be enforced on a transfer. Would it be too much to add one of LimitBreak's simple royalty interfaces to this or would it increase the scope of this ticket too much?

2023-10-27 14:35 UTC, ShaneDuncan602 commented on test/ERC721/ApplicationERC721.t.sol
> +        uint32 _index = RuleDataFacet(address(ruleStorageDiamond)).addTransferVolumeRule(address(applicationAppManager), 2000, 2, Blocktime, 10);
This was purposely set at 0 to test if the transfer volume rule could be used to turn a NFT into a soul bound token.

2023-10-27 14:36 UTC, ShaneDuncan602 commented on test/ERC721/ApplicationERC721.t.sol
Also, I think all tests related to 721C should be in separate test contracts. We would want to keep the current tests the same.

2023-10-27 14:39 UTC, ShaneDuncan602 commented on src/example/StakingWrapper.sol
> +import "@limitbreak/creator-token-contracts/contracts/erc721c/extensions/AdventureERC721CW.sol";
Is there a reason we're using their AdventureERC721CW instead of the ERC721CW template?

2023-10-27 14:39 UTC, ShaneDuncan602 requested changes
Really cool stuff. Just a few questions and suggestions.

2023-10-27 14:45 UTC, TJ-Everett commented on src/example/ERC721/NonProtocolERC721.sol
> +     * @dev Function mints a new token to anybody. Don't enabled this function if you are not sure about what you're doing.
This is from the free mint contract so I will also rework the statement in my documents ticket I am working so it gets merged to external and not lost. Great catch.

2023-10-27 14:46 UTC, TJ-Everett commented on src/example/ERC721/NonProtocolERC721.sol
> +    error TreasuryAddressNotSet();
Yeah, I was using the mintFee at first and then switched to a regular free mint so I can clean these up.

2023-10-27 14:46 UTC, TJ-Everett commented on test/ERC721/ApplicationERC721.t.sol
> +        uint32 _index = RuleDataFacet(address(ruleStorageDiamond)).addTransferVolumeRule(address(applicationAppManager), 2000, 2, Blocktime, 10);
Gotchya, I will ensure this still works as intended or document why it doesn't in the write up.

2023-10-27 14:47 UTC, TJ-Everett commented on src/example/StakingWrapper.sol
> +import "@limitbreak/creator-token-contracts/contracts/erc721c/extensions/AdventureERC721CW.sol";
No great catch, I can inherit from the regular in the testing rework.

2023-10-27 14:49 UTC, TJ-Everett commented on test/ERC721/ApplicationERC721.t.sol
I will rework the tests so that that we have a ProtocolERC721C and test suite associated to it. Since this will take some thought anyway, I can try and work in some of the royalty payment tests at the same time. I am going to time box myself to 1 working day and if I cannot get it done will spawn another ticket from this one to continue it.

2023-10-30 23:08 UTC, oscarsernarosero approved these changes
Looks good to me Tayler. Good job.

2023-10-31 14:07 UTC, ShaneDuncan602 commented on src/example/ERC721/NonProtocolERC721.sol
> +     * @dev Function mints a new token to anybody. Don't enabled this function if you are not sure about what you're doing.
I think this was missed. It was the " Don't enabled this function if you are not sure about what you're doing."

2023-10-31 14:12 UTC, TJ-Everett commented on src/example/ERC721/NonProtocolERC721.sol
> +     * @dev Function mints a new token to anybody. Don't enabled this function if you are not sure about what you're doing.
I corrected this in the Docs branch I was working on - since this wasn't a merge branch that way it was corrected in the external branch. I will correct here as well to "Function mints a new token freely without restriction. This function should only be enabled if you are certain you want a free mint with no restrictions."

2023-10-31 14:16 UTC, ShaneDuncan602 approved these changes
Great job and a huge amount of effort on this. It looks really good.

2023-10-31 16:48 UTC, TJ-Everett commented
Closing PR as this was not a merge branch.

2023-10-31 16:48 UTC, closed without merging