first draft of the pause rule
thrackle-io/forte-rules-engine-v1 pull request #171
Opened 2023-10-27 05:53 UTC by oscarsernarosero

2023-10-27 13:42 UTC, ShaneDuncan602 commented on docs/userGuides/rules/PAUSE-RULE.md
> +    - This rule doesn't apply when an **app administrator** address is in either the *from* or the *to* side of the transaction. This doesn't necessarily mean that if an app administrator is the one
The second statement seems contradictory to the first.

2023-10-27 13:47 UTC, ShaneDuncan602 commented on docs/userGuides/rules/PAUSE-RULE.md
> +    - This rule doesn't apply when a **registered treasury** address is in the *to* side of the transaction.
I'm not sure this is the case when a 721 is transferred. Probably need to mention that it's only in the case of 20's.

2023-10-27 13:48 UTC, ShaneDuncan602 commented on docs/userGuides/rules/PAUSE-RULE.md
> +It is worth noting that this rule is special in the sense that it is not stored in the protocol but in the AppManager data contracts. Therefore, this rule doesn't have an ID like the other rules.
We might want to mention that this fact makes it unshareable with other applications.

2023-10-27 13:49 UTC, ShaneDuncan602 requested changes
Just a few clarifying things. I love this format.

2023-10-27 17:12 UTC, TJ-Everett commented on docs/userGuides/rules/PAUSE-RULE.md
> +- **PauseRuleEvent(uint256 indexed pauseStart, uint256 indexed pauseStop, bool indexed add)**: emitted when:
This raises a question: 
In the MinBalanceByDate rule doc we said there was no event emitted for the rule. 
There is for the creation but not for when the rule is checked. 
Do we want to include rule creation events in these docs? (my vote is yes)

2023-10-27 17:13 UTC, TJ-Everett reviewed
Content and format are looking great, Just one question for me.

2023-10-30 14:43 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-10-30 15:23 UTC, merged