Se 357 create a markdown file for the implementation of the transfer counter rule
thrackle-io/forte-rules-engine-v1 pull request #173
Opened 2023-10-27 17:02 UTC by TJ-Everett

This also has a small change to the ApplicationERC721FreeMint.sol commentary for the mint function. This was in another PR but that branch is not being merged.

2023-10-27 18:33 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
should be "and the prevention of malfeasance"

2023-10-27 18:35 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +There is no limit in the amount of sub-rules that a rule can have other than at least one sub-rule.
Should say, "no limit to the amount"

2023-10-27 18:38 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +    ) external ruleAdministratorOnly(_appManagerAddr) returns (uint32)
I wonder if we should mention that nftTypes are the same as tags?

2023-10-27 18:42 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +###### *see [RuleDataFacet](../../../src/economic/ruleStorage/RuleDataFacet.sol)*
I know this is where the rule is but it seems like it should be in TaggedRuleDataFacet.

2023-10-27 18:43 UTC, ShaneDuncan602 requested changes
Just a couple of minor changes.

2023-10-27 19:38 UTC, TJ-Everett commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +###### *see [RuleDataFacet](../../../src/economic/ruleStorage/RuleDataFacet.sol)*
I know what I have to do, but I don't know if I have the strength to do it. 

JK, I moved this and refactored the tests to reflect.

2023-10-27 19:42 UTC, anne-thrackle requested changes
a few typos and suggestions. Trying to be as consistent as possible with the min-balance-by-date one.

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
what is a collection?

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
why is "trades" in quotes? Do you mean a limit on the number of trades?

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
some phrasing suggestions for clarity, take or leave
```suggestion
The transfer-counter rule enforces a daily limit on number of trades for each token within a collection. In the context of this rule, a "trade" is a transfer of a token from one address to another. This rule has two potential purposes: to reduce volatility of token price in the collection, and prevent malfeasance from holders who transfer tokens back-and-forth between addresses repeatedly. When this rule is active and the `tradesAllowedPerDay` is 0 this rule will act the same as a "soulBound" token, preventing all transfers of tokens in the collection. 
```

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- startTs(uint64): The unnix timestamp for the time that the rule starts.
noting that formatting here is slightly different than what we have for the min-balance-by-date rule.

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- startTs(uint64): The unnix timestamp for the time that the rule starts.
```suggestion
- tradesAllowedPerDay(uint8): The number of trades allowed per tokenId of the collection while the rule is active 
- startTs(uint64): The unix timestamp for the time that the rule starts. 
```

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +This is a [tag](../GLOSSARY.md)-based rule, you can think of it as a collection of rules, where all "sub-rules" are independent from each other, and where each "sub-rule" is indexed by its tag. The t
```suggestion
This is a [tag](../GLOSSARY.md)-based rule, you can think of it as a collection of rules, where all "sub-rules" are independent from each other, and where each "sub-rule" is indexed by its tag. In this case, the tag is applied to the NFT collection address. The tranfer counter rule is composed of two components:
```

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- startTs(uint64): The unnix timestamp for the time that the rule starts.
this is getting super nit-picky, but we also didn't mention that it was a unix timestamp in the min-balance-by-date rule. Are all our timestamps unix?

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +There is no limit in the amount of sub-rules that a rule can have other than at least one sub-rule.
matching language in the minimum-balance-by-date rule docs.
```suggestion
A transfer-counter rule must have at least one sub-rule. There is no maximum number of sub-rules.
```

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +```
I'm trying to understand why you decided to depart from the phrasing pattern in the min-balance-by-date one. 
Why specify "... under a tagged NFT Collection" instead of "under a tag"? 
similarly, why "the tagged token collections" instead of "The collection of these tagged sub-rules"

Could I not use the same tag across multiple NFT Collections? 

I understand that the tags are associated with collections instead of accounts, but it seems like all the tag logic works the same. I might be missing something

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +4. The processor will evaluate whether the last transaction time for the tokenId is within the rule period from the starting timestamp. If yes, the rule will continue to the trades per day check. If
```suggestion
4. The processor will evaluate whether the last transaction time for the tokenId is within the rule period from the starting timestamp. If yes, the rule will continue to the trades per day check (step 5). If no, the rule will return the new trades per day value for the token Id. 
```

2023-10-27 19:42 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The registering function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges.
```suggestion
The create function in the protocol needs to receive the appManager address of the application in order to verify that the caller has Rule administrator privileges. 
```

2023-10-27 19:51 UTC, oscarsernarosero requested changes
Very good in general. I did add some sections to the MinBalanceByDate doc that should be here too. Also added some comments.

2023-10-27 19:51 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
volatility* of token prices (typo in volatility, and also I think if you don't specify that it is price volatility it might sound like volatility in volume).

2023-10-27 19:51 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +    mapping(bytes32 => INonTaggedRules.NFTTradeCounterRule)
I added a comment in my docs on top of the line of code to make it more clear that the bytes32 is the tag and the INonTaggedRules is the rule:
```
    //       tag         =>   sub-rule
    mapping(bytes32 => INonTaggedRules.NFTTradeCounterRule)
```

2023-10-27 19:51 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +There is no limit in the amount of sub-rules that a rule can have other than at least one sub-rule.
But there is a limit of at least 1 tho. Anne reworded this for me, and it looks much better now. You should copy that one Tayler.

2023-10-27 19:51 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +4. The processor will evaluate whether the last transaction time for the tokenId is within the rule period from the starting timestamp. If yes, the rule will continue to the trades per day check. If
I know this is exactly what the code does, but I think we can word this in a simpler way. For instance: "The processor will evaluate if the current transaction is in a new period. If it is, then the transfer count for current period is just 1 (current transfer). If the current transfer is NOT in a new period, then it will accumulate to current amount of trades."
Also, Im not sure this is what you are trying to say. It is not very clear to me tbh.

2023-10-27 19:51 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +```
Maybe a link to the code file?

2023-10-27 19:53 UTC, TJ-Everett commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The purpose of the transfer-counter rule is to set and maintain a daily "trades" limit for all tokenId's within a collection. This allows for the reduction in volitility of tokens within the collecti
Love this rephrasing. Combining with Shane's from above as well

2023-10-27 19:53 UTC, TJ-Everett commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- startTs(uint64): The unnix timestamp for the time that the rule starts.
Yes all our timestamps are unix timestamps 
Great catch on the formatting being slightly different!

2023-10-27 20:01 UTC, TJ-Everett commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +```
The idea is to make it explicitly clear that this is using tags on an address vs a user account 
This was also an attempt at phrasing "The collection of these tagged NFT collection sub-rules" sounding too collection-y. The tag logic (as in how we tag an address/account is the same yes)

2023-10-27 20:23 UTC, TJ-Everett commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +4. The processor will evaluate whether the last transaction time for the tokenId is within the rule period from the starting timestamp. If yes, the rule will continue to the trades per day check. If
I cannot respond to the Volatility comment for some reason so I am doing to here. Thanks for the spelling catch. 
I do not think this rule is about price volatility and it is about trading volatility not trading of totalSupply though. 
IDK how we would like to capture the nuance of that, though. 

I also attempted a rephrase here on step 4

2023-10-27 21:00 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +The transfer-counter rule enforces a daily limit on number of trades for each token within a collection. In the context of this rule, a "trade" is a transfer of a token from one address to another. T
```suggestion
The transfer-counter rule enforces a daily limit on number of trades for each token within a collection. In the context of this rule, a "trade" is a transfer of a token from one address to another. This rule has two potential purposes: to reduce volatility of token price in the collection and the prevention of malfeasance for holders who transfer a token between addresses repeatedly. When this rule is active and the tradesAllowedPerDay is 0 this rule will act as a pseudo "soulBound" token, preventing all transfers of tokens in the collection. 
```
Ended up with duplicate sentences due to review edits

2023-10-27 21:02 UTC, anne-thrackle commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +```
ok, I found this pretty confusing, but if it's clear for everyone else then I'm good.

2023-10-30 14:48 UTC, ShaneDuncan602 approved these changes
Great job. Sorry about the refactoring! I really appreciate the extra effort here.

2023-10-30 16:35 UTC, oscarsernarosero requested changes
Great job Tayler. Just a few details.

2023-10-30 16:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +### Revert Message
This should be under Rule Evaluation section.

2023-10-30 16:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- **_tradesAllowed**: developers can pass the amount of trades allowed for each tag `_nftTypes` given at creation. The protocol will validate each allowable trade limit based on the tag(s) added to t
Im not sure this lastone is an option.

2023-10-30 16:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +### Role Applicability
should be only 2 "#" -> `## Role Applicability`

2023-10-30 16:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +### Create Function
should be only 2 "#" -> ## Role Applicability

2023-10-30 16:59 UTC, oscarsernarosero approved these changes

2023-10-30 17:18 UTC, merged