TOKEN-TRANSFER-VOLUME.md
thrackle-io/forte-rules-engine-v1 pull request #176
Opened 2023-10-31 19:43 UTC by TJ-Everett

2023-11-01 02:19 UTC, oscarsernarosero requested changes
Looks really good, but some parts need more work.

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +- **Max Volume** (uint24): The maximum percent of total supply to be traded during the *period*.
in percent basis units?

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
I think you're mixing 2 concepts here. This sounds more like a *rule-by-date* type of thing where you have an active period and then nothing. I think maybe something more like "The processor will evaluate whether the transaction is the first one in current period"... or something of the kind.

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +###### *see [IRuleStorage](../../../src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol) -> checkTokenTransferVolumePasses*
see [ERC20RuleProcessorFacet]*

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
I think I know what you're trying to do here. It does have a startTimestamp, so you do have to say this, but that's a different step before you start talking about transactions in a new period or not.

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is a new period**, the processor will return the `transfer volume` value increased from current trade for the handler to store.
This is not very clear. I think you are missing steps in the "not-a-new-period" part.

2023-11-01 02:19 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +- **_maxVolumePercentage** (uint24): .
Missing this one

2023-11-01 13:47 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
Hmmm, I disagree. 
The rule has to check the rule period and last transfer time to ensure it is within the current period or not. 
If it is in a new period then this transaction is simply added to the volume tracker 
if it is not a new period then the you move to the next step of volume calculations 

I don't think we should be too different with rule evaluation descriptions that are all using the same logic 
We even have common functions for isWithinPeriod() so to me those should all be nearly identical in the evaluation step.

2023-11-01 14:48 UTC, anne-thrackle reviewed
just one source of confusion for me, when things are percentages vs. raw values. Otherwise looks pretty good.

2023-11-01 14:48 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +The purpose of the token-transfer-volume rule is to reduce high trading volatility periods by allowing developers to set a volume percentage of the token's total supply that can be traded within a pe
phrasing suggestion, take it or leave it
```suggestion
The purpose of the token-transfer-volume rule is to reduce high trading volatility periods by allowing developers to set a maximum volume (as a percentage of the token's total supply) that can be traded within a period of time. When the trading volume maximum is reached, transfers are suspended until the next period begins. 
```

2023-11-01 14:48 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +- **Period** (uint16): The amount of hours that defines a period..
```suggestion
- **Period** (uint16): The amount of hours that defines a period.
```

2023-11-01 14:48 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +        uint24 maxVolume; // this is a percentage with 2 decimals of precision(2500 = 25%)
```suggestion
        uint24 maxVolume; // this is a percentage with 2 decimals of precision (2500 = 25%)
```

2023-11-01 14:48 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is not a new period**, the processor will then evaluate the `max volume`.
I find myself confused (throughout this doc) with what are percentages and what are straight up values. The paramter "Max Volume" defined on line 22 is a percentage in basis points. The "max volume" here is the actual maximum volume in token units? 

Maybe there's a different name we could use like "max volume percent" that would make this clearer. But I know it's wordier. (though this is what it's called in the creation function)

2023-11-01 14:48 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is a new period**, the processor will return the `transfer volume` value increased from current trade for the handler to store.
```suggestion
    - **If it is a new period**, the processor will return the `transfer volume` value, set to the current trade's size for the handler to store. 
```
is my understanding correct?

2023-11-01 15:23 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is not a new period**, the processor will then evaluate the `max volume`.
I will definitely try to clarify throughout the doc where possible 
The max volume variable is the percent basis points and stays that way. 
transfer volume passed from the handler is a true value. 

The rule will take the true value of transfer volume (reset after each period with the first transaction of the new period) and calculate that against the totalSupply (or fixed supply provided to the rule) 
Then it takes that calculation and compares that it is not greater than the max volume percent in basis units

2023-11-02 16:46 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
I would also consider this a rule by date. It has a period within the rule and the volatility is determined by checking the supply at the beginning of the period. 

I think we should also mention the total supply "snapshot" for when they use the token's totalSupply and not their own. It's unique enough that I always have to go look at the code to remember it.

2023-11-02 16:53 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +## Role Applicability
I am questioning this "Role" here. For instance, line 50 doesn't pertain to a defined role. It's a registered account but not a role.

2023-11-02 16:53 UTC, ShaneDuncan602 requested changes
Minor tweaks

2023-11-02 17:07 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
Shane:
Point 1 - is that an ask for a change in the phrasing or an agreement in current phrasing?
Point 2 - is step 3 enough clarification or would you prefer it be more clear? 
I don't want to miss any needed clarity in these PRs as I have multiple at once

2023-11-02 17:31 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
yeah. It does kinda combine the rule by date and the rule per period logic. But that's not clear in your phrases. It seems like you start talking about one thing, but end talking about another one. I would split step 3 in 2: one where it checks if it is in an active stage (post startTimestamp) and then another one to check if the transaction is in a new period or not.

2023-11-02 17:53 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
I promise I am not trying to be difficult here, but I do not understand how this is different than the min-max-bal-by-date logic for this specific step 
This phrasing was pulled directly from that approved doc and used here. Since this is the same date and period validation used, why would it need to be explained differently? 

i.e. 
4. The processor will evaluate whether each sub-rule's hold period is still active (if the current time is within `hold period` from the `starting timestamp`). If it is, the processor will then evaluate if the final balance of the account would be less than the `hold amount` in the case of the transaction succeeding. If yes, then the transaction will revert.

2023-11-02 18:50 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
It is not the same because it is not the same rule. min-max-bal-by-date rule doesn't have periods (plural). It only has one period.

2023-11-02 19:55 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +## Role Applicability
I have this section broken out now in the most recent push - if we like this, I will update all the currently merged rules 
(balance-by-risk  should be merged by that time also)

2023-11-02 19:58 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +## Role Applicability
Perhaps "Evaluation Exceptions" should live beneath the "Rule Evaluation" section now.

2023-11-02 20:01 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule is active base on `starting timestamp`.
This should be based instead of base

2023-11-02 20:12 UTC, oscarsernarosero requested changes
Much better. I still think it needs some final tweaks.

2023-11-02 20:12 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +5. The processor will evaluate whether the current time is within the `period`.
I would say "The processor will evaluate whether the current time is within a new `period` (first transaction in current period)"

2023-11-02 20:12 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is a new period**, the processor will return the `transfer volume` value from the current transaction for the handler to store.
if it is in a new period, it won't evaluate as if it is not?

2023-11-02 20:12 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - **If it is not a new period**, the processor will then evaluate the `transfer volume` (tokens transferred) against the rule's `max volume` (percent in basis units of total supply).
Maybe what throws me off is that you mention here the evaluation of the rule, but I think this happens after the volume has been defined which is what this fifth step is about (from what I am understanding).

2023-11-02 20:12 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +6. The processor will then calculate the final volume percentage, in basis units, of the total supply by adding the `transfer volume` (tokens transferred) for the period and the `amount` to be transf
Like you can say here "[...] by adding the `transfer volume` (tokens transferred) for the period defined in the step 5 [...]"

2023-11-02 20:14 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule's period is still active (if the current time is within `period` from the `starting timestamp`).
> Shane: Point 1 - is that an ask for a change in the phrasing or an agreement in current phrasing? Point 2 - is step 3 enough clarification or would you prefer it be more clear? I don't want to miss any needed clarity in these PRs as I have multiple at once

1. I think the phrasing needs to be changed a little because the period is on the rule and not the subrule. We might also need to clarify exactly what the term, transfer volume, means. It might help to put that in the purpose section as well. 
2. I think step 3 should mention that, when the token's total supply is used, the value it uses is the one from the beginning of the period.

2023-11-03 04:56 UTC, oscarsernarosero approved these changes
I love it Tayler. I like how you reorganized the Role Applicability section and reworded the rule evaluation section. I only have one small suggestion, but Im approving rn.

2023-11-03 04:56 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule is active based on the `starting timestamp`.
I would just add here at the end: "If it is not active, the rule evaluation will skip the next steps, and will simply return the `transfer volume` value.

2023-11-03 04:56 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +    - If no, the processor will return the `_volume` value for the current `period` to the handler.
This looks amazing now. Great job.

2023-11-03 13:28 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor will evaluate whether the rule is active based on the `starting timestamp`.
Good call! Added that in there.

2023-11-03 15:57 UTC, ShaneDuncan602 approved these changes
Looks great

2023-11-03 15:59 UTC, merged