added MAX-BALANCE-BY-ACCESS-LEVEL doc. Also fixed a couple other files.
thrackle-io/forte-rules-engine-v1 pull request #177
Opened 2023-11-01 04:32 UTC by oscarsernarosero

2023-11-01 13:42 UTC, jjbailey-io requested changes

2023-11-01 13:42 UTC, jjbailey-io commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +The purpose of this rule is to provide control over the balance limits for accounts at the application level. The limits will depend on the *access level* of the accounts. This control is mostly thou
We have to be careful about using verbiage that says "we're making a compliance solution for the government to satisfy regulatory requirements." KYC shouldn't be used at all, that's why we renamed it to "Access level". I recommend using the something more along the lines of:

> The purpose of this rule is to provide balance limits for accounts at the application level based on an application defined segment of users. The segments are defined as the access levels of the accounts. This rule may be used to provided gated accumulation of assets to ensure accounts cannot accumulate more assets without performing other actions defined by the application. For example, the application may decide users may not accumulate any assets without performing specific onboarding activities. The application developer may set a maximum balance of $0 for the default access level and $1000 for the next access level. As accounts are introduced to the ecosystem, they may not receive any assets until the application changes their access level to a higher value.

2023-11-01 13:42 UTC, jjbailey-io commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- **Pricing contracts**: pricing contracts for ERC20s and ERC721s need to be setup in the token handlers in order for this rule to work.
It would be nice to link the documentation/information on how to set pricing here.

2023-11-01 14:10 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +This rule works at the application level which means that all tokens in the app will have no choise but to comply with this rule when active.
choice*

2023-11-01 14:12 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +2. Then, the rule processor will retrieve the maximum balance allowed for the rule with the ruleId passed, and for the access level of the account. If the balance will exceed the maximum allowed by t
there are two spaces after successful

2023-11-01 14:17 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +The create function will return the protocol ID of the rule.
This line should be above ###Parameters:

2023-11-01 14:29 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- **Pricing contracts**: pricing contracts for ERC20s and ERC721s need to be setup in the token handlers in order for this rule to work.
I believe (and by that I mean I looked through the docs and couldn't find) we only have the deployment directions for the pricer - we do not currently have documentation outlining the pricer contracts. 
I imagine this will happen a good bit as we build out the docs, when we need to point to something that doesn't exist yet. 

Where is the best place to consolidate these kinds of issues? Should we create a shared doc somewhere and try to collect these as they pop up so when we are done with documentation we can review and make sure these little issues are corrected? @jjbailey-io

2023-11-01 14:29 UTC, TJ-Everett reviewed
Looks good overall Oscar, just a few changes and typos for me. I agree with JB's purpose description.

2023-11-01 14:55 UTC, jjbailey-io commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- **Pricing contracts**: pricing contracts for ERC20s and ERC721s need to be setup in the token handlers in order for this rule to work.
Good point. @TJ-Everett  Can you generate a ticket for it? We can ignore this for now then.

2023-11-01 15:19 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- **Pricing contracts**: pricing contracts for ERC20s and ERC721s need to be setup in the token handlers in order for this rule to work.
SE 401 created 
Created a collection doc for doc issues [here](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/213778530/Tron+Documentation+TODO+List)

2023-11-01 15:21 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- ERC721
Since this is application level, should we even have this section? It might be better to remove it for application level rules or to have a blanket statement about applying to all protocol supported assets within the application.

2023-11-01 15:27 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +
We need to include that it does not apply to burns. That is specifically code into the ProtocolApplicationHandler

2023-11-01 15:28 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- In the [App Manager Handler](../../../src/application/ProtocolApplicationHandler.sol):
I don't think "App Manager Handler" is the correct term. I think it is just ApplicationHandler

2023-11-01 15:30 UTC, ShaneDuncan602 requested changes
Just a couple of things.

2023-11-01 17:17 UTC, oscarsernarosero commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +The purpose of this rule is to provide control over the balance limits for accounts at the application level. The limits will depend on the *access level* of the accounts. This control is mostly thou
This sounds great Johnathan. Thank you.

2023-11-01 17:19 UTC, oscarsernarosero commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +2. Then, the rule processor will retrieve the maximum balance allowed for the rule with the ruleId passed, and for the access level of the account. If the balance will exceed the maximum allowed by t
I think Markdown still displays one, but I'll delete the extra one anyways. Great catch man.

2023-11-01 17:21 UTC, oscarsernarosero commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- ERC721
That's a @jjbailey-io question

2023-11-01 18:00 UTC, anne-thrackle reviewed
Looks good. Just a couple minor comments.

2023-11-01 18:00 UTC, anne-thrackle commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +This rule works at the application level which means that all tokens in the app will have no choice but to comply with this rule when active.
```suggestion
This rule works at the application level which means that all tokens in the app will comply with this rule when the rule is active.
```

2023-11-01 18:00 UTC, anne-thrackle commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- **maxBalance** (mapping(uint8 =>uint48)): the maximum USD worth of application assets that accounts can have per acces level.
```suggestion
- **maxBalance** (mapping(uint8 =>uint48)): the maximum USD worth of application assets that accounts can have per access level.
```

2023-11-01 18:00 UTC, anne-thrackle commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +1. The application manager will send to the protocol's rule processor the sum of the balances of every application asset of the account, the access level of the account, the ruleId, and the dollar am
```suggestion
1. The application manager will send to the protocol's rule processor the dollar value sum of all application assets the account holds, the access level of the account, the ruleId, and the dollar amount to be transferred in the transaction.
```

2023-11-01 18:00 UTC, anne-thrackle commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +2. Then, the rule processor will retrieve the maximum balance allowed for the rule with the ruleId passed, and for the access level of the account. If the balance will exceed the maximum allowed by t
What if I acquired a bunch of in-game gold when it was worth $0.10. Now it's worth $10 and I've gone above my limit based on my access level (through no action of my own, just the value going up independently of me). 
Now I'm trying to sell some gold. But the result after selling it will still be above my limit. Will the transaction succeed?

2023-11-01 21:09 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- ERC721
This is what I have for the risk rule I am working but applies here if yall like it
"This rule works at the application level. It must be activated and configured in the application handler. Each token in the application ecosystem will be valued and contribute to the rule balance calculation. This rule, when active, will apply to each token within the application."

I don't think we should get rid of the section for standardization reasons.

2023-11-01 21:12 UTC, TJ-Everett commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +2. Then, the rule processor will retrieve the maximum balance allowed for the rule with the ruleId passed, and for the access level of the account. If the balance will exceed the maximum allowed by t
The transaction would revert, Anne. This rule captures the current price (or at least the last price provided to the pricing contract, so we would assume the contract knows the price has increased for this example). 
You would need to either increase your access level or wait for the price to go back down to transact. @anne-thrackle

2023-11-01 21:13 UTC, TJ-Everett approved these changes
Approved for me Oscar, this looks great. 

I know there is an outstanding question for the scope section, but I left my vote in the in line comments.

2023-11-01 21:29 UTC, oscarsernarosero commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +2. Then, the rule processor will retrieve the maximum balance allowed for the rule with the ruleId passed, and for the access level of the account. If the balance will exceed the maximum allowed by t
That's correct.

2023-11-02 13:44 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- ERC721
Please capture this decision in the ticket @oscarsernarosero

2023-11-02 13:47 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-11-02 18:22 UTC, merged