Se 362 create a markdown file for the implementation of the token percentage sell rule
thrackle-io/forte-rules-engine-v1 pull request #180
Opened 2023-11-03 20:47 UTC by TJ-Everett

2023-11-06 19:04 UTC, oscarsernarosero approved these changes
Very minor typos. Great job in general tho.

2023-11-06 19:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit of the sale of tokens during a period. This rule sets a percentage of the token's total supply that is able to be sold per period. For this rule, a sel
"via AMM an swap"?

2023-11-06 19:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +    - If no, the processor will return the `tokenPercentage` value for the current `period` to the handler.
Great job here

2023-11-06 19:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **_tokenPercentage** (uint16): maximum allowable basis unit percentage of trading volume per period.
"maximum allowable percentage (in basis unit) of trading volume per period."

2023-11-06 19:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **_startTimestamp** (uint64): starting timestamp of the rule. This timestamp will determine the time that a day starts and ends for the rule processing. For example, *the amount of trades will rese
Unix timestamp

2023-11-06 19:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **_totalSupply**: For volatility calculations, when this is zero, the token's totalSupply is used. Otherwise, this value is used as the total supply.
"For sell volume over supply calculations, when [...]"

2023-11-07 14:19 UTC, anne-thrackle requested changes
Good overall, I think the Evaluation section needs a bit of work.

2023-11-07 14:19 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit of the sale of tokens during a period. This rule sets a percentage of the token's total supply that is able to be sold per period. For this rule, a sel
```suggestion
The token-percentage-sell rule enforces a limit on the sale of tokens during a certain time period. This rule sets the limit as a percentage of the token's total supply. For this rule, a "sell" is a swap of an application token for a token that is not part of the application (e.g. the chain native token, or a token from another application). 
```
Not sure that "non application token" was clear so I suggested a rephrase, but maybe it's ok. 

I removed the last sentence, I think it caused a bit of confusion for me (maybe the "leaving the ecosystem" which I don't think is related to this rule) - but I'm not against adding something like "for example, an account using an AMM to swap their application token for chain native token".

2023-11-07 14:19 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **Token Percentage** (uint16): The maximum percent in basis units of total supply to be sold during the *period*.
```suggestion
- **Token Percentage** (uint16): The maximum percent in basis units of total supply able to be sold during the *period*.
```

2023-11-07 14:19 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **Sell  Period** (uint16): The amount of hours that defines a period.
```suggestion
- **Sell  Period** (uint16): The length of time for which the rule will apply, in hours.
```

2023-11-07 14:19 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +## Rule Evaluation
I find this section confusing again. Trying to figure out why, I think it's: 
- variables being introduced without explaining what they are, and it not being obvious from the name. Especially `_token_amount_0` is a very nondescript name. 
- some variables being camel case, some snake case, some just words with spaces. Makes it harder to parse and digest. 
- statements like "the processor will use the `_token_amount_0` value from the current transaction as the `percentOfTotalSupply` value for the sell percent of total supply calculation." What does it mean to use one value as another, for two variables that I don't know what they are? 

I wonder if these evaluation sections would be better served by actual pseudocode. I think at least more accurate and descriptive/more consistent variable names would help.

2023-11-07 14:45 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +## Rule Evaluation
- Added clarity for new variable intro'ed via the handler params 
- changed all variables to be plain english words with spaces 
- The rule will either take the combined total of the token amount 0 and the percent of total supply from the handler if within an existing period, or take just the token amount 0 for the current transaction if in a new period to find the transaction percentage of total supply value. 

I do believe that some of this will become much more clear as we expand the docs to the handlers and assets and not just the rules. Creating a clearer picture, however yes we need a better handle on standardized variable names and to do a once through the protocol do catch instances of naming conventions not making sense.

2023-11-07 15:04 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +
I know this is the intention of the rule, but they could also create an AMM for two application tokens and still use it.

2023-11-07 15:05 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- ERC20
Shouldn't this be AMM? I know it's not a token but this rule is only supported within the AMM, right?

2023-11-07 15:06 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **Token Percentage** (uint16): The maximum percent in basis units of total supply able to be sold during the *period*.
it might be helpful to give an example of the numbers since it is shifted to account for lack of decimals.

2023-11-07 15:07 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **Total Supply** (uint256): if not zero, this value will always be used as the token's total supply for rule evaluation. This can be used when the amount of circulating supply is much smaller than
Shouldn't we also include the validations for these? For instance, that period cannot be zero

2023-11-07 15:12 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +## Rule Evaluation
I agree. I think internally labeling the tokens and token0 and token1 is fine in the code, but it's not how most people view things. It's our nerdy engineering jargon. For the sake of documentation, token_A and token_B or some other more natural label might be better.

2023-11-07 15:13 UTC, ShaneDuncan602 requested changes
Just minor things. I'm not sure where it would fit best, but I think it needs to be clear that this rule is only applicable to AMM's.

2023-11-07 15:25 UTC, anne-thrackle approved these changes
discussed this last set of suggestions with Tyler live. We may also want to have a broader conversation with the team about the approach here, and variable names.

2023-11-07 15:25 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +2. The processor receives the current `total sold within period`, `token amount 0` (total amount of token 0 being transferred), `previous sell time`, and token's total supply from the handler.
```suggestion
2. The processor receives the current `total sold within period`, `token amount 0` (total amount of token 0 being transferred in the current transaction), `previous sell time`, and token's total supply from the handler.
```

2023-11-07 15:25 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +    - **If it is a new period**, the processor will use the `token amount 0` value from the current transaction as the `percent of total supply` value for the sell percent of total supply calculation
```suggestion
    - **If it is a new period**, the processor sets the `percent of total supply` to the value of `token amount 0`. 
```

2023-11-07 15:25 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +    - **If it is not a new period**, the processor will then accumulate the `total sold within period` (tokens transferred) and the `token amount 0` of tokens to be transferred as the `percent of tot
```suggestion
    - **If it is not a new period**, the processor sets `percent of total supply` to the sum of `total sold within period` and `token amount 0`.   
```

2023-11-07 15:25 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +5. The processor calculates the final sell percentage, in basis units, from `percent of total supply` and the total supply set in step 3.
```suggestion
5. The processor calculates the final sell percentage, in basis units, using the `percent of total supply` calculated in step 4 and the total supply set in step 3. 
```

2023-11-07 15:25 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +    - If no, the processor will return the `tokenPercentage` value for the current `period` to the handler.
```suggestion
    - If no, the processor returns the `tokenPercentage` value for the current `period` to the handler.
```

2023-11-07 15:44 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- ERC20
I will expand the scope section a bit to be more explicitly clear that this is an AMM applied rule. 
I think the token section should remain as is and then add in 721 and 1155 as we build those AMM's

2023-11-07 15:45 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **Total Supply** (uint256): if not zero, this value will always be used as the token's total supply for rule evaluation. This can be used when the amount of circulating supply is much smaller than
We have the parameter validation steps on line 117

2023-11-08 00:35 UTC, oscarsernarosero reviewed
Looking into Shane's and Anne's comments which I think are valid, I made some more suggestions.

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- ERC20
This is a great point. Maybe renaming this to "Protocol-Element Supported" or something of the kind

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +This rule works at the AMM level. It must be activated and configured for each desired AMM in the corresponding asset handler. This rule will not be applied at the token level and will only be checke
"AMM handler"? I don't think an AMM can be considered an asset.

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +2. The processor receives the current `total sold within period`, `token amount 0` (total amount of token 0 being transferred in the current transaction), `previous sell time`, and token's total supp
This looks good, but looking into Shane's and Anne's comments, I would just avoid putting variable descriptions in "code blocks". So for instance just " total sold within period " instead of " `total sold within period` ". I think that would make much clearer the statements. Also, echoing Shane's point about us being nerds (lol), I would rename token 0 to token A, and instead of "token amount A" (assuming you are accepting my naming suggestion) maybe say "token A amount" since the former could be interpreted as "amount A of tokens" (where A is a number) instead of the "the amount of tokens for token A"

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +3. The processor evaluates whether the rule has a set total supply or uses the token's total supply provided by the handler set at the beginning of every new `period`.
for instance `period` here is well used because it has been already defined in the data structure section. So I think this is good.

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +6. The processor evaluates if the final sell percentage of total supply would be greater than the `token percentage` in the case of the transaction succeeding.
same suggestions as step 2

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +6. The processor evaluates if the final sell percentage of total supply would be greater than the `token percentage` in the case of the transaction succeeding.
Also, in line 61, you could use a more intuitive and less technical name for the token like "amount of tokens being sold in this transaction", or something like that.

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- In the case of ERC20s, this rule doesn't apply when a **registered treasury** address is in the *to* side of the transaction.
This is something that is in the code so we should keep it, but Im wondering now why an AMM would send tokens to a treasury address.

2023-11-08 00:35 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- **_startTimestamp** (uint64): starting unix timestamp of the rule. This timestamp will determine the time that a day starts and ends for the rule processing. For example, *the amount of trades will
In this case, you should mention that this example is only valid if `_sellPeriod` is 24 hours (1 day). Otherwise that example doesn't really apply because you start getting an accumulated shifting of hours per period (unless `_sellPeriod` is a factor of 24).

2023-11-08 14:20 UTC, anne-thrackle commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +2. The processor receives the current `total sold within period`, `token amount 0` (total amount of token 0 being transferred in the current transaction), `previous sell time`, and token's total supp
+1 to "token A"

2023-11-08 15:18 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- In the case of ERC20s, this rule doesn't apply when a **registered treasury** address is in the *to* side of the transaction.
I believe this is for Fees being deposited to a Treasury account and not wanting additional rules on that transfer.

2023-11-08 15:19 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +This rule works at the AMM level. It must be activated and configured for each desired AMM in the corresponding asset handler. This rule will not be applied at the token level and will only be checke
In previous conversations and docs we have called the handlers asset handlers and that continued to include AMM's but I have clarified here all the same that this is applied in the AMM handler.

2023-11-08 15:20 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +This rule works at the AMM level. It must be activated and configured for each desired AMM in the corresponding asset handler. This rule will not be applied at the token level and will only be checke
To the Tokens supported section, I think this is valuable to keep for both consistency in the docs as well as when we do add support for additional tokens.

2023-11-08 17:04 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- In the case of ERC20s, this rule doesn't apply when a **registered treasury** address is in the *to* side of the transaction.
awesome! Thank you

2023-11-09 16:01 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +- ERC20
I don't think we want to define the sell as between chain native and application tokens and then tell them they can also apply to any AMM swap. It would probably be clearer to just say that it only applies to AMM swaps

2023-11-09 16:06 UTC, ShaneDuncan602 requested changes
A little change to the purpose statement

2023-11-09 17:51 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit on the sale of tokens during a certain time period. This rule sets the limit as a percentage of the token's total supply. The rule will apply to the to
This applies to both sides of the swap. It also checks it on token 1 to token 0 swaps.

2023-11-09 17:57 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit on the sale of tokens during a certain time period. This rule sets the limit as a percentage of the token's total supply. The rule will apply to the to
The swap for 1 to 0 passes in the purchase action type so it would not check the sell only the purchase, no?

2023-11-09 18:14 UTC, TJ-Everett commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit on the sale of tokens during a certain time period. This rule sets the limit as a percentage of the token's total supply. The rule will apply to the to
That is why I was defining "sell" in the purpose before

2023-11-09 19:03 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-PERCENTAGE-SELL.md
> +The token-percentage-sell rule enforces a limit on the sale of tokens during a certain time period. This rule sets the limit as a percentage of the token's total supply. The rule will apply to the to
Ok, now I remember. Sheesh, the application of AMM rules is very confusing. Only one side of the swap is a sell but we don't enforce anything when the tokens are set in the AMM. If they want this rule on both sides of the swap, they have to create its purchase counterpart and apply it even if the rule intention is the same. We definitely need to revisit this in the future. I'm going to add this comment to Jira so we have it.

2023-11-09 19:03 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-11-09 19:08 UTC, merged