Se 401 create markdown file for pricing contracts
thrackle-io/forte-rules-engine-v1 pull request #192
Opened 2023-11-20 17:36 UTC by oscarsernarosero

GitHub view [here](https://github.com/thrackle-io/tron/tree/SE-401-Create-Markdown-file-for-Pricing-Contracts/docs/userGuides/pricing)

2023-11-20 18:44 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/ERC20-PRICING.md
> +function setSingleTokenPrice(address tokenContract, uint256 price) external;
Our example contract has onlyOwner on the implementation. I know this is the interface but we should probably mention permissions to this and the underlying example contract.

2023-11-20 18:48 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/ERC721-PRICING.md
> +function setSingleNFTPrice(address nftContract, uint256 id, uint256 price) external;
Same issue as above. We could add something like, "The provided example pricing contract, ProtocolERC721Pricing.sol, utilizes the onlyOwner modifier to ensure only the only may modify token price."

2023-11-20 18:50 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +The purpose of the pricing contracts is to serve as the token-price data sources for ecosystem applications. The token pricers can be found in 2 different categories:
"The purpose of the pricing contracts is to serve as the token-price" should be "The purpose of the pricing contracts is to serve as token-price"

2023-11-20 18:52 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +Some protocol rules require these contracts to be set in the tokens for them to be able to work.
The first question that comes to mind is: which ones? I think we should add a list of the ones that require pricing.

2023-11-20 18:53 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +- **Price is in weis of US Dollars**: 1 dollar is represented by 1 * 10^18, and 1 cent is represented 1 * 10^16 in these contracts. This is done to have precision over the price, and to account for t
We probably shouldn't mention a token like Shiba Inu. I think "account for the possibility of tokens with extremely low valuations" might work better.

2023-11-20 18:57 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +    - **For Fungible Tokens**: just like regular market data outlets, the price will be given for a whole token (no decimals), the same way the price is given for ETH or BTC, for example, which is no
It think this would be clearer if we didn't mention the atto values. For example: "just like regular market data outlets, the price will be given for a whole token without decimals, e.g. 1 ETH.

2023-11-20 19:00 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +Let's say we have the NFT collection called *ThrackleNFT*. Let's imagine that the *ThrackleNFT* with Id 222 is worth exactly $500.00 US Dollars. In this case, the price for the token will be 500 * 10
We have been getting away from mentioning the company name in examples like this. We should use public domain entities like FrankensteinNFT or something else at least 75 years old.

2023-11-20 19:01 UTC, ShaneDuncan602 requested changes
Few suggestions.

2023-11-20 19:17 UTC, oscarsernarosero commented on docs/userGuides/pricing/ERC20-PRICING.md
> +function setSingleTokenPrice(address tokenContract, uint256 price) external;
you're right. I'll add the onlyOwner since this is talking about our implementation and not the interface.

2023-11-20 19:19 UTC, oscarsernarosero commented on docs/userGuides/pricing/PRICING-CONTRACTS.md
> +Some protocol rules require these contracts to be set in the tokens for them to be able to work.
ok

2023-11-20 20:01 UTC, ShaneDuncan602 approved these changes
Awesome. Great job.

2023-11-21 14:48 UTC, TJ-Everett commented on docs/userGuides/pricing/ERC20-PRICING.md
> +- **price (uint256)**: the price in weis of dollars for a whole token (see [example](./README.md)).
I think we settled on wei instead of weis in previous docs.

2023-11-21 14:49 UTC, TJ-Everett commented on docs/userGuides/pricing/ERC20-PRICING.md
> +- **price (uint256)**: the price in weis of dollars for a whole token (see [example](./README.md)).
Same here

2023-11-21 14:50 UTC, TJ-Everett commented on docs/userGuides/pricing/ERC721-PRICING.md
> +- **price (uint256)**: the price in weis of dollars for a whole token (see [example](./README.md)).
Wei

2023-11-21 14:51 UTC, TJ-Everett approved these changes
Approve and looks great, I found a couple spots where you used weis vs using wei without the s.

2023-11-21 18:53 UTC, merged