Create Oracle rule .md files
thrackle-io/forte-rules-engine-v1 pull request #200
Opened 2023-12-01 22:24 UTC by TJ-Everett

Update previous rule file url links with new diamond arch

2023-12-02 00:49 UTC, oscarsernarosero approved these changes
Looks great Tayler.

2023-12-05 19:05 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-BALANCE-BY-RISK.md
> +###### *see [IRuleStorage](../../../src/economic/ruleProcessor/IRuleStorage.sol)*
IRuleStorage should be RuleProcessor

2023-12-05 19:06 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-BALANCE-BY-RISK.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol)):
Storage Diamond should be Rule Diamond, right?

2023-12-05 19:07 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ADMIN-WITHDRAWAL-RULE.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:08 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MAX-BALANCE-BY-ACCESS-LEVEL.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ApplicationAccessLevelProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:08 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +###### *see [IRuleStorage](../../../src/economic/ruleProcessor/IRuleStorage.sol)*
Storage Diamond should be Rule Diamond

2023-12-05 19:08 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +###### *see [IRuleStorage](../../../src/economic/ruleProcessor/IRuleStorage.sol)*
Storage Diamond should be Rule Diamond

2023-12-05 19:08 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:09 UTC, ShaneDuncan602 commented on docs/userGuides/rules/SUPPLY-VOLATILITY.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:09 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:09 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSACTION-SIZE-BY-RISK-SORE.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ApplicationAccessLevelProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:10 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TRANSFER-COUNTER.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ERC721TaggedRuleProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:10 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TX-SIZE-PER-PERIOD-BY-RISK-SCORE.md
> +- In Protocol [Storage Diamond](../../../src/economic/ruleProcessor/ApplicationAccessLevelProcessorFacet.sol):
Storage Diamond should be Rule Diamond

2023-12-05 19:15 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ALLOW-ORACLE.md
> +- This rule has no dependencies.
This rule would be dependent upon the oracle itself. The oracle must contain a function with the signature:

function isAllowed(address _address) external view returns (bool)

2023-12-05 19:19 UTC, ShaneDuncan602 commented on docs/userGuides/rules/SANCTION-ORACLE.md
> +The purpose of the sanction-oracle rule is to check if the caller of the transaction is allowed to or restricted from performing the transaction. Addresses are added to the sanction oracle by the own
This is a little misleading. When it says, "check if the caller of a transaction is allowed" that makes it seem like it performs both allow list and deny list. I think we should remove this.

2023-12-05 19:20 UTC, ShaneDuncan602 commented on docs/userGuides/rules/SANCTION-ORACLE.md
> +- [ ] AMM
Applies to AMM's as well.

2023-12-05 19:20 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ALLOW-ORACLE.md
> +- [ ] AMM
Applies to AMM's as well

2023-12-05 19:21 UTC, ShaneDuncan602 commented on docs/userGuides/rules/SANCTION-ORACLE.md
> +- This rule has no dependencies.
This rule would be dependent upon the oracle itself. The oracle must contain a function with the signature:

function isRestricted(address _address) external view returns (bool)

2023-12-05 19:22 UTC, ShaneDuncan602 requested changes
Some diamond name stuff and applicability things.

2023-12-06 14:43 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ALLOW-DENY-ORACLE.md
> +The purpose of the allow-deny-oracle rule is to check if the receiver address in the transaction is an allowed address or to check if the sender is restricted from performing the transaction. Address
This rule doesn't check the sender. It only checks the receiver. The AMM has a check for _from, but this is misleading because it is the user that is trading so they are still the receiver.

2023-12-06 14:46 UTC, ShaneDuncan602 commented on docs/userGuides/rules/RULE-GUIDE.md
> +| [Oracle](./ALLOW-DENY-ORACLE.md) | The purpose of the allow-deny-oracle rule is to check if the receiver address in the transaction is an allowed address or to check if the sender is restricted fro
Same issue as above. Doesn't check the sender.

2023-12-06 14:47 UTC, ShaneDuncan602 requested changes
Almost. One thing in the descriptions.

2023-12-07 15:54 UTC, ShaneDuncan602 approved these changes
Looks great

2023-12-07 15:58 UTC, merged