Se 368 create a markdown file for the implementation of the minimum maximum account balances rule
thrackle-io/forte-rules-engine-v1 pull request #204
Opened 2023-12-05 20:29 UTC by TJ-Everett

2023-12-05 21:40 UTC, oscarsernarosero approved these changes
This looks really good Tayler. I just have a couple small suggestions, but Im approving rn.

2023-12-05 21:40 UTC, oscarsernarosero commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +6. Step 4 and 5 are repeated for each of the account's tags.
I believe Anne and Johnathan had agreed on these sentences to be in present tense.

2023-12-05 21:40 UTC, oscarsernarosero commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +        ) external ruleAdministratorOnly(_appManagerAddr) returns (uint32);
just this indentation should be -1 than the other ones.

2023-12-06 15:15 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-BALANCE-BY-RISK.md
> +5. The processor checks if the transaction value + current balance total is less than the risk score `max balance`. If total is greater than `max balance`, the rule will revert.
The rule will revert should be "the rule reverts"

2023-12-06 15:22 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +This rule works at both the token level and AMM level. It must be activated and configured for each desired token in the corresponding token handler or each desired AMM in the AMM Handler.
We should change the wording on this a little because it makes it sound like the AMM doesn't require us to set the rule for each token.  "each desired AMM in the AMM Handler" should be "each desired AMM supported token within the AMM Handler."

2023-12-06 15:33 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +4. The processor evaluates if the final balance of the sender account would be less than the`minimum` in the case of the transaction succeeding. If yes, then the transaction will revert.
I don't think we need this statement, "in the case of the transaction succeeding" and it should be present tense, "If yes, the transaction reverts"

2023-12-06 15:33 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +5. The processor evaluates if the final balance of the receiver account would be greater than the `maximum` in the case of the transaction succeeding. If yes, then the transaction will revert.
I don't think we need this statement, "in the case of the transaction succeeding" and it should be present tense, "If yes, the transaction reverts"

2023-12-06 15:35 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +- This rule doesn't apply when an **app administrator** address is in either the *from* or the *to* side of the transaction. This doesn't necessarily mean that if an app administrator is the one exec
It looks like it does apply to app admins for AMM's.

2023-12-06 15:46 UTC, TJ-Everett commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +- This rule doesn't apply when an **app administrator** address is in either the *from* or the *to* side of the transaction. This doesn't necessarily mean that if an app administrator is the one exec
Wow, I see that. I don't know if that is intentional, though?

2023-12-06 15:47 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +function addBalanceLimitRules(
I have always hated that this function name doesn't match the rule name. I talked to JB and he said go ahead and change it in this ticket. Let's do a global find/replace to change it addMinMaxBalanceRule. I will let Rob know that it will affect DOOM as well.

2023-12-06 15:52 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +        function getBalanceLimitRule(
We'll need to refactor this one as well. It should be: getMinMaxBalanceRule

2023-12-06 15:54 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MINIMUM-ACCOUNT-BALANCE-BY-DATE.md
> +4. The processor evaluates whether each sub-rule's hold period is still active (if the current time is within `hold period` from the `starting timestamp`). If it is, the processor will then evaluate
"will then evaluate" should be, "then evaluates".
"then the transaction will revert." should be "then the transaction reverts"

2023-12-06 15:54 UTC, ShaneDuncan602 commented on docs/userGuides/rules/PAUSE-RULE.md
> +2. The processor loops through all these pause rules, and evaluates if current timestamp is greater or equal to `pauseStart` and less than `pauseStop`. If the condition is true for at least one rule,
"then the transaction will revert" should be "then the transaction reverts"

2023-12-06 15:56 UTC, ShaneDuncan602 commented on docs/userGuides/rules/SUPPLY-VOLATILITY.md
>  4. After current period's net supply change and totalSupply have been defined, the rule processor will calculate the change in supply. If the change is greater than the rule's maximum, it will revert
"the rule processor will calculate the change in supply. If the change is greater than the rule's maximum, it will revert." should be "the rule processor calculates the change in supply. If the change is greater than the rule's maximum, it reverts."

2023-12-06 15:57 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +4. The processor evaluates whether the rule is active based on the `starting timestamp`. If it is not active, the rule evaluation will skip the next steps, and will simply return the `transfer volume
"the rule evaluation will skip the next steps, and will simply return the `transfer volume` value." should be "the rule evaluation skips the next steps, and simply returns the `transfer volume` value."

2023-12-06 15:58 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
> +7. The processor evaluates if the final volume percentage of total supply would be greater than the `max volume` in the case of the transaction succeeding.
Don't think we need, "in the case of the transaction succeeding" in this.

2023-12-06 15:58 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
>      - If yes, then the transaction will revert.
"then the transaction will revert." should be, "then the transaction reverts."

2023-12-06 15:58 UTC, ShaneDuncan602 commented on docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md
>      - If no, the processor will return the `_volume` value for the current `period` to the handler.
"the processor will return the `_volume` value" should be, "the processor returns the `_volume` value"

2023-12-06 16:00 UTC, ShaneDuncan602 requested changes
Some minor things. Also, my OCD required that we fix the rule creation function name and the getter function name. Sorry for the scope change.

2023-12-07 16:52 UTC, ShaneDuncan602 commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +- This rule doesn't apply when an **app administrator** address is in either the *from* or the *to* side of the transaction. This doesn't necessarily mean that if an app administrator is the one exec
If it's not supposed to allow it, as product is going through these docs, we can change as necessary.

2023-12-07 16:54 UTC, ShaneDuncan602 approved these changes
Looks great. Sorry for the scope creep. This change was long overdue.

2023-12-07 18:40 UTC, oscarsernarosero reviewed
I have only 2 very small changes requests

2023-12-07 18:40 UTC, oscarsernarosero commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +1. The receiver account and the sender account being evaluated pass all the tags it has registered to their addresses in the application manager to the protocol.
"[...]  being evaluated **pass** all the tags..." suggests plural (receiver and sender), but "it has" is singular. I would say, instead of "it has" it should be "they have".

2023-12-07 18:40 UTC, oscarsernarosero commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +- Not one `minimum` or `maximum` can have a value of 0.
It also checks that the minimum is not greater than maximum. I am realizing we should probably check min is not greater or equal to max.

2023-12-07 18:40 UTC, oscarsernarosero commented on docs/userGuides/rules/MIN-MAX-ACCOUNT-BALANCE.md
> +- Not one `minimum` or `maximum` can have a value of 0.
for the scope of the ticket tho. I would say, just say it is not greater than.

2023-12-07 19:47 UTC, merged