SE-365-Create-a-Markdown-file-for-the-implementation-of-the-Account-Purchase-Controller-Rule
thrackle-io/forte-rules-engine-v1 pull request #205
Opened 2023-12-05 21:01 UTC by ShaneDuncan602

2023-12-05 21:33 UTC, oscarsernarosero requested changes
I noticed a couple stuff that might also affect the SellPurchase-rule doc. Looks good in general.

2023-12-05 21:33 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +- **Starting Timestamps** (uint64): The timestamp of the date when the *period* starts counting.
Unix timestamp*?

2023-12-05 21:33 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +7. Return the cumulative purchases amount.
Something I just remembered is that Anne did mentioned that this should always be in present tense. I forgot about the other doc. I think that's a good rule of thumb for this section in the docs.

2023-12-05 21:33 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +4. The processor will evaluate whether each sub-rule's period is active (if the current time is within `period` from the `starting timestamp`). If it is not within the period, it will set the cumulat
Im realizing that this statement has the same issue Tayler was having with another rule where there was basically a combination of 2 different checks. One is with the startTime and the other one is with the period. I would suggest to have [Tayler's work as reference](https://github.com/thrackle-io/tron/blob/internal/docs/userGuides/rules/TOKEN-TRANSFER-VOLUME.md#rule-evaluation)

2023-12-05 21:33 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +- This rule doesn't apply when an **app administrator** address is in either the *from* or the *to* side of the transaction.
Looking at the code, it seems that this rule doesn't apply for treasury, but it does apply for app administrators.

2023-12-05 21:38 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +4. The processor will evaluate whether each sub-rule's period is active (if the current time is within `period` from the `starting timestamp`). If it is not within the period, it will set the cumulat
+1 to this, it was a frustrating logic problem for me to unwrap so hopefully we don't have to go through that again

2023-12-05 21:41 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +- **Tags**: This rules relies on accounts having [tags](../GLOSSARY.md) registered in their [AppManager](../GLOSSARY.md), and they should match at least one of the tags in the rule for it to have any
rule* 
I caught this in my doc and tried to correct all the ones in external that use tags.

2023-12-05 21:42 UTC, TJ-Everett requested changes
Echoing Oscar for the eval steps and then a typo in the Dependencies section that seems to have copy pasta'ed its way around

2023-12-05 21:56 UTC, TJ-Everett commented
I also realized that we have not updated the RULES-GUIDE.md with the new rules. I am adding to min/max and Oracle branches as well

2023-12-06 15:53 UTC, TJ-Everett commented on docs/userGuides/rules/RULE-GUIDE.md
>  | Minimum/Maximum Account Balances | TODO |
I can't leave an inline comment on the lines but we need to add the Purchase and Sell links and purposes on line 9 and 10

2023-12-06 15:55 UTC, TJ-Everett requested changes
Great work Shane. Just need to plug in the links in the Rule-Guide md

2023-12-06 18:19 UTC, oscarsernarosero approved these changes
Looks good Shane. I only have one small question/suggestion, but it looks great, so Im approving.

2023-12-06 18:19 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +8. Steps 4 and 5 are repeated for each of the account's tags.
Should we mention that the default behavior will be to enforce the most restrictive sub rule in case of multiple tags matching?

2023-12-06 18:24 UTC, oscarsernarosero commented on docs/userGuides/rules/ACCOUNT-PURCHASE-CONTROLLER.md
> +8. Steps 4 and 5 are repeated for each of the account's tags.
you also skipped step 7

2023-12-07 15:24 UTC, TJ-Everett approved these changes
Approved. Great work Shane.

2023-12-07 15:46 UTC, merged