Se 403 tagged rules processing optimization by skipping empty rules
thrackle-io/forte-rules-engine-v1 pull request #211
Opened 2023-12-08 18:00 UTC by TJ-Everett

2023-12-08 19:56 UTC, oscarsernarosero requested changes
This looks good, but we need to do the same for all tagged rules

2023-12-08 19:56 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +                    if(holdAmount != 0) {
Is there a reason why we didn't use the `holdPeriod` that is already accessed?

2023-12-08 20:03 UTC, TJ-Everett commented on src/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +                    if(holdAmount != 0) {
Great call - I will drop that back down a level and only call if we pass the holdPeriod check.

2023-12-11 15:28 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-12-11 22:40 UTC, merged