Se 461 add new amm created events to amm factory for UI tron py
thrackle-io/forte-rules-engine-v1 pull request #213
Opened 2023-12-08 21:48 UTC by TJ-Everett

Added events to AMM Calculators 
Added AMMCalculatorAssigned event to AMMs

2023-12-09 00:23 UTC, oscarsernarosero requested changes
I love it! I just think we should add the AMMCalculatorAssigned event to the AMM constructor as well since that's the only way that DOOM can now what calculator the AMM is using (if there's been no update yet).

2023-12-09 00:23 UTC, oscarsernarosero commented on src/liquidity/ProtocolERC20AMM.sol
> +        emit AMMDeployed(address(this), _token0, _token1, _appManagerAddress);
Should we add the `AMMCalculatorAssigned` right after this line?

2023-12-09 00:23 UTC, oscarsernarosero commented on src/liquidity/ProtocolERC721AMM.sol
> +        emit AMMDeployed(address(this), _ERC20Token, _ERC721Token, _appManagerAddress);
same here?

2023-12-09 00:23 UTC, oscarsernarosero commented on src/liquidity/calculators/ProtocolAMMCalcCP.sol
> +        emit AMMCalculatorDeployed();
love it

2023-12-11 14:34 UTC, TJ-Everett commented on src/liquidity/ProtocolERC20AMM.sol
> +        emit AMMDeployed(address(this), _token0, _token1, _appManagerAddress);
So I thought about that and actually had it there, then when I ran the tests it fires the event twice. Since it is firing from the _setcalculatorAddress() in the constructor. So it does fire at deployment in both types of AMMs and then it also fires when created from the factory as well.

2023-12-12 20:44 UTC, oscarsernarosero approved these changes
Great job Tayler!

2023-12-12 20:44 UTC, oscarsernarosero commented on src/liquidity/ProtocolERC20AMM.sol
> +        emit AMMDeployed(address(this), _token0, _token1, _appManagerAddress);
ah I see man. Perfect then. Very efficient.

2023-12-12 21:15 UTC, ShaneDuncan602 approved these changes
Looks great!

2023-12-12 22:02 UTC, merged