Se 448 move all test setup logic to test common files
thrackle-io/forte-rules-engine-v1 pull request #219
Opened 2023-12-18 22:31 UTC by TJ-Everett

2023-12-19 16:31 UTC, oscarsernarosero requested changes
This looks great so far and it looks like it's going in the right direction. I left a comment to basically point to the fact that we should use polymorphism for the array-creation functions, and I think rule-creation encapsulation should be done in this ticket as explained in the ticket itself. We can do the setup process the way you proposed in the coming tickets, but the rule creation should be done here if we want to be efficient for the next tickets.

2023-12-19 16:31 UTC, oscarsernarosero commented on test/util/TestArrays.sol
> +    function createUint256SizeOneArray(uint256 arg1) public pure returns(uint256[] memory array) {
I think it is better if you name the functions the same. I left an example in the [document](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/214401029/EVM+Protocol+Testing+Strategy+-+DRAFT#Creation-Of-Utility-Contracts). This way we only have one function name to create an array of size 1, 2 or 3.

2023-12-19 17:56 UTC, TJ-Everett commented on test/util/TestArrays.sol
> +    function createUint256SizeOneArray(uint256 arg1) public pure returns(uint256[] memory array) {
I see your point and I don't necessarily disagree. I built out the unique names more to add explicit clarity in the test code. In my mind it was more clear this way. If we would rather have the same function name and just based on number of params I can work to change these.

2023-12-20 15:30 UTC, TJ-Everett commented on test/util/TestArrays.sol
> +    function createUint256SizeOneArray(uint256 arg1) public pure returns(uint256[] memory array) {
@ShaneDuncan602 Can you be the tie breaker vote on polymorphism for this one? I am happy either way just need to know. 
Also @oscarsernarosero the rule creation encapsulation ticket is created and in the next sprint (planning session). Let me know if that satisfies what you wanted done in the this.

2023-12-21 15:52 UTC, ShaneDuncan602 commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> +    bytes32 public constant SUPER_ADMIN_ROLE = keccak256("SUPER_ADMIN_ROLE");
I think we would want all the role definitions in the TestCommon

2023-12-21 15:54 UTC, ShaneDuncan602 commented on test/client/application/integration/ApplicationAppManager.t.sol
> +
Same here. We shouldn't be redefining these roles.

2023-12-21 15:55 UTC, TJ-Everett commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> +    bytes32 public constant SUPER_ADMIN_ROLE = keccak256("SUPER_ADMIN_ROLE");
I tried this, because I thought the same thing, and it was blowing up. The role hashes expected by the test were not the same role hashes passed form common. I spent a good deal of time trying to troubleshoot but I can try again if we think that was a "me" issue.

2023-12-21 15:58 UTC, ShaneDuncan602 commented on test/client/token/ERC20/integration/ApplicationERC20.t.sol
> +        uint16[] memory holdPeriods = createUint16SizeThreeArray(720, 4380, 17520);
These changes are so much cleaner. Good thinking.

2023-12-21 15:59 UTC, ShaneDuncan602 commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
> +        setUpProcotolAndCreateERC20AndHandlerSpecialOwner();
nice

2023-12-21 16:05 UTC, ShaneDuncan602 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        setUpProtocolAndAppManagerAndTokensUpgradeable();
This kicks ass

2023-12-21 16:17 UTC, ShaneDuncan602 commented on test/util/TestArrays.sol
> +    function createUint256SizeOneArray(uint256 arg1) public pure returns(uint256[] memory array) {
I agree with Oscar on this one. Sorry! I know that means more work, but I think the benefit of having one function handle all the sizes outweighs the explicit clarity. It just seems a lot cleaner.

2023-12-21 16:26 UTC, ShaneDuncan602 requested changes
This looks really good. The tests are so much cleaner than before. I have a few suggestions. I think the role definitions should be moved to the common test files, I agree with Oscar on the array creation functions, and I think we need to look at DiamondTestUtil and RuleProcessorDiamondTestUtil. Can't we get rid of those now?

2023-12-21 19:11 UTC, oscarsernarosero approved these changes
Looks great Tayler

2023-12-22 15:39 UTC, merged