Multiple updates to support easier deployment.
thrackle-io/forte-rules-engine-v1 pull request #230
Opened 2024-01-08 21:26 UTC by mpetersoCode55

1. Split the DeployAllModules into multiple scripts. Split between deplying facets and deploying the rule processor diamond. (verified this split works on mumbai)
2. Added a DeployExampleGame script that automates deploying locally and on an actual chain. Creates the contracts for the application (copies and modifies based on applicaiton name) deploys the protocol and the application (or just the application if the protocol is already deployed) and updates  the .env file for you.
3. Updated some documentation to specify the version of foundry needed.

2024-01-08 21:29 UTC, ShaneDuncan602 commented on .env
> +
I don't understand what this for? Are these the default addresses and they will get changed by the script? Also, are the duplicates supposed to be here?

2024-01-08 21:30 UTC, ShaneDuncan602 commented on .env
> +DEPLOYMENT_OWNER_KEY=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
We need to keep these defaulted or the tests won't run correctly.

2024-01-08 21:30 UTC, ShaneDuncan602 commented on .env
> +DEPLOYMENT_RULE_PROCESSOR_DIAMOND=0x88dD21924FbEeccC4dC8Ae3a0e207ecCA03c5b92
Same here.

2024-01-08 21:32 UTC, ShaneDuncan602 commented on .env
> +FEE_RULE_DATA=0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1
I think something happened to this file. Something bad. Something unfortunate. Something that it won't be able to just wash off.

2024-01-08 21:32 UTC, ShaneDuncan602 commented on docs/userGuides/README.md
> +Note: Due to an issue with the latest version of foundry at the time of writing, we are currently using a specific foundry verion. To guarantee expected behavior please run the following command:
verion

2024-01-08 21:33 UTC, mpetersoCode55 commented on .env
> +
These are the defaults from an anvil deployment, and yes the script will update them as you deploy. Good catch on the duplicates I'll remove them

2024-01-08 21:34 UTC, mpetersoCode55 commented on .env
> +DEPLOYMENT_OWNER_KEY=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
Ok I'll shift them back to the defaults

2024-01-08 21:36 UTC, mpetersoCode55 commented on .env
> +
Resolved.

2024-01-08 21:37 UTC, mpetersoCode55 commented on .env
> +DEPLOYMENT_OWNER_KEY=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
Resolved.

2024-01-08 21:37 UTC, mpetersoCode55 commented on .env
> +DEPLOYMENT_RULE_PROCESSOR_DIAMOND=0x88dD21924FbEeccC4dC8Ae3a0e207ecCA03c5b92
Resolved.

2024-01-08 21:38 UTC, mpetersoCode55 commented on .env
> +FEE_RULE_DATA=0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1
Originally was piping the variables to the .env file, updated to use sed to update what was already there ... missed these to when I was removing the original piping

2024-01-08 21:38 UTC, mpetersoCode55 commented on .env
> +FEE_RULE_DATA=0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1
Resolved.

2024-01-08 21:39 UTC, mpetersoCode55 commented on docs/userGuides/README.md
> +Note: Due to an issue with the latest version of foundry at the time of writing, we are currently using a specific foundry verion. To guarantee expected behavior please run the following command:
Resolved.

2024-01-08 21:39 UTC, ShaneDuncan602 commented on script/DeployAllModulesPt1.s.sol
> +}
Things would be much simpler if you deployed the diamond in this first script. I thought that was the plan so that you wouldn't have to retrieve all of those facet addresses. All you would need is to retrieve the Diamond address and then use that in the subsequent scripts. So essentially you would create the diamond, add some facets in the first script. Then the other scripts would just grab the diamond address and add more facets to it.

2024-01-08 21:42 UTC, ShaneDuncan602 commented on script/DeployExampleGame.sh
> +if [ "$LOCAL" = "y" ]; then
I think we need to validate these entry variables. I know it's a little tedious, but currently a "Y" would make it try to deploy remotely. Maybe not all the variables will need it but probably the main ones.

2024-01-08 21:46 UTC, mpetersoCode55 commented on script/DeployExampleGame.sh
> +if [ "$LOCAL" = "y" ]; then
Do you think just forcing it to lower case is enough validation? Or checking for different variants (y, Y, yes, YES, etc)?

2024-01-08 21:55 UTC, ShaneDuncan602 requested changes
This is really cool. I'm going to go ahead and set to "Request changes" until the deployment script gets reworked. You did a great job on this.

2024-01-08 23:15 UTC, oscarsernarosero commented on .env
> +
Just to document what we agreed on in the slack discussion, we still want to keep the rule-processor address here and update it through the script created in this ticket.

2024-01-09 15:04 UTC, mpetersoCode55 commented on script/DeployAllModulesPt1.s.sol
> +}
Resolved.

2024-01-09 15:04 UTC, mpetersoCode55 commented on script/DeployExampleGame.sh
> +if [ "$LOCAL" = "y" ]; then
Resolved.

2024-01-09 15:38 UTC, TJ-Everett commented on script/DeployAllModules.s.sol
> +            // "FeeRuleDataFacet"
Q: Was this left as commented out on purpose? 
If so, we should either remove the whole script file and have the make deployAll command run the new scripts and inform Rob / Brandon we have a new way of deploying.

2024-01-09 15:39 UTC, TJ-Everett commented on script/DeployAllModulesPt1.s.sol
> +contract DeployAllModulesScript is Script {
Bit of a nitpick but will help Brandon on the Tron side is to have the file name match the contract name so each one of the scripts should be Pt1, Pt2, etc.

2024-01-09 15:40 UTC, TJ-Everett approved these changes
Really great work overall Michael and I am glad we have these working both with deploying the diamond and calling diamond cut to upgrade. This will be key to the longevity of the protocol. 
1 question and some tediousness in the naming. Approved overall.

2024-01-09 15:50 UTC, mpetersoCode55 commented on script/DeployAllModules.s.sol
> +            // "FeeRuleDataFacet"
Good catch, meant to revert that before committing I'll fix it!

2024-01-09 15:52 UTC, ShaneDuncan602 commented on script/DeployAllModules.s.sol
> +            // "FeeRuleDataFacet"
I agree, we need to keep this script working for DOOM.

2024-01-09 15:53 UTC, mpetersoCode55 commented on script/DeployAllModules.s.sol
> +            // "FeeRuleDataFacet"
Resolved.

2024-01-09 15:53 UTC, mpetersoCode55 commented on script/DeployAllModulesPt1.s.sol
> +contract DeployAllModulesScript is Script {
Resolved.

2024-01-09 15:54 UTC, ShaneDuncan602 approved these changes

2024-01-09 17:40 UTC, oscarsernarosero approved these changes
Looks great Michael. Great job.

2024-01-09 17:40 UTC, oscarsernarosero commented on docs/userGuides/README.md
> +
nice

2024-01-09 17:40 UTC, merged