Updated asset handlers to allow for multiple oracle rules (up to 10)
thrackle-io/forte-rules-engine-v1 pull request #234
Opened 2024-01-10 18:34 UTC by mpetersoCode55

Implements [SE-529](https://thracklelabs.atlassian.net/browse/SE-529)

[SE-529]: https://thracklelabs.atlassian.net/browse/SE-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-10 20:22 UTC, TJ-Everett commented on docs/src/src/client/token/ERC20/ProtocolERC20Handler.sol/contract.ProtocolERC20Handler.md
Anything in the dcos/src/src directory is auto generated by foundry based on the natspec commentary - so we don't update these as they will auto update through github actions

2024-01-10 20:34 UTC, mpetersoCode55 commented on docs/src/src/client/token/ERC20/ProtocolERC20Handler.sol/contract.ProtocolERC20Handler.md
That makes so much more sense, I kept thinking man this is a pain

2024-01-10 20:41 UTC, oscarsernarosero requested changes
This is a great first ticket Michael. I left some comments.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    struct OracleRuleStruct {
I think just naming this OracleRule would be a good name.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    OracleRuleStruct[] private oracleRuleIds;
I know you were trying to keep the naming patter, but since this rule is basically breaking the pattern, I think it's ok if you name this differently. Maybe `oracleRules`

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        if (nextOracleRuleIndex >= 10) {
10 must be set in a constant/variable. We shouldn't have magic numbers

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        address oracleAddress;
also, I don't think you need this variable. That's supposed to be stored at the protocol level.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    uint32 private nextOracleRuleIndex;
could this simply be extracted from the array length?

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        }
nice. This is perfect. Only thing is that to save gas, for loops in Solidity should have the increment of the iterator in an `unchecked` block at the end of the body. You can look for one in the repo for an example. This is not necessary in the latest Solidity version, but we still using 0.8.17 so we still need it.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        address oracleAddress = ERC20RuleProcessorFacet(address(ruleProcessor)).getOracleRule(_ruleId).oracleAddress;
We shouldn't be doing this. We don't really need the oracleAddress. That's what the protocol is for.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function activateOracleRule(bool _on, address oracleAddress) external ruleAdministratorOnly(appManagerAddress) {
If you get rid of the oracleAddress, you would need the ruleId here.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        for (uint256 oracleRuleIndex = 0; oracleRuleIndex < nextOracleRuleIndex; oracleRuleIndex++) {
same about the iterator as above

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
I would ask for an index in the array instead of an oracleAddress

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function isOracleActive(address oracleAddress) external view returns (bool) {
Maybe ask for the ruleId

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
>      }
Since we are now dealing with an array, the question is how are you managing that array? how do you remove rules from it? There is already a pattern regarding arrays in Solidity since it is not a straight forward matter. You can check the repo for examples. For instance, the `_removeAddressWithMapping` function in the AppManager. Although, in this case it would be even simpler beccause I don't think we need to keep track of indexes, but maybe we could. I'll leave that decision to you.

2024-01-10 20:41 UTC, oscarsernarosero commented on src/client/token/ERC721/ProtocolERC721Handler.sol
>      /**
same as above

2024-01-10 20:41 UTC, mpetersoCode55 commented on docs/src/src/client/token/ERC20/ProtocolERC20Handler.sol/contract.ProtocolERC20Handler.md
Resolved

2024-01-10 20:44 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    OracleRuleStruct[] private oracleRuleIds;
This is actually funny. I am doing something very similar in the action rule ticket. Change is coming!

2024-01-10 20:49 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
Ironically I originally had this as the index into the array, I changed it because I thought from a usability perspective it would make more sense to pass in the address of the oracle the rule corresponds to instead of having to track the order in which you added the rules so you'll know the index to pass in. 
Also when I add the ability to remove rules from the array like you suggested below, tracking the index will get more complicated, vice just checking against the address of the oracle the rule corresponds to.
What are your thoughts?

2024-01-10 20:51 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    struct OracleRuleStruct {
Resolved

2024-01-10 20:52 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        address oracleAddress = ERC20RuleProcessorFacet(address(ruleProcessor)).getOracleRule(_ruleId).oracleAddress;
Agreed. You only need to maintain a list of refId's

2024-01-10 20:54 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    OracleRuleStruct[] private oracleRuleIds;
Resolved

2024-01-10 20:55 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
>          if (_on) {
I think you would only emit the event if the refId exists. Probably need to validate here as well. For instance, if they have 2 oracle rules, but make a mistake on the refId for this deactivation, they would get a completed transaction and an event but nothing would have really changed.

2024-01-10 20:55 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        if (nextOracleRuleIndex >= 10) {
Resolved

2024-01-10 20:56 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
Yep, we need to remove every reference to oracle address in here.

2024-01-10 20:57 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
>      }
In this situation, I don't think it warrants a mapping. It has a max of 10 so it could just loop through until it found it and then deactivated/removed it.

2024-01-10 21:00 UTC, ShaneDuncan602 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
I could see where using the address would be easier for the devs but we have to keep this decoupled from the rule itself. It's up to the devs to know what refId is for each oracle. DOOM will also help them with this.

2024-01-10 21:01 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
Usually, with Solidity arrays, you rely on a mapping to keep track of the indexes. That would solve this issue since you can pass the ruleId instead of the index or oracleAddress, and that would be the best solution from the user and technical perspective imo since we keep parity with the other rules. Checkout implementations of ERC721Enumerable when they deal with removing or adding tokenIds, or you can also checkout `_removeAddressWithMapping` (it is the same concept but applied to a specific case). But basically, you have a mapping with indexes  `mapping (oracleRuleId => index) oracleRuleIdToIndex` and you keep it up to date every time you update the array.

2024-01-10 21:13 UTC, TJ-Everett reviewed
I will re-review once you finish with the feedback

2024-01-10 21:15 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
sorry. scratch all this. I was thinking this was for another function

2024-01-10 21:36 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        address oracleAddress;
Resolved

2024-01-10 21:36 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    uint32 private nextOracleRuleIndex;
Resolved

2024-01-10 21:36 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        address oracleAddress = ERC20RuleProcessorFacet(address(ruleProcessor)).getOracleRule(_ruleId).oracleAddress;
Resolved

2024-01-10 21:37 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function activateOracleRule(bool _on, address oracleAddress) external ruleAdministratorOnly(appManagerAddress) {
Resolved

2024-01-10 21:37 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function getOracleRuleId(address oracleAddress) external view returns (uint32) {
Resolved

2024-01-10 21:37 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +    function isOracleActive(address oracleAddress) external view returns (bool) {
Resolved

2024-01-10 21:38 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
>          if (_on) {
Resolved

2024-01-10 21:44 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        for (uint256 oracleRuleIndex = 0; oracleRuleIndex < nextOracleRuleIndex; oracleRuleIndex++) {
Resolved

2024-01-10 21:44 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        }
Resolved

2024-01-10 22:16 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
>      }
Resolved.

2024-01-10 22:44 UTC, oscarsernarosero requested changes
Almost there.

2024-01-10 22:44 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        for (uint256 oracleRuleIndex = 0; oracleRuleIndex < oracleRules.length; ) {
This looks much better man. This is just a comment. There is no real need to go and change this, but I forgot to tell you in the past PR that Solidity's default values are 0, address(0), false, etc. So it is not necessary to initialize to a default value.

2024-01-10 22:44 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        if (oracleRules.length >= 10) {
We still have this magic number. You should create a constant to set this value. You can check GeneralTags under src/client/application/data for a similar piece.

2024-01-10 22:44 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +            oracleRules[oracleRules.length - 1] = ruleToSwap;
you can skip this last step. It doesn't matter what we have here since we are gonna pop it.

2024-01-10 22:44 UTC, oscarsernarosero commented on src/client/token/ERC721/ProtocolERC721Handler.sol
> +    uint16 constant MAX_ORACLE_RULES = 10;
this is why Im proposing to move these rules to a contract we can inherit. You did this here, but not in the other one.

2024-01-10 22:44 UTC, oscarsernarosero commented on src/client/token/ERC721/ProtocolERC721Handler.sol
> +        if (oracleRules.length >= 10) {
still not using it tho

2024-01-10 22:44 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
> +        goodBoys.push(address(69));
lol I love it, but Tayler already got mad at me about this before.

2024-01-11 14:08 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        for (uint256 oracleRuleIndex = 0; oracleRuleIndex < oracleRules.length; ) {
Since I'm already changing things in these files I went ahead and fixed this.

2024-01-11 14:09 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +        if (oracleRules.length >= 10) {
Resolved

2024-01-11 14:09 UTC, mpetersoCode55 commented on src/client/token/ERC721/ProtocolERC721Handler.sol
> +    uint16 constant MAX_ORACLE_RULES = 10;
Resolved

2024-01-11 14:09 UTC, mpetersoCode55 commented on src/client/token/ERC721/ProtocolERC721Handler.sol
> +    uint16 constant MAX_ORACLE_RULES = 10;
Agreed we should definitely move the common logic into a contract we inherit from, there's a lot of duplication

2024-01-11 14:10 UTC, mpetersoCode55 commented on src/client/token/ERC721/ProtocolERC721Handler.sol
> +        if (oracleRules.length >= 10) {
Resolved

2024-01-11 14:12 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20Handler.sol
> +            oracleRules[oracleRules.length - 1] = ruleToSwap;
Resolved.

2024-01-11 14:13 UTC, mpetersoCode55 commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
> +        goodBoys.push(address(69));
No fun! I updated it to be 68

2024-01-11 19:37 UTC, oscarsernarosero approved these changes
Looks great Michael

2024-01-11 19:43 UTC, merged