Restructured admin roles document.
thrackle-io/forte-rules-engine-v1 pull request #241
Opened 2024-01-12 19:46 UTC by mpetersoCode55

Restructured the admin roles document to treat each role as its own section.

2024-01-12 21:51 UTC, TJ-Everett approved these changes
Awesome job Michael

2024-01-12 22:45 UTC, oscarsernarosero requested changes
This looks overall really good. Just some details.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Super admin is set at construction of the App Manager(the deploying address of the AppManager). This role has the highest level of permissions and can grant/revoke the app admin role. Functions with
I would say it `has the highest hierarchy of the roles` instead of `role has the highest level of permissions` since it doesn't really has a lot of permissions.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +* The Super Administrator should be a multi-signature account.
This is a great point, and we should definitely have it in the docs, but I think this is more of a recommendation so it should not be in this section.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Risk admin is set at construction and can be granted only by the app admin at any time. This role sets the risk level for addresses within the application app manager. Functions with the modifier onl
the only roles that are set at construction time are the superAdmin and the appAdmin.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Access tier is set at construction and can be granted only by the app admin at any time. This role sets the access level for addresses within the application app manager. Functions with the modifier
Same here. The only roles that are set at construction time are the superAdmin and the appAdmin.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Rule Admin: Rule admin is set at construction and can be granted only by the app admin at any time. This role can activate and deactivate economic rules within the handler contracts. Functions with t
Same here. Also, the format looks different here.

2024-01-12 22:45 UTC, oscarsernarosero commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +* Rule Administrators may renounce their role.
They're also the only role that can create a rule in the protocol

2024-01-16 14:00 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Super admin is set at construction of the App Manager(the deploying address of the AppManager). This role has the highest level of permissions and can grant/revoke the app admin role. Functions with
Resolved

2024-01-16 14:01 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Risk admin is set at construction and can be granted only by the app admin at any time. This role sets the risk level for addresses within the application app manager. Functions with the modifier onl
Resolved

2024-01-16 14:03 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Access tier is set at construction and can be granted only by the app admin at any time. This role sets the access level for addresses within the application app manager. Functions with the modifier
Resolved

2024-01-16 14:04 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Rule Admin: Rule admin is set at construction and can be granted only by the app admin at any time. This role can activate and deactivate economic rules within the handler contracts. Functions with t
Resolved

2024-01-16 14:44 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +* Rule Administrators may renounce their role.
Resolved

2024-01-16 14:45 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +* The Super Administrator should be a multi-signature account.
Resolved

2024-01-16 19:27 UTC, oscarsernarosero approved these changes
Looks good!

2024-01-16 20:30 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Rule Bypass Account is set at construction and can be granted only by the app admin at any time. This role is exempt from all economic rules except for the Admin Withdrawal rule. This role cannot be
I don't agree that this role is set at construction.  That seems to imply that it is set when the AppManager is created. All of the roles are created at construction, but the only ones set are the Super and AppAdmin. The AppManager deployer gets these roles.

2024-01-16 20:31 UTC, ShaneDuncan602 requested changes
One clarification, but really good. Tech Doc Mike does not play around.

2024-01-17 14:50 UTC, mpetersoCode55 commented on docs/userGuides/deployment/ADMIN-ROLES.md
> +Rule Bypass Account is set at construction and can be granted only by the app admin at any time. This role is exempt from all economic rules except for the Admin Withdrawal rule. This role cannot be
Resolved

2024-01-17 14:52 UTC, merged