Se 499 document amm fee buy
thrackle-io/forte-rules-engine-v1 pull request #242
Opened 2024-01-12 21:36 UTC by TJ-Everett

Created document architecture for Fees, FEE-Guide.md, PROTOCOL-FEE-STRUCTURE.md, BUY-FEE.md, SELL-FEE.md

2024-01-12 22:28 UTC, oscarsernarosero requested changes
This is a great job Tayler. I like the structure. I requested some minor changes, but I have always been a bit confused about fees, so I might be off on some comments.

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +Protocol supported tokens and AMMs will always assess all fees asigned to the account executing the current function. If a token and AMM have fees active and an account is tagged with applicable fees
This is totally accurate with the code, but Im realizing there might be an issue with the way we implemented this. If we calculate fees on the `msg.sender` instead of the `from` or `to` address, then when a swap is executed, the `msg.sender` will be the AMM and not the owner of the tokens. Am I tripping?

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/FEE-GUIDE.md
Maybe call this file README?

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +AMM Fees work at the AMM level. Fees must be activated and configured for each AMM in the corresponding AMM handler. AMM fees are assessed in the swap function of the AMM.
Maybe create a subsection for each kind, or use bullets.

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +The AMM loops through each applicable fee and sends that amount from the transfer total to the `feeCollectorAccount` for that fee. The total amount of fees assesed is tracked within the swap as `fees
same here. Probably subsection is better.

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +- There are no evaluation exceptions when fees are active.
what about treasury?

2024-01-12 22:28 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +Fee totals are added inside of a loop and then total fees are subtracted from the amount being transferred within the transfer or swap functions. This data is not saved to storage.
nice

2024-01-16 16:04 UTC, mpetersoCode55 requested changes

2024-01-16 16:04 UTC, mpetersoCode55 commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +Protocol supported tokens and AMMs will always assess all fees asigned to the account executing the current function. If a token and AMM have fees active and an account is tagged with applicable fees
Discussed in huddle, it may be worth adding a note that token transfer fees are taken from the protocol supported token being transferred (instead of a collateralized token like in the AMM swap)

2024-01-16 16:04 UTC, mpetersoCode55 commented on docs/userGuides/fees/AMM-SELL-FEE.md
> +Protocol supported tokens and AMMs will always assess all fees asigned to the account executing the current function. If a token and AMM have fees active and an account is tagged with applicable fees
Same note from the Buy Fee

2024-01-16 16:04 UTC, mpetersoCode55 commented on docs/userGuides/fees/FEE-GUIDE.md
> +| [AMM Sell Fee](./AMM-SELL-FEE.md) | The purpose of the AMM Sell Fee is to assess fees via the AMM swap function for purchases. A purchase via the AMM is defined as the user exchanging application t
Shouldn't this one be focused on the sale side instead of the purchase? Just reading the two overviews I can't tell the difference between AMM Buy Fee and AMM Sell Fee

2024-01-16 16:04 UTC, mpetersoCode55 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +- Fees can only be aremoved in the asset handler by the **owner**.
typo on removed

2024-01-16 16:04 UTC, mpetersoCode55 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +The AMM retrieves all applicable fees for the account transferring tokens (swpper) for the token being swapped. If token 1 is swapped for token 0, token 1 has fees assessed.
Is this true? I thought the AMM fees were always take from the collateralized token, regardless of which direction you're swapping.

2024-01-16 17:02 UTC, TJ-Everett commented on docs/userGuides/fees/FEE-GUIDE.md
FEE-README.md?

2024-01-16 17:07 UTC, TJ-Everett commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +- There are no evaluation exceptions when fees are active.
Great Question! Since fees will be assessed on every transfer or swap when the fee rules are active- there isn't an "exception" to the check but those would accounts and contracts wouldn't be tagged with a fee so they don't have a fee but are still checked. 

Should I explain that in this section?

2024-01-16 17:08 UTC, TJ-Everett commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +The AMM retrieves all applicable fees for the account transferring tokens (swpper) for the token being swapped. If token 1 is swapped for token 0, token 1 has fees assessed.
Great catch I will reword this to a true statement.

2024-01-16 17:38 UTC, TJ-Everett commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +Protocol supported tokens and AMMs will always assess all fees asigned to the account executing the current function. If a token and AMM have fees active and an account is tagged with applicable fees
You mean that in a scenario where there are token fees and AMM fees we would not be assessing the token fee in the swap because we pass in msg.sender instead of from/to? 

Inside the AMM the msg.sender is the address calling swap. Then that address is used throughout. I don't think it is is an issue, outside of the possibility above. Unless I am misunderstanding this entirely.

2024-01-16 18:42 UTC, mpetersoCode55 commented on docs/userGuides/fees/FEE-GUIDE.md
Or just shorten it to FEEDME.md

2024-01-16 18:43 UTC, mpetersoCode55 approved these changes

2024-01-16 19:19 UTC, oscarsernarosero commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +Protocol supported tokens and AMMs will always assess all fees asigned to the account executing the current function. If a token and AMM have fees active and an account is tagged with applicable fees
I think you're right.

2024-01-16 19:21 UTC, oscarsernarosero commented on docs/userGuides/fees/FEE-GUIDE.md
Well, the reason to call it README.md specifically is so it can automatically be shown by GH page once you land on this directory. Since this is basically a map of the directory, it makes sense for this document to be the one showing up.

2024-01-16 19:24 UTC, oscarsernarosero approved these changes
Well done! I'll leave it to you if you want to make the FEE-GUIDE the page popping up.

2024-01-16 20:38 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +The purpose of the AMM Buy Fee is to assess fees via the AMM swap function for purchases. A purchase via the AMM is defined as the user exchanging collateralized tokens for application tokens via the
I think the MATIC is always just referred to as MATIC. I've never seen it abbreviated MATC.

2024-01-16 20:45 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +- [x] AMM
I'm not sure this really applies to all 3 here. This document is titled, "AMM-BUY-FEE". This "Applies To:" section seems a little confusing to me. Can we get rid of it?

2024-01-16 20:56 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-BUY-FEE.md
> +A Buy Fee is the additive amount of all applicable fees for the account calling the swap function that swaps the user's collateralized tokens for application tokens inside the AMM.
This is a complex sentence. Can we break it up into pieces like, "Buy fees are assessed on the collateralized token being swapped for application tokens inside the AMM. The fees are additive. If a user has multiple applicable fees, the sum of all their fees will be assessed."

2024-01-16 20:57 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-SELL-FEE.md
> +The purpose of the AMM Sell Fee is to assess fees via the AMM swap function for sales. A sale via the AMM is defined as the user exchanging application tokens for collateralized tokens via the AMM. C
Same comment about MATC as above.

2024-01-16 21:10 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-SELL-FEE.md
> +- [x] AMM
Same comment as above.

2024-01-16 21:11 UTC, ShaneDuncan602 commented on docs/userGuides/fees/AMM-SELL-FEE.md
> +A Sell Fee is the additive amount of all applicable fees for the account calling the swap function that swaps the user's application tokens for collateralized tokens inside the AMM.
This is a complex sentence. Can we break it up into pieces like, "Sell fees are assessed on the collateralized token being received during swaps for application tokens inside the AMM. The fees are additive. If a user has multiple applicable fees, the sum of all their fees will be assessed."

2024-01-16 21:23 UTC, ShaneDuncan602 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +- Fees can only be removed in the asset handler by the **owner**.
Fees are configured by the Rule Admins. The Fee contract has owner on it but the owner is actually the handler.

2024-01-16 21:24 UTC, ShaneDuncan602 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +The AMM retrieves all applicable fees for the account calling the swap function (swpper).
swpper?

2024-01-16 21:25 UTC, ShaneDuncan602 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +function addFee(bytes32 _tag, uint256 _minBalance, uint256 _maxBalance, int24 _feePercentage, address _targetAccount) external onlyOwner;
This function should be the handler's pass through function. The function in Fees.sol will never be called directly.

2024-01-16 21:28 UTC, ShaneDuncan602 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +The create function will return the protocol ID of the rule.
Fees don't have protocol ID's. The FeeRuleDataFacet still exists but is not currently used.

2024-01-16 21:31 UTC, ShaneDuncan602 requested changes
Just a few minor things. This is good stuff. A lot of good detail.

2024-01-16 22:24 UTC, ShaneDuncan602 approved these changes
Looks perfect!

2024-01-16 22:52 UTC, merged