Create TRANSFER-FEE.md
thrackle-io/forte-rules-engine-v1 pull request #245
Opened 2024-01-18 17:29 UTC by TJ-Everett

2024-01-18 19:03 UTC, oscarsernarosero requested changes
Looks good! I just have some suggestions.

2024-01-18 19:03 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +When an AMM or token handler is deployed a Fee data contract is deployed at the same time. All supporting fee data is stored in this contract and owned by the deployer. Data contracts can be migrated
I think a comma after `... handler is deployed` -> `handler is deployed, a Fee data contract is`

2024-01-18 19:03 UTC, oscarsernarosero commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +When an AMM or token handler is deployed a Fee data contract is deployed at the same time. All supporting fee data is stored in this contract and owned by the deployer. Data contracts can be migrated
or simply invert the order of the 2 sentences and there would be no need for a comma since the `when` would be the connector.

2024-01-18 19:03 UTC, oscarsernarosero commented on docs/userGuides/fees/TRANSFER-FEE.md
> +The purpose of the Transfer Fee is to assess fees when protocol supported tokens are transferred. Application developers can utilize fees to influence their application's economy through incentivisin
`incentivized behavior`?

2024-01-18 19:03 UTC, oscarsernarosero commented on docs/userGuides/fees/TRANSFER-FEE.md
> +The purpose of the Transfer Fee is to assess fees when protocol supported tokens are transferred. Application developers can utilize fees to influence their application's economy through incentivisin
I think you can get rid of this piece ` Token transfer fees are assessed and taken from the token itself, not a collateralized token, when fees are active in the token handler. `. I think it is kinda obvious, and It could cause confusion.

2024-01-18 19:03 UTC, oscarsernarosero commented on docs/userGuides/fees/TRANSFER-FEE.md
> +- **Tags**: This rule relies on accounts having [tags](../GLOSSARY.md) registered in their [AppManager](../GLOSSARY.md), and they should match at least one of the tags in the rule for it to have any
We should explain how fees are expressed somewhere (it is a percentage expressed in basis points). I think you mentioned the max percentage somewhere in a past ticket, but maybe that should be in the README as a general rule for all fees alongside the convention to express fees (percentage in basis points).

2024-01-18 19:12 UTC, TJ-Everett commented on docs/userGuides/fees/TRANSFER-FEE.md
> +The purpose of the Transfer Fee is to assess fees when protocol supported tokens are transferred. Application developers can utilize fees to influence their application's economy through incentivisin
Valid point and will remove. "Incentivized behavior" came from the spec [doc](https://docs.google.com/document/d/1f2xx9S6y0MQCZIQm68gGdvkBge7zHjMvhtX4PyaNiiI/edit#heading=h.a94zo9fts5vw) and I liked it, if we have a preferred verbiage here I am all for it. Incentivized to me being you can tag accounts that dust trade or reward (discount) players that hold tokens longer, etc.

2024-01-18 19:13 UTC, TJ-Everett commented on docs/userGuides/fees/TRANSFER-FEE.md
> +- **Tags**: This rule relies on accounts having [tags](../GLOSSARY.md) registered in their [AppManager](../GLOSSARY.md), and they should match at least one of the tags in the rule for it to have any
Great point i will find an appropriate place for this and clarify.

2024-01-18 19:18 UTC, oscarsernarosero commented on docs/userGuides/fees/TRANSFER-FEE.md
> +The purpose of the Transfer Fee is to assess fees when protocol supported tokens are transferred. Application developers can utilize fees to influence their application's economy through incentivisin
I agree. sorry I wasn't clear. I was mostly pointing to the fact that it said "through incentivising behavior" and I was proposing "through incentivized behavior"

2024-01-22 17:40 UTC, oscarsernarosero approved these changes
Looks good

2024-01-22 18:10 UTC, ShaneDuncan602 commented on docs/userGuides/fees/PROTOCOL-FEE-STRUCTURE.md
> +A Fee data contract is deployed at the same time as the AMM or token handler. All supporting fee data is stored in this contract and owned by the deployer. Data contracts can be migrated to a new han
Not sure how to word this but the Data contract is actually owned by the handler. The deployer address can't really do anything with it.

2024-01-22 18:12 UTC, ShaneDuncan602 commented on docs/userGuides/fees/README.md
> +| [Protocol Fee Structure](./PROTOCOL-FEE-STRUCTURE.md) | This document outlines the overall fee structure of the protocol, how fees are applied and at what level the fees are applied. Each fee type
This sentence should have a comma, "When an AMM or token handler is deployed`,` a Fee"

2024-01-22 18:14 UTC, ShaneDuncan602 approved these changes
I just found a couple of minor things.

2024-01-22 19:10 UTC, merged