pricer contract configuration and third party adapters
thrackle-io/forte-rules-engine-v1 pull request #246
Opened 2024-01-19 01:48 UTC by oscarsernarosero

2024-01-19 21:22 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/README.md
>  Some protocol rules require these contracts to be set in the tokens for them to be able to work:
This should probably say, "Configured pricing modules are required for the following rules:"

2024-01-19 21:23 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/README.md
> +Setting up the pricer contracts for your application is really easy. Simply follow the next steps:
This is probably too conversational. We have to keep it business like. "To set up the pricer contracts:"

2024-01-19 21:26 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/README.md
> +2. Now, you are ready to connect your pricer-contract set to your appManager. For this, an account with the role of appAdministrator should call the following functions in the appManager handler:
"Now, you are ready to connect your pricer-contract.." should just be "Connect the pricer-contract..."

"an account with the role of appAdministrator should" should be "only an account with the role of appAdministrator will be able to call the following functions

2024-01-19 21:29 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/README.md
> +
In the other deployment instructions, we give them the actual cast command to use for calling the functions. I think we need to continue that trend here.

2024-01-19 21:30 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/THIRD-PARTY-SOLUTIONS.md
> +For the full interface, checkout [IProtocolERC20Pricing]("scr/common/IProtocolERC20Pricing.sol").
This link doesn't work. We probably need to change "checkout" to "see"

2024-01-19 21:30 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/THIRD-PARTY-SOLUTIONS.md
> +Developes may choose to implement and deploy an adapter contract per token standard (one for ERC20 and another for ERC721), or to implement both in a single contract to deploy. No matter the route ta
Developes

2024-01-19 21:32 UTC, ShaneDuncan602 commented on docs/userGuides/pricing/THIRD-PARTY-SOLUTIONS.md
> +
Should we create an example adapter contract? We have examples for all the other stuff. @jjbailey-io

2024-01-19 21:33 UTC, ShaneDuncan602 requested changes
Some suggestions and found some minor typos. Good stuff.

2024-01-19 22:22 UTC, jjbailey-io commented on docs/userGuides/pricing/THIRD-PARTY-SOLUTIONS.md
> +
I don't think that's necessary. Any example we'd provide likely wouldn't get used due to the infinite customization options available in pricing contracts.

2024-01-22 14:19 UTC, mpetersoCode55 approved these changes
Looks great!

2024-01-22 17:00 UTC, ShaneDuncan602 approved these changes
Looks awesome. Approved.

2024-01-22 17:01 UTC, merged