Se 449 create GitHub workflow for necessist run
thrackle-io/forte-rules-engine-v1 pull request #250
Opened 2024-01-23 03:10 UTC by bfcoursewool

Everything for automating necessist. Includes a dockerfile for the necessist build, github workflow for building and pushing to ECR as well as redeploying the k8s job from the new container, and a k8s manifest file describing the new necessist job. 

Run the workflow from here in github under Actions -> Run Necessist, and when it finally finishes (the GH workflow itself only takes 5 minutes) there will be a new necessist-YY-mm-dd.db file in the "necessist database" bucket of S3 in our AWS account. Voila!

2024-01-23 15:18 UTC, bcamp136 approved these changes

2024-01-23 20:34 UTC, oscarsernarosero reviewed
Looks good to me Rob. I didn't really mess at all with Necessist, so Shane will be the real test.

2024-01-23 21:56 UTC, ShaneDuncan602 commented on foundry.toml
> +code-size-limit = 0x60000
I don't think we need the 0x for this value. We should be fine with actually using the kb value of 45000 or so.

2024-01-23 21:57 UTC, ShaneDuncan602 commented on Dockerfile.anvil
> +ENTRYPOINT anvil --host 0.0.0.0 --code-size-limit 0x60000 --chain-id $CHAIN_ID
We could probably leave out the 0x value and just use the actual Kb

2024-01-23 22:02 UTC, ShaneDuncan602 commented on necessist-run.sh
> +necessist --verbose --framework foundry -- --ffi
ToB had to give us a fix for a problem that we encountered. We have to use

`cargo install --git https://github.com/trailofbits/necessist --branch fix-foundry-build`

2024-01-23 22:25 UTC, ShaneDuncan602 requested changes
Just a couple of questions

2024-01-30 16:30 UTC, ShaneDuncan602 approved these changes
Great job

2024-01-30 16:30 UTC, merged