Se 507 review protocol deployment documentation
thrackle-io/forte-rules-engine-v1 pull request #254
Opened 2024-01-26 07:57 UTC by oscarsernarosero

2024-01-31 13:44 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/CREATE-APP-RULES.md
> +        *Note: we are assumming that APP_ADMIN_1_KEY was also granted Rule Admin privileges.*
I think we should change this and use a dedicated rule admin in the documentation.

2024-01-31 13:48 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ADMIN-CONFIG.md
> +   *Note: Super Admin also gets granted **appAdmin** role during deployment. That's why we can use APP_ADMIN_1_KEY as **superAdmin**.*
I think the documentation should use a dedicated app admin rather than the shared super admin. The only reason the deployer gets the app admin privileges as well is because it saved us a lot of time reworking the tests. There was never a decision that this should be the case and I assume we will change it prior to the next audit because ToB wants a clear separation of admin roles. If we use the dedicated app admin then it works regardless of the decision.

2024-01-31 13:49 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ADMIN-CONFIG.md
> +   *Note: APP_ADMIN_1_KEY would still work since this address has both superAdmin and appAdmin privileges.*
see above

2024-01-31 13:50 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/CREATE-APP-RULES.md
> +        ````
I know we don't really have a choice but I have always hated that devs will have to do this. It is so clunky.

2024-01-31 13:52 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +        ````
This should probably be deployed with a dedicated super admin role.

2024-01-31 13:52 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +        The AppManager contract deployed in this step will automatically grant SuperAdmin and AppAdmin roles to the _Owner Address_ at construction time, and --if `_upgradeMode_ == false`-- new data
See above about the roles

2024-01-31 13:53 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +        ````
This would also need to be the super admin

2024-01-31 13:54 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-PRICING.md
> +Once your pricing modules have been deployed, it is time to set their addresses in you appManager handler. The appManager handler needs both variables set to work:
in your appManager handler

2024-01-31 14:00 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-PROTOCOL.md
> +   cast send $RULE_PROCESSOR_DIAMOND "updateVersion(string)()" <PROTOCOL_VERSION> --private-key $LOCAL_DEPLOYMENT_OWNER_KEY --rpc-url POLYGON_ETH_RPC_URL
This has POLYGON_ETH_RPC_URL but the other commands have $ETH_RPC_URL

2024-01-31 14:00 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-PROTOCOL.md
> +         cast send $RULE_PROCESSOR_DIAMOND "transferOwnership(address)" $MULTISIG_ADDRESS --private-key $LOCAL_DEPLOYMENT_OWNER_KEY --rpc-url POLYGON_ETH_RPC_URL
This has POLYGON_ETH_RPC_URL but the other commands have $ETH_RPC_URL

2024-01-31 14:01 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-PROTOCOL.md
> +         cast call $RULE_PROCESSOR_DIAMOND "owner()(address)" --rpc-url POLYGON_ETH_RPC_URL
This has POLYGON_ETH_RPC_URL but the other commands have $ETH_RPC_URL

2024-01-31 14:03 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ERC20-DEPLOYMENT.md
> +4. An ERC20Handler must be deployed with each ERC20 token and connected accordingly.
Minimum deployment also requires registering the token with the appManager

2024-01-31 14:05 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ERC20-DEPLOYMENT.md
> +        forge create src/example/ERC20/ApplicationERC20.sol:ApplicationERC20 --constructor-args  "MickeyMouseCoin" "MMC" $APPLICATION_APP_MANAGER --private-key $APP_ADMIN_1_KEY --rpc-url $ETH_RPC_URL
Can't use Mickey Mouse. Disney is one of the most litigious companies in the world. Let's stick with the public domain horror stuff like FrankensteinCoin, DraculaCoin, MummyCoin, etc.

2024-01-31 14:06 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/ERC20-DEPLOYMENT.md
> +    cast send $APPLICATION_APP_MANAGER "registerToken(string,address)()" "MMYC" $APPLICATION_COIN --private-key $APP_ADMIN_1_KEY --rpc-url $ETH_RPC_URL
MMYC

2024-01-31 14:07 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/NFT-DEPLOYMENT.md
> +* 0.1.1  --> NOT SURE WHAT TO PUT HERE
Just leaving it as 0.1.1 seems fine to me

2024-01-31 14:11 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/README.md
> +This guide explains how to deploy into your selected EVM blockchain everything you need for the protocol. From the protocol processor to the application tokens, this guide will lead you step by step
Let's change, "This guide explains how to deploy into your selected EVM blockchain everything you need for the protocol." to "This is a step-by-step guide to protocol and protocol supported application deployments." 

and remove this sentence: 

"From the protocol processor to the application tokens, this guide will lead you step by step in the deployment process."

and

"This guide is broken down into modules to make it easier to follow, and is listed in the same logical order that they must be deployed in order to succeed:" to "This guide is broken down into modules to make it easier to follow and is listed in the proper deployment order:"

2024-01-31 14:12 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/README.md
> +3. Setup the pricing module for your application. Go to [Deploy Pricing](DEPLOY-PRICING.md).
We probably need an "optional" flag on this because they don't really have to do it.

2024-01-31 14:14 UTC, ShaneDuncan602 commented on docs/userGuides/permissions/ADMIN-ROLES.md
> +6. [Rule-Bypass Account](#RULE-BYPASS-ACCOUNT).
nice. Didn't know this was possible.

2024-01-31 14:15 UTC, ShaneDuncan602 requested changes
Great work. This was needed badly. Just have a few suggestions.

2024-01-31 16:15 UTC, TJ-Everett commented on docs/userGuides/permissions/ADMIN-ROLES.md
> +6. [Rule-Bypass Account](#RULE-BYPASS-ACCOUNT).
I agree this is sweet! 
The  . and the end look a little funny, to me, in the docs in github.

2024-01-31 16:16 UTC, TJ-Everett reviewed
Holding approval as I agree with Shane's feedback on this one. Great work though, Oscar.

2024-01-31 17:43 UTC, oscarsernarosero commented on docs/userGuides/deployment/ERC20-DEPLOYMENT.md
> +        forge create src/example/ERC20/ApplicationERC20.sol:ApplicationERC20 --constructor-args  "MickeyMouseCoin" "MMC" $APPLICATION_APP_MANAGER --private-key $APP_ADMIN_1_KEY --rpc-url $ETH_RPC_URL
Mickey Mouse is public domain tho

2024-01-31 17:44 UTC, oscarsernarosero commented on docs/userGuides/deployment/ERC20-DEPLOYMENT.md
> +    cast send $APPLICATION_APP_MANAGER "registerToken(string,address)()" "MMYC" $APPLICATION_COIN --private-key $APP_ADMIN_1_KEY --rpc-url $ETH_RPC_URL
?

2024-01-31 17:44 UTC, oscarsernarosero commented on docs/userGuides/deployment/NFT-DEPLOYMENT.md
> +* 0.1.1  --> NOT SURE WHAT TO PUT HERE
cool

2024-01-31 19:30 UTC, oscarsernarosero commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +        The AppManager contract deployed in this step will automatically grant SuperAdmin and AppAdmin roles to the _Owner Address_ at construction time, and --if `_upgradeMode_ == false`-- new data
I agree with the superAdmin stuff. I think I'll leave this piece like this since we should reflect the current state of the code, and the current code does grant both of these roles at construction time.

2024-02-01 14:35 UTC, ShaneDuncan602 approved these changes
Looks fantastic.

2024-02-01 15:44 UTC, TJ-Everett approved these changes
Looks good Oscar!

2024-02-01 20:19 UTC, merged