SE-504-Document-Access-Level-configurations
thrackle-io/forte-rules-engine-v1 pull request #255
Opened 2024-01-26 16:01 UTC by ShaneDuncan602

2024-01-26 16:18 UTC, TJ-Everett commented on docs/userGuides/accessTier/ACCESS-TIER-RULES.md
> +
Idk if you saw the comment in the ticket but we have landed on access level instead of access tier so we will want to rename everything that is accessTier to access level. 

Also shouldn't the withdrawalRuleByAccessLevel be here too?

2024-01-26 16:19 UTC, TJ-Everett commented on docs/userGuides/accessTier/PROTOCOL-ACCESS-TIER-STRUCTURE.md
> +Access Tier levels can be assigned to accounts and addresses by Access Tier Administrators through the [AppManager](../../../src/client/application/AppManager.sol). They are predefined as 0,1,2,3,4 a
This will read cleaner when we update to just access levels. 
"Access levels can be assigned..."

2024-01-26 16:19 UTC, TJ-Everett commented on docs/userGuides/accessTier/PROTOCOL-ACCESS-TIER-STRUCTURE.md
> +Access Levels can be applied to individual accounts or addresses of contracts. When an access tier related rule is activated, all users will be subject to any limitations set by the rule related to t
Oscar doesn't like this phrasing haha

We landed on just "addresses"

2024-01-26 16:22 UTC, TJ-Everett requested changes
This is really great Shane! There are some areas to update this for access level vs access tier. 
I also recommend creating a README.md for this dir folder so it acts as a landing page for the folder (like in tags and risk scores).

2024-01-26 16:23 UTC, ShaneDuncan602 commented on docs/userGuides/accessTier/ACCESS-TIER-RULES.md
> +
Oh. I was thinking that was just for the score itself. I thought access tier would describe the module and level would be used for the actual value. And, yep, withdrawalLimitByAccessLevel should be here too. Missed it.

2024-01-29 15:47 UTC, TJ-Everett approved these changes
Thank you Shane, this looks perfect now. 

Once this is merged in and then merged into Oscar's rename branch I can once over again with the newest Access Level Admin function names

2024-01-30 15:56 UTC, mpetersoCode55 approved these changes
Looks great!

2024-01-30 15:56 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        applicationAppManager.addRuleAdministrator(vm.envAddress("QUORRA"));
I had also fixed this in my branch, glad I'm not crazy (insert laughing emoji)

2024-01-30 15:57 UTC, merged