SE-471. Create Deployment Tests and Github Actions.
thrackle-io/forte-rules-engine-v1 pull request #258
Opened 2024-01-31 20:11 UTC by mpetersoCode55

1. Added scripts to parse output and update env file after deploying the protocol and application.
2. Added verification checks into the Application deployment script.
3. Added tests to verify an application deployment against an actual chain and test setup
4. Fixed issues with Protocol Deployment tests when run against actual chain
5. Setup a Github worflow to run all of the above and: a. on success kick off the k8s workflow b. on failure send an email notification to the team.

2024-01-31 21:29 UTC, bfcoursewool commented on Dockerfile.anvil
> +ENTRYPOINT anvil --host 0.0.0.0 --chain-id $CHAIN_ID --code-size-limit 30000
So I just checked and in the necessist branch I set code-size-limit to 45000, and I put those values in foundry.toml... I'm not hugely attached to any particular approach to this setting, either where we set it, or what value we set it to, as long as it works, but I guess I do think we should just do it in one or the other place.

2024-01-31 21:30 UTC, bfcoursewool commented on Dockerfile.deploymentCheck
> +
Dang, this dockerfile looks like it was made by a real DevOps guy...

2024-01-31 21:33 UTC, bfcoursewool commented on docker-compose.yml
> +      dockerfile: Dockerfile.deploymentCheck
This probably doesn't make much difference since I think nobody actually uses this docker-compose file for anything in the tron dev process, but maybe it's worth pointing out in like a comment or something that this is using the "deploy check" tron container, rather than the "real" one that actually just deploys tron. I think in theory if someone did build this docker-compose stack on their machine, then it would actually go run the tests and potentially even actually kick off the k8s workflow in GH and stuff, which may not be ideal.

2024-01-31 21:35 UTC, bfcoursewool commented on script/ParseApplicationDeploy.sh
> +
The bash-fu is strong with this one.

2024-01-31 21:38 UTC, bfcoursewool approved these changes
Looks great to me!

2024-01-31 21:47 UTC, mpetersoCode55 commented on Dockerfile.anvil
> +ENTRYPOINT anvil --host 0.0.0.0 --chain-id $CHAIN_ID --code-size-limit 30000
Good catch, yeah I prefer the foundry.toml approach, seems cleaner to keep it all in one location. I'll update accordingly

2024-01-31 21:47 UTC, mpetersoCode55 commented on Dockerfile.deploymentCheck
> +
Don't you put that evil on me

2024-01-31 21:50 UTC, mpetersoCode55 commented on docker-compose.yml
> +      dockerfile: Dockerfile.deploymentCheck
Yeah I agree, the better we document the flow and purpose the less pain future us will have to endure. Not no pain, just less

2024-02-01 01:17 UTC, bfcoursewool commented on Dockerfile.anvil
> +ENTRYPOINT anvil --host 0.0.0.0 --chain-id $CHAIN_ID --code-size-limit 30000
@mpetersoCode55 -- ah, so actually we might need to go with the command line parameter approach... I've been messing with tron over here today for the rules rename stuff and discovered that something isn't working with the code-size-limit value that's getting set in foundry.toml... I suppose we could continue to experiment and figure out why it isn't working there and how to make it work there, but I'm lazy and it definitely works the way you have it here in this branch so I'm inclined to just go with that for right now...

2024-02-01 02:48 UTC, oscarsernarosero requested changes
Looks really good and thorough Michael. I just have some minor suggestions.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Nice. We should also check for the appManager having connected its handler.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // Checking to make sure AppManager is deployed
I would just change these comments to something more accurate like `// Checking XXX-contract environment variable has been set` since that is what we are actually checking here. We will know for sure if the contract has been deployed when we call functions on that address and we get our expected results like you do in the next steps.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Maybe call a public function in this address and test that it returns what it should to make sure the contract lives in that address.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +    function verifyERC20(bool isCoin1) public view {
nice. I like the flag.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Same here. Try calling a public function and check its returned data.

2024-02-01 02:48 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +            revert("ERC20 Handlers owner should be the Frankenstein Coin");
Is this error message accurate?

2024-02-01 02:48 UTC, oscarsernarosero commented on test/client/application/deployment/ApplicationDeployment.t.sol
> +            applicationAppManager = ApplicationAppManager(payable(vm.envAddress("TEST_DEPLOY_APPLICATION_APP_MANAGER")));
why do we need the `payable` attribute for this address argument?

2024-02-01 13:48 UTC, mpetersoCode55 commented on Dockerfile.anvil
> +ENTRYPOINT anvil --host 0.0.0.0 --chain-id $CHAIN_ID --code-size-limit 30000
Ok let's go with the command line parameter approach for now then. I think we just want something that we know works for now since it's going to be removed once we finish the handler refactor anyways (so we don't have false positives moving forward. I'll remove it from foundry.toml and we can just rely on what I'm passing into anvil, in the anvil container

2024-02-01 13:52 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Resolved

2024-02-01 13:59 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +            revert("ERC20 Handlers owner should be the Frankenstein Coin");
Resolved

2024-02-01 14:03 UTC, mpetersoCode55 commented on test/client/application/deployment/ApplicationDeployment.t.sol
> +            applicationAppManager = ApplicationAppManager(payable(vm.envAddress("TEST_DEPLOY_APPLICATION_APP_MANAGER")));
Good catch! Resolved

2024-02-01 14:12 UTC, ShaneDuncan602 commented on script/ParseApplicationDeploy.sh
> +if [[ $os == *"Darwin"* ]]; then
It's sad we have to do this.

2024-02-01 14:17 UTC, ShaneDuncan602 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // Checking to make sure AppManager is deployed
I agree. Verify usually refers to verifying the contract for block explorers.

2024-02-01 14:22 UTC, ShaneDuncan602 commented on script/clientScripts/ApplicationDeployAll.s.sol
Is DOOM the only place we use this script? Since we are already maintaining the Application_Deploy_01 through 08 maybe we should abandon this altogether and use those instead. This might be too much scope creep for this ticket but those other scripts didn't exist at the time of ticket creation so I think we should consider it as long as the ApplicationDeployAll and all the mini scripts do the same thing.

2024-02-01 14:29 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Resolved

2024-02-01 14:29 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        }
Resolved

2024-02-01 14:29 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // Checking to make sure AppManager is deployed
Resolved

2024-02-01 14:34 UTC, mpetersoCode55 commented on docker-compose.yml
> +      dockerfile: Dockerfile.deploymentCheck
Resolved.

2024-02-01 15:03 UTC, mpetersoCode55 commented on script/clientScripts/ApplicationDeployAll.s.sol
(Resolution pulled from Slack conversation)
I agree that retiring the DeployAll script is a good call. I think we should have a dedicated effort though. I'd want to also remove the DeployAllModules script and update the repo to make sure every reference to either is replaced with the relevant broken up scripts. (I think we have a pretty decent mix of the two approaches throughout the repo right now so I'd vote for a dedicated ticket)

2024-02-01 15:25 UTC, ShaneDuncan602 approved these changes
Good job. Adding a new ticket to retire the ApplicationDeployAll ticket.

2024-02-01 15:30 UTC, TJ-Everett approved these changes
Awesome job on this one!

2024-02-01 15:30 UTC, merged