Se 546 create documentation for the protocol processor
thrackle-io/forte-rules-engine-v1 pull request #265
Opened 2024-02-06 16:22 UTC by TJ-Everett

2024-02-06 18:09 UTC, mpetersoCode55 approved these changes

2024-02-06 18:09 UTC, mpetersoCode55 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-DIAMOND.md
> +The diamond pattern allows the protocol to upgrade, add new features and improvements through the use of a proxy contract. New facet contracts can be deployed and connected to the diamond via a speci
Is it worth having separate subsections to define our Rule Processor Diamonds Purpose and the overall design or Diamond contracts themselves?

2024-02-06 18:09 UTC, mpetersoCode55 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-DIAMOND.md
> +The Rule Processor diamond architecture consists of the Rule Processor Diamond, [Rule Processor Diamond Libraries](./RULE-PROCESSOR-LIBRARIES.md) and supporting [Rule Processor Facets](./RULE-PROCESS
Could we reword the last sentence to something more like:
The facet contracts fall into two categories: Storage Contracts and Processor Contracts. Storage contracts contain the data associated with a specific rule and the corresponding Processor contract contains the functions used to validate transactions relevant to the rule on chain.

2024-02-06 18:09 UTC, mpetersoCode55 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-DIAMOND.md
> +The Rule Processor Diamond contains one primary function, the fallback function. This will find the function selector being passed to the diamond by a calling contract. When a valid function selector
Is it worth expanding this to explicitly say that the diamond contract is checking the facets that have been associated with it to find the function selector?

2024-02-06 18:09 UTC, mpetersoCode55 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-FACETS.md
> +- The new facet that is to be added to the diamond should first be deployed to the network the Rule Processor Diamond is deployed too.
to*

2024-02-06 18:09 UTC, mpetersoCode55 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-LIBRARIES.md
> +The importance of using these singular library contracts prevents data storage collision as functionality is added or removed from the protocol. Facets should always be removed through the diamond cu
I would get rid of "The importance of" and just say:
"Using these singular library contracts prevents data storage collision as functionality is added or removed from the protocol."

2024-02-07 15:11 UTC, ShaneDuncan602 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-DIAMOND.md
> +
I don't think we should include this information. The Diamond design was adopted directly from the EIP docs. I think we should just add something like, "For additional information on Diamond storage, usage, and design, see ERC2535". Probably need a sign off from @jjbailey-io though.

2024-02-07 15:13 UTC, ShaneDuncan602 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-FACETS.md
> +        - data: A function call, including function selector and arguments calldata is executed with delegatecall on "init"
We should add a TODO in here for the upcoming facet upgrade scripts ticket and link that ticket to this one.

2024-02-07 15:14 UTC, ShaneDuncan602 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-LIBRARIES.md
> +```
I think this would be another opportunity where we could just reference the ERC and not have to include actual code.

2024-02-07 15:14 UTC, ShaneDuncan602 commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-LIBRARIES.md
> +}
Love this

2024-02-07 15:15 UTC, ShaneDuncan602 requested changes
Just some minor suggestions and a decision for @jjbailey-io

2024-02-07 15:25 UTC, jjbailey-io commented on docs/userGuides/ruleProcessor/RULE-PROCESSOR-DIAMOND.md
> +
I'm good with referencing industry standards for canned information. My only caveat is we should be explicit if we're expecting it to be managed a specific way when there are multiple ways to manage it.

2024-02-07 17:25 UTC, ShaneDuncan602 approved these changes
Awesome!

2024-02-07 17:25 UTC, merged