SE-496-Create-Invariants-for-Client-Pricing
thrackle-io/forte-rules-engine-v1 pull request #267
Opened 2024-02-08 18:13 UTC by ShaneDuncan602

2024-02-09 17:46 UTC, oscarsernarosero requested changes
This is very good. I just have a couple things to reconsider.

2024-02-09 17:46 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/Pricing-Invariants.md
> +- Trying to set a price for non ERC721 compliant collection always reverts with NotAnNFTContract
maybe better to say NFT - collection instead of contracts - collection?

2024-02-09 17:46 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/Pricing-Invariants.md
> +- When no specific tokenId price is set and a collection price is set, it always retrieves the collection price.
you don't really need a collection price set. It would just retrieve 0 in that case, but that is still the collection price being retrieved. If we keep the statement as is, then the question: what happens when the collection price is not set? will naturally come up.

2024-02-09 17:46 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/Pricing-Invariants.md
> +- When a specific tokenId prices are set and a collection price is set, it always returns the specific tokenId's price when present.
I would just remove the last "when present".

2024-02-09 18:38 UTC, TJ-Everett approved these changes
Looks good!

2024-02-12 16:05 UTC, mpetersoCode55 approved these changes
Looks great!

2024-02-13 15:53 UTC, merged