Se 548 create documentation for access level0 after rename is finalized
thrackle-io/forte-rules-engine-v1 pull request #269
Opened 2024-02-09 22:47 UTC by TJ-Everett

2024-02-12 14:49 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-DENY-FOR-NO-ACCESS-LEVEL.md
> +The purpose of this rule is to provide a way to prevent the transfer of assets without application verification. For example, the application may decide users may not accumulate or transfer any asset
I think this first sentence should probably just refer to the Access Level itself: "without application verification" to "for accounts that do not have an access level or whose access level has been set to 0"

2024-02-12 14:59 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-DENY-FOR-NO-ACCESS-LEVEL.md
> +- This rule doesn't apply when the *to* address is the zero address to allow for burning while rule is active.
This is getting changed. We will be removing that burn check from the handler. The rule will not be applicable to a burn. It's in [ticket](https://thracklelabs.atlassian.net/browse/SE-565). Not sure how we should handle this. We could change it here or add something to the ticket to change it. Personally, I think we should go ahead and change it so it doesn't get missed.

2024-02-12 15:01 UTC, ShaneDuncan602 commented on docs/userGuides/rules/README.md
> +| [Account Deny For No Access Level](./ACCOUNT-DENY-FOR-NO-ACCESS-LEVEL.md) | The purpose of this rule is to provide a way to prevent the transfer of assets without application verification. For exam
See above

2024-02-12 15:02 UTC, ShaneDuncan602 requested changes
Couple of itty bitty things

2024-02-12 22:40 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-DENY-FOR-NO-ACCESS-LEVEL.md
> +- This rule doesn't apply when the *to* address is the zero address to allow for burning while rule is active.
Agreed changing here and leaving a note to ensure the docs match after that ticket is complete.

2024-02-13 15:58 UTC, ShaneDuncan602 approved these changes
Perfect!

2024-02-13 15:58 UTC, merged