SE-497-Create-Invariants-for-Client-Token
thrackle-io/forte-rules-engine-v1 pull request #270
Opened 2024-02-13 15:49 UTC by ShaneDuncan602

2024-02-13 17:09 UTC, TJ-Everett approved these changes
Approving this as it looks great! 

Question: Should we have invariants for the DiamondCut function for the handlers? This should be RBAC'ed and that should have at least one invariant per handler that only that role can call the function.

2024-02-14 02:44 UTC, oscarsernarosero requested changes
This was a lot of work. Very deep and thorough job, in general. I just have a couple suggestions.

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/ERC20/ProtocolERC20-invariants.md
> +- Handler address can never be zero address
it technically can be zero. I guess the invariant would be that if it is zero, then any transfer will always fail.

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/ERC20/ProtocolERC20-invariants.md
> +- The sum of users balances should not be greater than the token's total supply.
...or less

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/ERC721/ProtocolERC721-invariants.md
> +- Handler address can never be zero address
same as above

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/ERC721/upgradeable/ProtocolERC721U-invariants.md
> +- Version will never change.
are these true for an upgradeable contract?

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/data/Fees-invariants.md
> +- When adding a fee, fee percentage can never be greater than 10000 or less than -10000
should we write in parenthesis (100%) and (-100%)

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/handler/Fees-invariants.md
> +- Version will never change.
I don't think we can have a version at the facet level since that would mean a function collision at the diamond level. I think we can have a version at the diamond level only.

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/handler/Fees-invariants.md
> +- Any user can get the contract's version
same for this

2024-02-14 02:44 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/client/token/handler/common/Fees-invariants.md
> +- When mint, deterineTransferAction always returns ActionTypes.MINT
`deterine`* 'determine'

2024-02-21 20:55 UTC, ShaneDuncan602 commented on docs/userGuides/development/invariants/client/token/ERC721/upgradeable/ProtocolERC721U-invariants.md
> +- Version will never change.
I think this will still be true, but I'll add the delimiter

2024-02-22 16:31 UTC, oscarsernarosero approved these changes
Great job Shane

2024-02-22 19:31 UTC, merged