Added invariants for each of the contracts in the client/application directory
thrackle-io/forte-rules-engine-v1 pull request #271
Opened 2024-02-13 16:09 UTC by mpetersoCode55

Added invariants for each of the contracts in the client/application directory

2024-02-13 17:55 UTC, TJ-Everett commented on docs/userGuides/development/invariants/client/application/AppManager-Invariants.md
> +
I think we should have the event emission for each of the data contract functions.

2024-02-13 18:14 UTC, TJ-Everett commented on docs/userGuides/development/invariants/client/application/ProtocolApplicationHandler-Invariants.md
> +
In Shane's current invariant ticket he has this: 
When AccountMinMaxTokenBalance is active, violation of the rule is reverted.
- When AccountMaxBuySize is active, violation of the rule is reverted. 
- When TokenMaxBuyVolume is active, violation of the rule is reverted. 
- When AccountMaxSellSize is active, violation of the rule is reverted. 
- When TokenMaxSellVolume is active, violation of the rule is reverted. 

see: https://github.com/thrackle-io/tron/pull/270/files#diff-6b0e19a2db0415a3e097542eb1f12cbab623dd0409528bb6e9e1a7cfc32ec47b

I think this is necessary here too for the app level rules

2024-02-13 18:15 UTC, TJ-Everett requested changes
Great work over all TDMike! Just a quick couple things about event emission and the rules reverting (example given).

2024-02-13 20:18 UTC, mpetersoCode55 commented on docs/userGuides/development/invariants/client/application/ProtocolApplicationHandler-Invariants.md
> +
Good catch! I shall make it so

2024-02-13 20:19 UTC, mpetersoCode55 commented on docs/userGuides/development/invariants/client/application/AppManager-Invariants.md
> +
That's embarrassing, I can't believe I missed those. On it!

2024-02-13 21:16 UTC, mpetersoCode55 commented on docs/userGuides/development/invariants/client/application/ProtocolApplicationHandler-Invariants.md
> +
Resolved

2024-02-13 21:27 UTC, mpetersoCode55 commented on docs/userGuides/development/invariants/client/application/AppManager-Invariants.md
> +
Resolved

2024-02-13 21:35 UTC, TJ-Everett approved these changes
Looks great! Approved

2024-02-20 16:14 UTC, ShaneDuncan602 approved these changes
This looks great. Tayler already found all the good stuff!

2024-02-21 12:44 UTC, merged