Se 538 token handlers to diamonds
thrackle-io/forte-rules-engine-v1 pull request #273
Opened 2024-02-14 04:23 UTC by oscarsernarosero

2024-02-14 19:22 UTC, TJ-Everett commented on src/client/token/ERC20/ProtocolERC20.sol
> +            (targetAccounts, feePercentages) = FeesFacet(address(handler)).getApplicableFees(owner, balanceOf(owner));
Does having the facet here instead of calling through the interface create any future upgrading issues? For example if the token is deployed and the application updates the FeesFacet to V2 and redeploys, will the token still call the old facet here? Should we instead call the proxy through an interface? Maybe a better Q is should we avoid hard coding facets where we can?

2024-02-14 19:22 UTC, TJ-Everett commented on src/client/token/ERC20/ProtocolERC20.sol
> +            (targetAccounts, feePercentages) = FeesFacet(address(handler)).getApplicableFees(from, balanceOf(from));
same Q here.

2024-02-14 19:28 UTC, TJ-Everett commented on src/client/token/handler/common/DataStructures.sol
> + * @title Handly Type Enum
Handler types*

2024-02-14 19:32 UTC, TJ-Everett commented on src/client/token/handler/common/HandlerUtils.sol
> +     * @return action intended in the transfer
This function comment block is old, the new one is:
    /**
     * @dev determines if a transfer is:
     *          p2p transfer 
     *          buy
     *          sell
     *          mint
     *          burn
     * @notice p2p transfer is position 0 and will be default unless other conditions are met. 
     * @param _from the address where the tokens are being moved from
     * @param _to the address where the tokens are going to
     * @param _sender the address triggering the transaction
     * @return action intended in the transfer
     */
     
     This way the enums are in the right order and adds a little context to the function

2024-02-14 19:34 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20HandlerMainFacet.sol
> +     * @dev Constructor sets params
This should say initializer sets params

2024-02-14 19:35 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20HandlerMainFacet.sol
> +        // // All transfers to treasury account are allowed
double //

2024-02-14 19:41 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20TaggedRuleFacet.sol
> +            // TradingRuleFacet(address(this)).checkTradingRules(_from, _to, fromTags, toTags, _amount, action);
can we remove this line?

2024-02-14 19:45 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721HandlerMainFacet.sol
> +     * @dev Constructor sets params
Initializer instead of constructor

2024-02-14 19:46 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +     * @dev This function uses the protocol's ruleProcessorto perform the actual  rule checks.
rule processor to - missing a space

2024-02-14 19:54 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721TaggedRuleFacet.sol
> +            // TradingRuleFacet(address(this)).checkTradingRules(_from, _to, fromTags, toTags, _amount, action);
Can we remove this line too?

2024-02-14 20:00 UTC, TJ-Everett commented on src/client/token/handler/diamond/StorageLib.sol
> +     */
Line 87 and line 98 both say Account Max Buy/Sell but the rule name is TokenMax Buy/Sell

2024-02-14 20:00 UTC, TJ-Everett commented on src/client/token/handler/diamond/StorageLib.sol
> +     * @dev Function to store Token Min Hold Time
NFT valuation Limit Storage

2024-02-14 20:01 UTC, TJ-Everett commented on src/client/token/handler/diamond/StorageLib.sol
> +    // }
We should either uncomment these or remove so we don't have them in for the audit if we are not using

2024-02-14 20:17 UTC, mpetersoCode55 commented
We do need to go through and remove --code-size-limit qualifier anywhere it exists in the repo. I verified that it's at least still in Dockerfile.anvil

2024-02-14 20:18 UTC, TJ-Everett commented on src/client/token/handler/diamond/TradingRuleFacet.sol
> +
I think we still need a consolidated import for all these. Or at least as many as we can to reduce repetition across the facets

2024-02-14 20:19 UTC, mpetersoCode55 requested changes
Just a couple of small things, overall this looks great. Massive undertaking, great work Oscar

2024-02-14 20:19 UTC, mpetersoCode55 commented on src/example/ERC20/ApplicationERC20Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
This should be removed, right?

2024-02-14 20:19 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
This should be removed, right?

2024-02-14 20:19 UTC, mpetersoCode55 commented on test/util/TestCommonFoundry.sol
> +    function deployAndSetupERC721(string memory name, string memory symbol) internal returns(ApplicationERC721 erc721, HandlerDiamond handler) {
So we essentially have duplicates of these with: setupApplicationCoinAndHandler and setupApplicationNFTAndHandler. I think we should get rid of one of the other and update all references to point to the ones we keep (I don't really have a preference on which, I think the ones you added here are more modular/better designed but if swapping to them is a lot of work we could just get rid of these and use the existing ones then refactor those when we get to some of the test refactoring tickets).

2024-02-14 21:10 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountMaxSellSize.sol
> + * @title Handler Account Max Buy Size
Handler Account Max Sell Size

2024-02-14 21:11 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountMaxSellSize.sol
> +     * @dev Set the AccountMaxBuySizeRuleId. Restricted to rule administrators only.
MaxSellRuleId

2024-02-14 21:11 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountMaxSellSize.sol
> +     * @dev Retrieve the Account Max Buy Size Rule Id
Sell

2024-02-14 21:11 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountMaxSellSize.sol
> +     */
Sell

2024-02-14 21:11 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountMaxSellSize.sol
> +     * @dev Tells you if the Account Max Buy Size Rule is active or not.
Sell

2024-02-14 21:14 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerBase.sol
> + * @title Protocol Handler Common
Protocol Handler Base

2024-02-14 21:16 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSellVolume.sol
> +     * @dev Retrieve the Account Max Buy Size Rule Id
Sell

2024-02-14 21:16 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSellVolume.sol
> + * @title Handler Account Max Buy Size
Sell

2024-02-14 21:16 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSellVolume.sol
> +     * @dev Tells you if the Account Max Buy Size Rule is active or not.
Sell

2024-02-14 21:22 UTC, TJ-Everett commented on src/common/IEvents.sol
>      event HandlerConnected(address indexed handlerAddress, address indexed assetAddress); // ...in favor of this one since regular deploy and upgrade now looks the same?
can we remove the comment from in code and pop it into the event [ticket](https://thracklelabs.atlassian.net/browse/SE-493)?

2024-02-14 21:30 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/ERC20TaggedRuleProcessorFacet.sol
> +        if(amount > currentBalance) revert("amount more tha current balance");
Should this be a custom error reversion? If no, Than is misspelled.

2024-02-14 21:31 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/RuleProcessorDiamond.sol
> +        if (facet.code.length == 0) revert FacetHasNoCodeOrHasBeenDestroyed();
perfect!

2024-02-14 21:35 UTC, TJ-Everett commented on test/client/application/integration/ApplicationAppManager.t.sol
> +    HandlerDiamond applicationCoinHandlerC;
Can all of these be in the testCommon or TestCommonFoundry files?

2024-02-14 21:36 UTC, TJ-Everett commented on test/client/application/integration/ApplicationAppManager.t.sol
> +
We have to move these to the common files - it undoes the goal of having the set ups be as small as possible.

2024-02-14 21:37 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        applicationAppManager.registerToken("DRAC", address(draculaCoin));
Same here- these should drop into the common files

2024-02-14 21:57 UTC, TJ-Everett commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
Can we remove this whole file now? Since we have the DiamondHandler.t.sol?

2024-02-14 22:00 UTC, TJ-Everett commented on test/util/ApplicationAssetHandlerMod.sol
> +// }
Seems like we can remove this file too?

2024-02-14 22:00 UTC, TJ-Everett commented on test/util/ApplicationERC721HandlerMod.sol
> +// }
Same with this one?

2024-02-14 22:01 UTC, TJ-Everett requested changes
Holy smokes this is a big one. GREAT work on this Oscar. I have a few requested changes and some questions.

2024-02-14 22:09 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20.sol
> +            (targetAccounts, feePercentages) = FeesFacet(address(handler)).getApplicableFees(owner, balanceOf(owner));
It is essentially the same to have the facet wrapper or the interface. All Solidity does is to grab the function signature to build the calldata correctly (including the function selector). So it won't matter basically. The diamond will know what facet to call because it has a list of function selectors attached to contract addresses. So as long as we do upgrades correctly, it shouldn't bring any type of upgrading issues.

2024-02-14 22:09 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20.sol
> +            (targetAccounts, feePercentages) = FeesFacet(address(handler)).getApplicableFees(from, balanceOf(from));
same

2024-02-14 22:13 UTC, TJ-Everett commented on src/client/token/ERC20/ProtocolERC20.sol
> +            (targetAccounts, feePercentages) = FeesFacet(address(handler)).getApplicableFees(owner, balanceOf(owner));
Okay great! Thanks @oscarsernarosero

2024-02-14 22:33 UTC, oscarsernarosero commented on src/client/token/handler/diamond/StorageLib.sol
> +     */
nice catch

2024-02-14 22:43 UTC, oscarsernarosero commented on src/client/token/handler/diamond/StorageLib.sol
> +    // }
for sure. Removed.

2024-02-14 22:44 UTC, oscarsernarosero commented on src/client/token/handler/diamond/TradingRuleFacet.sol
> +
good call. I thought about it but didn't actually do it.

2024-02-15 02:08 UTC, oscarsernarosero commented on src/example/ERC20/ApplicationERC20Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
not really. That's the license we are using. We might want to review this, but  not removing it.

2024-02-15 02:16 UTC, oscarsernarosero commented on src/common/IEvents.sol
>      event HandlerConnected(address indexed handlerAddress, address indexed assetAddress); // ...in favor of this one since regular deploy and upgrade now looks the same?
fo sho

2024-02-15 02:26 UTC, oscarsernarosero commented on test/client/application/integration/ApplicationAppManager.t.sol
> +    HandlerDiamond applicationCoinHandlerC;
Im not sure I agree. The testCommon and TestCommonFoundry should contain common variables and functions for all tests. The more localized a "common" function or variable is, the deeper in the directory it should be. So we should have a common directory inside client, another inside token, and another in application and so on. For this particular case, I would say, this is very localized in this specific test so it shouldn't go into a common contract.

2024-02-15 14:41 UTC, mpetersoCode55 commented on src/example/ERC20/ApplicationERC20Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
I mean the file, it's all commented out

2024-02-15 14:42 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
also talking about the file here

2024-02-15 16:42 UTC, oscarsernarosero commented on test/util/TestCommonFoundry.sol
> +    function deployAndSetupERC721(string memory name, string memory symbol) internal returns(ApplicationERC721 erc721, HandlerDiamond handler) {
I totally agree with you here Michael, but there are some testing tickets coming, so I would say let's do this here. Im trying to get this merge so we can unlock the other tickets.

2024-02-15 16:42 UTC, oscarsernarosero commented on src/example/ERC721/ApplicationERC721Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
gotcha

2024-02-15 17:26 UTC, oscarsernarosero commented on src/example/ERC721/ApplicationERC721Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
I kept this one since this is a separate test. I did remove `ApplicationERC721HandlerDiamond.t.sol` and `ApplicationERC20DiamondHandler.t.sol` since we already have the original ones with the diamonds.

2024-02-15 17:27 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
I kept this one since this is the original one now working with the diamonds, and I removed `ApplicationERC721HandlerDiamond.t.sol` and `ApplicationERC20DiamondHandler.t.sol` instead since those were temporary.

2024-02-15 19:14 UTC, ShaneDuncan602 commented on docs/userGuides/images/ProtocolOverview.png
I think we need to differentiate the handler facets from the pricing contract. It's hard to tell that the pricing contract is not part of the diamond. Not sure the best way to do that. Maybe moving the Pricing contract to the other side. Also might be able to add "invokes" to the array

2024-02-15 19:16 UTC, ShaneDuncan602 commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // verifyERC721();
We can't keep these verification functions?

2024-02-15 19:29 UTC, ShaneDuncan602 commented on src/example/ERC20/ApplicationERC20Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
Yeah, we should remove this

2024-02-15 19:31 UTC, ShaneDuncan602 commented on src/example/ERC721/ApplicationERC721Handler.sol
>  // SPDX-License-Identifier: UNLICENSED
I think it should be removed as well.

2024-02-15 19:38 UTC, ShaneDuncan602 commented on test/client/application/integration/ApplicationAppManager.t.sol
> +
I agree. In order to maintain the common pattern. These should use deployAndSetupERC20 or setupApplicationCoinAndHandler(whichever function survives the PR) style create functions.

2024-02-15 19:40 UTC, ShaneDuncan602 requested changes
Just some minor questions and concerns. I'm reall proud of everyone for this.

2024-02-15 22:15 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // verifyERC721();
It looks like I can. @mpetersoCode55 is it ok if I turn this back on?

2024-02-15 22:18 UTC, oscarsernarosero commented on script/clientScripts/ApplicationDeployAll.s.sol
> +        // verifyERC721();
I'm going to fix the functions to use the handler facets. I think that was the reason to comment this out. Great catch Shane

2024-02-16 16:01 UTC, ShaneDuncan602 requested changes
I think we still need to remove ApplicationERC20Handler and ApplicationERC721Handler. Also, to move the _createERC20HandlerDiamond() calls in ApplicationAppManager.t.sol to deployAndSetupERC20 or setupApplicationCoinAndHandler(whichever function survives the PR) style create functions in the TestCommonFoundry.

2024-02-16 22:44 UTC, TJ-Everett commented on src/client/token/handler/diamond/HandlerDiamond.sol
> +        DiamondLib.diamondCut(diamondCut, args.init, args.initCalldata);
I added to the Event harding ticket too come in and make sure each diamond fires a Diamond<type>Deployed event. This comment is for everyones FYI

2024-02-16 22:45 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
> +    uint8 constant LAST_POSSIBLE_ACTION = uint8(ActionTypes.P2P_TRANSFER);
This should be ActionTypes.BURN as P2P_TRANSFER is now the first action type in the enum

2024-02-16 22:46 UTC, TJ-Everett approved these changes
Just a comment for awareness and a small update in one facet. Approved for me. GREAT WORK sir.

2024-02-20 16:19 UTC, ShaneDuncan602 commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
> +    uint8 constant LAST_POSSIBLE_ACTION = uint8(ActionTypes.P2P_TRANSFER);
Great catch

2024-02-20 19:01 UTC, ShaneDuncan602 approved these changes
Think we got it

2024-02-20 19:28 UTC, merged