Se 544 create documentation for handlers
thrackle-io/forte-rules-engine-v1 pull request #277
Opened 2024-02-20 21:18 UTC by TJ-Everett

App Handler md
Asset Handler Diamond mds

2024-02-21 14:11 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/Application/APP-HANDLER.md
> +# App Handler
I think we should use the full name on titles and in the descriptions. Application Handler sounds fancy.

2024-02-21 14:13 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/Application/APP-HANDLER.md
> +The App Handler facilitates the rule checks for each application level rule. The first function called by the App Manager is:
Can we define what an Application Level Rule is here?

2024-02-21 14:20 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/Application/APP-HANDLER.md
> +This function allows the App Manager to know if any application level rules are active and if the call should continue to the handler to check the active rules.
Since there isn't a specific function for pause rules, I think we should mention it checking them.

2024-02-21 14:23 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND-FACET-LIST.md
> +- [FeesFacet.sol](../../../../../src/client/token/handler/diamond/FeesFacet.sol)
It's tough to say whether this is a rule facet or a data facet. I tend to think of it as a data facet since it stores the fees per asset. I'm good either way though.

2024-02-21 14:23 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +The Protocol Asset Handler Diamond serves as the access point  to the protocol for a protocol supported asset. The protocol supported asset accepts the Handler Diamond proxy address and calls the che
double space between point and to

"The protocol supported asset accepts the Handler Diamond proxy address and calls the check all rules function." Can we change this to "The protocol supported asset stores the Handler Diamond proxy address and uses it to call the check all rules function."

2024-02-21 14:29 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +Each Protocol supported asset type (ERC20, ERC721, etc) will need a handler diamond deployed and connected to the asset. The Handler diamond architecture will remain the same for each asset type. The
"will need a handler diamond " to "will need one handler diamond "

"The proxy contract, libraries and storage facets may be the same for different asset handler diamonds." I'm a little confused by this statement. We might want to say that they share the same code, but they will never share the same deployed facets.

2024-02-21 14:48 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +[Protocol NonFungible Handler](./PROTOCOL-NONFUNGIBLE-TOKEN-HANDLER.md)
Are we getting away from the 20 and 721 labels?

2024-02-21 14:57 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +The diamond pattern allows the handler to upgrade, add new features and improvements through the use of a proxy contract. New facet contracts can be deployed and connected to the diamond via a specia
overtime should be two words

2024-02-21 15:02 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-FUNGIBLE-TOKEN-HANDLER.md
> +- The new facet that is to be added to the diamond should first be deployed to the network the Asset Handler Diamond is deployed to.
"to the network the Asset Handler Diamond" should be "to the same network the Asset Handler Diamond"

2024-02-21 15:04 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-NONFUNGIBLE-TOKEN-HANDLER.md
> +- The new facet that is to be added to the diamond should first be deployed to the network the Asset Handler Diamond is deployed to.
"to the network the Asset Handler Diamond" to "to the same network the Asset Handler Diamond"

2024-02-21 15:05 UTC, ShaneDuncan602 requested changes
Solid work here, Tayler. I have a few minor suggestions but this is really good.

2024-02-21 17:09 UTC, oscarsernarosero requested changes
This is an amazing job Tayler. Very minor suggestions.

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/Application/APP-HANDLER.md
> +# App Handler
I second that

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/Application/APP-HANDLER.md
> +The App Handler supports the App Manager by storing the application level rules data and functions. Procotol supported asset handler contracts call check application level rules via the App Manager.
`check application level rules` this can sound very confusing to the person not familiar with the code. So I think we have a couple options here:
`check-application-level-rules function` or `checkApplicationLevelRules`. If the latter is preferred, I would even do the code single quote so it is clear that it is a function

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND-FACET-LIST.md
> +- [FeesFacet.sol](../../../../../src/client/token/handler/diamond/FeesFacet.sol)
Yeah. I think it is merged since in other rules we have the data in a contract and the activation flag in the handler, but not in this case. They all live in the same place, so I would say, for simplicity, it is a good idea to treat it as a rule in general.

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +The Protocol Asset Handler Diamond serves as the access point  to the protocol for a protocol supported asset. The protocol supported asset accepts the Handler Diamond proxy address and calls the che
same as above about `check all rules`

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +Asset level rules are set by [Rule administrators](../permissions/ADMIN-ROLES.md). The protocol supplied rule id for each [Rule](../../../rules/README.md) is stored with an active status boolean insi
I wouldn't go as deep as to mention the data structure types. If we want to show the data structures we can do that with a code block. I would just mention at a high level how the rules are stored as you have already done here.

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +Each Protocol supported asset type (ERC20, ERC721, etc) will need a handler diamond deployed and connected to the asset. The Handler diamond architecture will remain the same for each asset type. The
They could tho. In theory, you just need to deploy a different proxy contract that points to the same facets as another handler diamond, and you have the exact same behavior without the cost of deploying the facets.

2024-02-21 17:09 UTC, oscarsernarosero commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +Each Protocol supported asset type (ERC20, ERC721, etc) will need a handler diamond deployed and connected to the asset. The Handler diamond architecture will remain the same for each asset type. The
That might actually be a good guideline for devs since that way they save money on deployments and upgrades

2024-02-21 19:53 UTC, TJ-Everett commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +[Protocol NonFungible Handler](./PROTOCOL-NONFUNGIBLE-TOKEN-HANDLER.md)
Yeah that was something we had talked about ages ago to try and keep parity with Zelda and then also limit cognitive requirements for non tron devs reading through docs.

2024-02-21 22:02 UTC, mpetersoCode55 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +[Protocol NonFungible Handler](./PROTOCOL-NONFUNGIBLE-TOKEN-HANDLER.md)
parity with who?

2024-02-21 22:03 UTC, mpetersoCode55 approved these changes
Looks great Tayler! I don't see anything else outside of what the guys already pointed out

2024-02-22 00:16 UTC, oscarsernarosero approved these changes
Looks good.

2024-02-22 14:36 UTC, ShaneDuncan602 approved these changes
Great job.

2024-02-22 15:26 UTC, merged