Fixed High, Medium and Low severity Slither findings.
thrackle-io/forte-rules-engine-v1 pull request #279
Opened 2024-02-21 21:29 UTC by mpetersoCode55

2024-02-22 15:48 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +
Do we still want to have the if () switch in this to bypass the check when there are no oracle rules active?

2024-02-22 15:49 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +        IRuleProcessor(handlerBaseStorage.ruleProcessor).checkAccountApproveDenyOracles(accountApproveDenyOracle[action], _to);
Same question: Should we keep the if() switch?

2024-02-22 15:51 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerAccountApproveDenyOracle.sol
> +            Rule memory newOracleRule = Rule(_ruleId, true);
This is clean!

2024-02-22 16:07 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/AppRuleDataFacet.sol
> +        emit ProtocolRuleCreated(ACC_MAX_VALUE_BY_ACCESS_LEVEL, index, new bytes32[](0));
Nice! I have a feeling ToB will like this version way more.

2024-02-22 16:16 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            if ((_volume * _VOLUME_MULTIPLIER) / _supply >= uint(rule.max) * 10000) {
Should we do the same for the basis points magic number? Since we are already here fixing magic numbers?

2024-02-22 16:16 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
>              if (uint256(volatility) > uint(rule.max) * 10000) {
Here too if we change this to be not a magic number.

2024-02-22 16:19 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
I know it is not a slither finding BUT can we make this a loop for 6 mints instead of all the lines? We try to catch these as they come up in PRs

2024-02-22 16:19 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); /// Id 10
Same here for the loop

2024-02-22 16:19 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1);
And here.

2024-02-22 16:19 UTC, oscarsernarosero requested changes
This is great Michael. We have some unnecessary initializations and some other small issues. Great job.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/application/AppManager.sol
> +        super.grantRole(PROPOSED_SUPER_ADMIN_ROLE, newAddress);
I'm not sure where the reentrancy risk was and how this solves it. Could you elaborate?

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/application/AppManager.sol
> +
I'm thinking all these reentrancy-risk flags raised by Slither are false positives in the AppMananger.sol tbh.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20.sol
> +     * @param _symbolProto abreviated name for token (i.e. THRK)
interesting. Why the name change?

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20.sol
> +            uint256 fees = 0;
Solidity initializes uint256 to 0 by default. This change has no real effect except for maybe some more gas consumed (but the optimizer might catch this so not even that).

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ERC20/ProtocolERC20.sol
> +            uint256 fees = 0;
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ProtocolTokenCommon.sol
> +    bool internal _lock = false;
booleans are by default `false`. This initialization has no effect other than maybe more gas expense. So just `bool internal _lock;` would do.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ProtocolTokenCommon.sol
> +    }
I believe OZ has something like this already. So we can either use theirs, or we can put this in a contract that can be inherited so we don't have duplicated code through out the repo.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/ProtocolTokenCommonU.sol
> +    }
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC20TaggedRuleFacet.sol
> +            fromTags = new bytes32[](0);
not sure we need this.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721TaggedRuleFacet.sol
> +            fromTags = new bytes32[](0);
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/Fees.sol
> +        uint24 discount = 0;
Unnecessary initialization.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/Fees.sol
> +            uint feeCount = 0;
Unnecessary initialization.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAccountApproveDenyOracle.sol
> +            Rule memory newOracleRule = Rule(_ruleId, true);
nice

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
> -        bool active;
nice!

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>          uint8 action = 0;
I know this wasn't you, but this initialization is also unnecessary.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>              action++;
++action;

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>          uint8 action = 0;
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>              action++;
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxDailyTrades(_ruleId);
nice!

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/ERC721/ApplicationERC721MintForAFee.sol
> +     * @param _symbolApp Symbol for the NFT
not sure why the name change. In any case, `App` is mostly associated in this context to the appManager since tokens are considered part of an application.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/ERC721/ApplicationERC721WhitelistMint.sol
> +     * @param _symbolApp Symbol for the NFT
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/ERC721/ApplicationERC721WhitelistMint.sol
> -    Counters.Counter private _tokenIdCounter;
nice

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/ERC721/upgradeable/ApplicationERC721UProxy.sol
> +        _;
great catch man

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/ERC721/upgradeable/ApplicationERC721UpgMintForAFee.sol
> +     * @param _symbolApp Symbol for the NFT
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/pricing/CustomERC20Pricing.sol
>      function getTokenPrice(address tokenContract) external view returns (uint256 price) {
with these changes, we should return `(uint256)` instead of `(uint256 price)` since we don't use `price` anywhere

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/pricing/CustomERC20Pricing.sol
>      function getTokenPrice(address tokenContract) external view returns (uint256 price) {
this looks like an old typo tho. Would be good to fix it now that came up

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/pricing/CustomERC721Pricing.sol
> -        return feedPrice;
looks like we are not returning anything now

2024-02-22 16:19 UTC, oscarsernarosero commented on src/example/pricing/CustomERC721Pricing.sol
>      function getNFTCollectionPrice(address nftContract) external view returns (uint256 price) {
same here

2024-02-22 16:19 UTC, oscarsernarosero commented on src/protocol/economic/ruleProcessor/AppRuleDataFacet.sol
> +        emit ProtocolRuleCreated(ACC_MAX_VALUE_BY_ACCESS_LEVEL, index, new bytes32[](0));
I like it

2024-02-22 16:19 UTC, oscarsernarosero commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +    uint256 constant _VOLUME_MULTIPLIER = 100000000;
I love it, but could you express this as `10**8` so it is more readable? or maybe `100_000_000`

2024-02-22 16:19 UTC, oscarsernarosero commented on src/protocol/economic/ruleProcessor/ERC721TaggedRuleProcessorFacet.sol
> +        uint256 cumulativeTotal = 0;
Unnecessary initialization.

2024-02-22 16:19 UTC, oscarsernarosero commented on src/protocol/economic/ruleProcessor/RuleProcessorCommonLib.sol
> -        uint256 maxValue;
nice

2024-02-22 16:20 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1);
Starting to feel real bad about these asks...here too.

2024-02-22 16:20 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); // tokenId = 4
I mean I hope its just copy paste at this point...

2024-02-22 16:22 UTC, TJ-Everett commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); // tokenId = 4
Last one.

2024-02-22 16:23 UTC, TJ-Everett requested changes
Great work Michael! The cleanliness of this ticket was soothing to review. Lots of little pieces in here add up. Just a few questions and some test clean up suggestions.

2024-02-22 20:33 UTC, mpetersoCode55 commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +
So the problem is you'd still have to loop through to determine if any are active. The purpose of the refactor here was to remove the external calls inside of a loop. We could loop through ahead of time but that's adding an additional loop (since the original one still takes place in the contract we're calling), which is probably as/more costly than the single call out for the check right?

2024-02-22 20:36 UTC, mpetersoCode55 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +        IRuleProcessor(handlerBaseStorage.ruleProcessor).checkAccountApproveDenyOracles(accountApproveDenyOracle[action], _to);
So the problem is you'd still have to loop through to determine if any are active. The purpose of the refactor here was to remove the external calls inside of a loop. We could loop through ahead of time but that's adding an additional loop (since the original one still takes place in the contract we're calling), which is probably as/more costly than the single call out for the check right?

2024-02-22 20:37 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            if ((_volume * _VOLUME_MULTIPLIER) / _supply >= uint(rule.max) * 10000) {
So Slither has a limit on how many digits a number can have before it needs to be a constant. I can update these here as well if we want, but we probably want a ticket to go through the repo and cleanse of magic numbers

2024-02-22 21:19 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
Resolved

2024-02-22 21:19 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); /// Id 10
Resolved

2024-02-22 21:20 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1);
Resolved

2024-02-22 21:29 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20.sol
> +     * @param _symbolProto abreviated name for token (i.e. THRK)
Resolved

2024-02-22 21:29 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20.sol
> +     * @param _symbolProto abreviated name for token (i.e. THRK)
For clarity, we decided that these shadow findings are false positives so anywhere name and symbol had to be renamed in a constructor I'm disabling that particular slither finding and using our original syntax.

2024-02-22 21:42 UTC, mpetersoCode55 commented on src/client/token/ProtocolTokenCommon.sol
> +    }
Resolved (Used OZ's implementation)

2024-02-22 21:43 UTC, mpetersoCode55 commented on src/client/token/ProtocolTokenCommonU.sol
> +    }
Resolved (Used OZ's implementation)

2024-02-22 21:45 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>              action++;
++action vs action++ shouldn't make any difference here. Either way it will resolve prior to the while being evaluated again

2024-02-22 21:45 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
>              action++;
++action vs action++ shouldn't make any difference here. Either way it will resolve prior to the while being evaluated again

2024-02-22 22:10 UTC, ShaneDuncan602 commented on src/client/application/AppManager.sol
> +
This is great. We've needed it for quite some time.

2024-02-22 22:13 UTC, ShaneDuncan602 commented on src/client/application/AppManager.sol
> +        super.grantRole(PROPOSED_SUPER_ADMIN_ROLE, newAddress);
I always wondered why so many benign functions have reentrancy guards on production chains. Now I know why...because Slither is the boss of us. I guess it doesn't change much since it's very little gas but I expected Slither to be smarter.

2024-02-22 22:15 UTC, ShaneDuncan602 commented on src/client/application/AppManager.sol
> +
agreed

2024-02-22 22:22 UTC, ShaneDuncan602 commented on src/client/token/ERC721/upgradeable/ProtocolERC721U.sol
> +    uint256[49] __gapU;
I'm curious about this name change. This is the OZ standard name for this.

2024-02-22 22:48 UTC, ShaneDuncan602 commented on src/example/ERC20/ApplicationERC20.sol
> +     * @param _symbolApp  Symbol of the token
Not sure that app is the best variable change here. "token" or "ERC20" might be better so it doesn't get confused with application level variables. The "Application" in the name is really meant to be changed by the devs when they deploy.

2024-02-22 22:48 UTC, ShaneDuncan602 commented on src/example/ERC721/ApplicationERC721AdminOrOwnerMint.sol
> +     * @param _nameApp Name of NFT
same

2024-02-22 22:48 UTC, ShaneDuncan602 commented on src/example/ERC721/ApplicationERC721FreeMint.sol
> +     * @param _nameApp Name of NFT
same

2024-02-22 22:53 UTC, ShaneDuncan602 commented on src/example/pricing/CustomERC721Pricing.sol
> -        return feedPrice;
Yeah, I think the function calls need return statements

2024-02-22 22:54 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/AppRuleDataFacet.sol
> +        emit ProtocolRuleCreated(ACC_MAX_VALUE_BY_ACCESS_LEVEL, index, new bytes32[](0));
saves us money on line count for sure!

2024-02-22 23:00 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +    function areTagsValid(bytes32[] calldata _accountTags) internal pure {
I'm not sure I agree with this change in its current form. Usually, a function that begins with "is" or "are" is expected to return a bool. We don't use this function within a conditional so we should probably rename the function to something that makes more sense like "validateTags".

2024-02-22 23:01 UTC, ShaneDuncan602 requested changes
Great work here. Found some minor stuff but mainly piggy-backed on previous comments.

2024-02-23 12:26 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20.sol
> +            uint256 fees = 0;
We decided to follow slithers convention and do the explicit initializations

2024-02-23 12:26 UTC, mpetersoCode55 commented on src/client/token/ERC20/ProtocolERC20.sol
> +            uint256 fees = 0;
We decided to follow slithers convention and do the explicit initializations

2024-02-23 12:31 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721MintForAFee.sol
> +     * @param _symbolApp Symbol for the NFT
For clarity, we decided that these shadow findings are false positives so anywhere name and symbol had to be renamed in a constructor I'm disabling that particular slither finding and using our original syntax.

2024-02-23 12:31 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721WhitelistMint.sol
> +     * @param _symbolApp Symbol for the NFT
For clarity, we decided that these shadow findings are false positives so anywhere name and symbol had to be renamed in a constructor I'm disabling that particular slither finding and using our original syntax.

2024-02-23 12:32 UTC, mpetersoCode55 commented on src/example/ERC721/upgradeable/ApplicationERC721UpgMintForAFee.sol
> +     * @param _symbolApp Symbol for the NFT
For clarity, we decided that these shadow findings are false positives so anywhere name and symbol had to be renamed in a constructor I'm disabling that particular slither finding and using our original syntax.

2024-02-23 12:34 UTC, mpetersoCode55 commented on src/example/pricing/CustomERC721Pricing.sol
> -        return feedPrice;
Resolved

2024-02-23 12:35 UTC, mpetersoCode55 commented on src/example/pricing/CustomERC721Pricing.sol
>      function getNFTCollectionPrice(address nftContract) external view returns (uint256 price) {
Resolved

2024-02-23 12:39 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +    uint256 constant _VOLUME_MULTIPLIER = 100000000;
Resolved

2024-02-23 12:39 UTC, mpetersoCode55 commented on src/client/application/AppManager.sol
> +
Actually updated to use the one provided by OZ

2024-02-23 12:40 UTC, mpetersoCode55 commented on src/client/token/ERC721/upgradeable/ProtocolERC721U.sol
> +    uint256[49] __gapU;
Yeah this is another instance of the Shadowing false positive, Resolved

2024-02-23 12:41 UTC, mpetersoCode55 commented on src/example/ERC20/ApplicationERC20.sol
> +     * @param _symbolApp  Symbol of the token
We decided to disable the false positives for shadowing, this has been resolved.

2024-02-23 12:41 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721AdminOrOwnerMint.sol
> +     * @param _nameApp Name of NFT
We decided to disable the false positives for shadowing, this has been resolved.

2024-02-23 12:41 UTC, mpetersoCode55 commented on src/example/ERC721/ApplicationERC721FreeMint.sol
> +     * @param _nameApp Name of NFT
We decided to disable the false positives for shadowing, this has been resolved.

2024-02-23 12:43 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1);
Resolved

2024-02-23 12:44 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); // tokenId = 4
Resolved

2024-02-23 12:44 UTC, mpetersoCode55 commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +        ApplicationERC721UpgAdminMint(address(applicationNFTProxy)).safeMint(user1); // tokenId = 4
Resolved.

2024-02-23 12:46 UTC, mpetersoCode55 commented on src/example/pricing/CustomERC20Pricing.sol
>      function getTokenPrice(address tokenContract) external view returns (uint256 price) {
Resolved

2024-02-23 12:47 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +    function areTagsValid(bytes32[] calldata _accountTags) internal pure {
Resolved

2024-02-23 12:49 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            if ((_volume * _VOLUME_MULTIPLIER) / _supply >= uint(rule.max) * 10000) {
Resolved

2024-02-23 12:49 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
>              if (uint256(volatility) > uint(rule.max) * 10000) {
Resolved

2024-02-23 14:58 UTC, merged