Se 583 remove the app manager.s.sol script
thrackle-io/forte-rules-engine-v1 pull request #280
Opened 2024-02-22 19:28 UTC by mpetersoCode55

Removed AppManager.s.sol, OracleAllowed.s.sol, OracleRestricted.s.sol, ApplicaitonCoin.s.sol, and all variants of ApplicationERC721*.s.sol
Updated DemoSetup.sh script to use relevant forge scripts
Updated install_deploy_check.sh and install_forge.sh to use relevant forge scripts
overall script consolidation and refactoring to be more efficient and succinct.

2024-02-22 23:30 UTC, TJ-Everett commented on docs/userGuides/README.md
> +These scripts deploys the contracts that are specific for games, emulating the steps that a application dev would follow. They will deploy 2 ERC20s and 2 ERC721 tokens, among the other setup contract
deploy* - not pluralized

2024-02-22 23:33 UTC, TJ-Everett commented on script/ParseApplicationDeploy.sh
> +# # Retreive the Second App Manager
Retrieve*

2024-02-22 23:36 UTC, TJ-Everett commented on install-forge.sh
> +	bash script/ParseApplicationDeploy.sh 5
This looks awesome! 
Does that mean we can kill the make file now as well?

2024-02-22 23:41 UTC, TJ-Everett approved these changes
This is awesome and long over due. I found a tiny typo and have one question about the make file. 

Also, and please don't hate me but I think we need a quick README.md somewhere that can walk a dev through start to finish our scripting process. Thinking about the upcoming onboarding contributorGuides ticket, this will be a part of it. Even if it is as simple as "run awesomeScript in your commandLine". This would be for us for testing, someone deploying locally, etc.

2024-02-23 15:21 UTC, mpetersoCode55 commented on docs/userGuides/README.md
> +These scripts deploys the contracts that are specific for games, emulating the steps that a application dev would follow. They will deploy 2 ERC20s and 2 ERC721 tokens, among the other setup contract
Resolved

2024-02-23 15:22 UTC, mpetersoCode55 commented on script/ParseApplicationDeploy.sh
> +# # Retreive the Second App Manager
Resolved

2024-02-23 15:23 UTC, mpetersoCode55 commented on install-forge.sh
> +	bash script/ParseApplicationDeploy.sh 5
It's technically a separate ticket, to make sure we update all references throughout the repo, but yes we are now in a state where the Makefile can be deleted

2024-02-26 14:05 UTC, ShaneDuncan602 commented on script/clientScripts/Application_Deploy_01_AppManger.s.sol
AppManger

2024-02-26 14:09 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +The protocol and an example applicaiton architecture can be deployed using the deployment scripts in the script directory. Rn the following commands from the root of the repo to do the deployment:
applicaiton

Rn

2024-02-26 14:10 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +
We probably need to have a little index or description of what gets deployed if they run these scripts and what each contract will be named.

2024-02-26 14:13 UTC, ShaneDuncan602 commented on install-deploy-check.sh
>  TEST_ONE_UNCUT=$(forge test --ffi -vv --match-contract RuleProcessorDiamondTest)
This is only checking the diamond deployment. In order to fully test the app portion of the deployment we would need to create deployment tests for the 20 and 721 or incorporate deployAppERC20Test.sh and deployAppERC721Test.sh

2024-02-26 14:16 UTC, ShaneDuncan602 commented on install-forge.sh
Can we rename this to something like "install-protocol-forge.sh"? Its current name implies that it installs forge.

2024-02-26 14:17 UTC, ShaneDuncan602 commented on script/clientScripts/Application_Deploy_01_AppManger.s.sol
AppManger

2024-02-26 14:21 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +bash script/ParseApplicationDeploy.sh 5
Can we create a bash that does all of this for them? In scripts/clientScripts/deploy, there is a bash that deploys the protocol(deployProtocol.sh). I think it would be good to create one called deployProtocolWithExampleApp.sh that did all of this as well. Then it could be mentioned in this MD as well.

2024-02-26 14:21 UTC, ShaneDuncan602 requested changes
Good stuff. Just some minor typos and suggestions.

2024-02-26 14:28 UTC, mpetersoCode55 commented on script/clientScripts/Application_Deploy_01_AppManger.s.sol
Resolved

2024-02-26 14:29 UTC, mpetersoCode55 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +The protocol and an example applicaiton architecture can be deployed using the deployment scripts in the script directory. Rn the following commands from the root of the repo to do the deployment:
Resolved

2024-02-26 15:08 UTC, mpetersoCode55 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +
Resolved

2024-02-26 15:10 UTC, mpetersoCode55 commented on install-forge.sh
Discussed with Shane, going to tackle this in https://thracklelabs.atlassian.net/browse/SE-588. There's a DOOM component to this change and we don't want to hold up the tickets that are dependent on this getting merged.

2024-02-26 15:10 UTC, mpetersoCode55 commented on script/clientScripts/Application_Deploy_01_AppManger.s.sol
Resolved

2024-02-26 15:23 UTC, mpetersoCode55 commented on docs/userGuides/deployment/DEPLOYMENT-SCRIPTS.md
> +bash script/ParseApplicationDeploy.sh 5
Good catch! Resolved

2024-02-26 16:06 UTC, mpetersoCode55 commented on install-deploy-check.sh
>  TEST_ONE_UNCUT=$(forge test --ffi -vv --match-contract RuleProcessorDiamondTest)
Resolved

2024-02-26 18:16 UTC, ShaneDuncan602 approved these changes
Great work!

2024-02-26 18:53 UTC, merged