Se 492 tron testing enhancement rule creation encapsulation functions
thrackle-io/forte-rules-engine-v1 pull request #281
Opened 2024-02-22 22:15 UTC by TJ-Everett

2024-02-26 14:40 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleCodeData.sol
> -bytes32 constant MIN_ACCT_BAL_BY_DATE = "MIN_ACCT_BAL_BY_DATE";
Good catch

2024-02-26 14:48 UTC, ShaneDuncan602 commented on test/util/RuleCreation.sol
I think these all should return the ruleId. If we have a testing scenario where multiple rules are created and applied to separate actions or tokens, we would have to discern the ruleId by the number of times the functions are called. If we used this on active deployments, we wouldn't know what ruleId to use.

2024-02-26 14:56 UTC, ShaneDuncan602 commented on test/util/RuleCreation.sol
Ok, I think there was some confusion on this one. I think the ticket was asking for the rule creation and activations to be in separate functions. The idea was to abstract out each step so that they could be as modular as possible and then each step could be added to a testXXXRule function.

2024-02-26 14:57 UTC, ShaneDuncan602 requested changes
I think we need a little restructuring on this one.

2024-03-05 16:00 UTC, mpetersoCode55 requested changes
Looks great, really cleans things up! I just had one suggestion on a way to avoid code duplication

2024-03-05 16:00 UTC, mpetersoCode55 commented on test/client/token/ERC721/util/ERC721Util.sol
> +abstract contract ERC721Util is RuleCreation {
A lot of the code in here appears to be duplicated in ERC20Util.sol. Can we move anything that's shared between them out to a separate contract that they inherit to remove the duplicate code?

2024-03-05 22:24 UTC, ShaneDuncan602 commented on test/client/token/ERC721/util/ERC721Util.sol
> +abstract contract ERC721Util is RuleCreation {
That's a good idea. Maybe a SharedUtil that both ERC20Util and ERC721Util could inherit from.

2024-03-05 22:26 UTC, ShaneDuncan602 approved these changes
Looks really good

2024-03-05 23:11 UTC, TJ-Everett commented on test/client/token/ERC721/util/ERC721Util.sol
> +abstract contract ERC721Util is RuleCreation {
Great idea guys! Added in a tokenUtils with all the shared rule creation functions.

2024-03-06 00:20 UTC, oscarsernarosero requested changes
This looks really good man. Im just wondering if we can shrink the rule-creation file by accepting variable-size arrays as parameters instead of polymorphism where it is not clear what each argument is.

2024-03-06 00:20 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint32 ruleId = createAccountMaxTxValueByRiskRule(25, 50, 75, 100_000_000, 10_000, 1, period);
This looks amazing, but Im curious if you could specify an array as a parameter in these rule-creation functions, and then create the arrays at function-calling time. So, something like:
```
createAccountMaxTxValueByRiskRule( createUint8Array(25, 50, 75),  createUint48Array(100_000_000, 10_000, 1), period );
```
so this way the function signature doesn't rely on polymorphism but in variable-size arrays for their parameters which would be much more readable and will consolidate the rule-creation functions.

2024-03-06 00:20 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        _riskScore[2] = 90;
not sure why we need this.

2024-03-06 18:32 UTC, oscarsernarosero approved these changes
Great job man. Just some minor stuff around riskScores, but approving now.

2024-03-06 18:32 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint32 ruleId = createAccountMaxTxValueByRiskRule(createUint8Array(25, 50, 75), createUint48Array(100_000_000, 10_000, 1), period);
Not sure if you use the `_riskScore` variable from line 192 somewhere else, but if you do then you should use it here as well. Otherwise prob better to just get rid of that line (192).

2024-03-06 18:32 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        if (risk >= 90) vm.expectRevert();
I think this is where you use `_riskScore`. So I would keep the line 192 and use the array fields here instead of hard coded values, and also use the array in the rule creation function since you already declared it.

2024-03-06 18:32 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>          uint8[] memory _riskScore = createUint8Array(25, 50, 75, 90);
same here

2024-03-06 18:32 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20.t.sol
> +        applicationAppManager.addRiskScore(user5, 99);
Im thinking that as a general rule for the riskScore case, it is better to declare the array before the rule creation so we can use it later for score assignment and testing.

2024-03-06 20:13 UTC, merged