Add Upgrade steps to Pricing and Oracle md's
thrackle-io/forte-rules-engine-v1 pull request #283
Opened 2024-02-23 22:23 UTC by TJ-Everett

Update App Manager and NFT deployent md's with scripts

2024-02-23 22:52 UTC, excalq commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +#### *[see diamond diagram](../../../images/ApplicationDeployment.png)*
Why not have the PNG inline?

2024-02-23 22:56 UTC, excalq commented on docs/userGuides/deployment/nft/DEPLOY-NFT_AND_HANDLER.md
> +[environment-url]: ./SETENVIRONMENT.md
This currently 404s

2024-02-24 11:44 UTC, mpetersoCode55 requested changes
Looks great Tayler, just caught a small typo

2024-02-24 11:44 UTC, mpetersoCode55 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +3. Use the output from the deployment to set an environment variables:
Remove the "an" (could say relevant instead)

2024-02-24 11:44 UTC, mpetersoCode55 commented on docs/userGuides/deployment/nft/DEPLOY-NFT_AND_HANDLER.md
> +4. Use the output from the deployment to set an environment variables:
Replace an with relevant

2024-02-24 16:57 UTC, TJ-Everett commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +#### *[see diamond diagram](../../../images/ApplicationDeployment.png)*
@excalq I am not sure I know what you mean by this.

2024-02-24 16:57 UTC, TJ-Everett commented on docs/userGuides/deployment/nft/DEPLOY-NFT_AND_HANDLER.md
> +[environment-url]: ./SETENVIRONMENT.md
Thank you! I will double tap all the links

2024-02-26 15:01 UTC, ShaneDuncan602 commented on docs/userGuides/Architecture/Client/AssetHandler/PROTOCOL-ASSET-HANDLER-DIAMOND.md
> +#### *[see diamond diagram](../../../images/ApplicationDeployment.png)*
He is asking why not embed the diagram instead of adding a link

2024-02-26 15:02 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +    forge script script/clientScripts/Application_Deploy_01_AppManger.s.sol --ffi --broadcast
AppManger. I noticed this in Michael's PR as well. He will be changing the name of the script.

2024-02-26 15:03 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-APPMANAGER.md
> +4. The deployer of the Application Manager is granted the [super admin role](../permissions/ADMIN-ROLES.md).
Markdown seems to work, but this looks like it goes from 4 directly to 7

2024-02-26 15:05 UTC, ShaneDuncan602 approved these changes
Crushed it. Just found one typo that isn't really a typo until Michael fixes the AppManger typo in his PR.

2024-03-04 18:26 UTC, merged