Removed Makefile, updated references, fixed broken deployment tests.
thrackle-io/forte-rules-engine-v1 pull request #285
Opened 2024-02-26 21:09 UTC by mpetersoCode55

2024-03-04 21:44 UTC, ShaneDuncan602 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +    /// Test mismatched arrays sizgites
sizgites?

2024-03-04 21:45 UTC, ShaneDuncan602 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +            vm.startPrank(appAdministrator);
We should use switchToAppAdministrator() instead.

2024-03-04 21:46 UTC, ShaneDuncan602 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +            vm.startPrank(superAdmin);
Should be switchToSuperAdmin()

2024-03-04 21:47 UTC, ShaneDuncan602 requested changes
Good job. Just a few little things.

2024-03-04 21:53 UTC, TJ-Everett commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>              user2 = vm.envAddress("SAM");
Totally understand if we think this is out of scope BUT do we want to rename the two "named" addresses as well to something like "LOCAL_RULE_ADMIN" / "LOCAL_RISK_ADMIN" etc?

2024-03-04 21:54 UTC, TJ-Everett approved these changes
Approving since Shane got the good stuff and I am borderline on my comment being out of scope anyway.

2024-03-05 14:59 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>              user2 = vm.envAddress("SAM");
I would lean towards tackling this in the test refactoring ticket just because of the amount of tests/scripts it will impact

2024-03-05 15:08 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +    /// Test mismatched arrays sizgites
Resolved

2024-03-05 15:10 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +            vm.startPrank(appAdministrator);
Resolved

2024-03-05 15:12 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
> +            vm.startPrank(superAdmin);
Resolved

2024-03-05 15:12 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>              user2 = vm.envAddress("SAM");
Discussed with Tayler, holding off on this change for now

2024-03-05 18:30 UTC, merged