SE-514-Create-Invariant-Tests-for-Protocol
thrackle-io/forte-rules-engine-v1 pull request #287
Opened 2024-03-04 17:23 UTC by ShaneDuncan602

This contains the Rule Storage invariant test infrastructure and examples for testing Token Min Transaction Size Rule

2024-03-04 20:53 UTC, mpetersoCode55 requested changes
Looks great! One small question about one of the test cases

2024-03-04 20:53 UTC, mpetersoCode55 commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeMulti.t.i.sol
> +        assertLe(previousTotal, RuleDataFacet(address(ruleProcessor)).addTokenMinTxSize(address(applicationAppManager), 1));
Should this be assertLt instead of assertLe?

2024-03-04 21:29 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-APPROVE-DENY-ORACLE.md
> +        function isAccountAllowDenyOracleActive(ActionTypes _action, uint32 ruleId) external view returns (bool);
Great catch

2024-03-04 21:37 UTC, TJ-Everett approved these changes
This is BADASS Shane! Approved for me.

2024-03-05 02:12 UTC, oscarsernarosero requested changes
Great job overall Shane. Just some minor suggestions since this will be the model to replicate.

2024-03-05 02:12 UTC, oscarsernarosero commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeActorManager.sol
> +    RuleStorageTokenMinTxSizeHandler[] handlers;
Could we rename this for something like "agents" or "actors"?

2024-03-05 02:12 UTC, oscarsernarosero commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeMulti.t.i.sol
> +        assertLe(previousTotal, RuleDataFacet(address(ruleProcessor)).addTokenMinTxSize(address(applicationAppManager), 1));
this assertion makes sure that the new total is incrementing, but not necessarily checks that it is incrementing by 1. I think it is better to assert that new total is exactly the old one +1.

2024-03-05 02:12 UTC, oscarsernarosero commented on test/util/TestCommonFoundry.sol
> +        _addProcessingFacetsToFacetCut();
Im just not sure how this is different than looping through the string array of facets. Since this is a model for us to replicate, I think it is better to make sure this is the most optimal way of doing it.

2024-03-05 02:12 UTC, oscarsernarosero commented on test/util/TestCommonFoundry.sol
> +        inputs[1] = "script/python/get_selectors.py";
I thought I had encapsulated this process, but it looks like I only encapsulated the new scripts that I made in Python. I think it would be a good idea to encapsulate this in this ticket so this model can be replicated without fear of spreading code duplication. You can checkout `script/DiamondScriptUtil.sol` to see what I did for the other scripts if you want, but it is quite simple. I guess the harder part would be to decide where to put that function since it would be used in the scripts and the tests.

2024-03-05 02:12 UTC, oscarsernarosero commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeActorManager.sol
> +    RuleStorageTokenMinTxSizeHandler[] handlers;
or rappers? jk... wrappers?

2024-03-05 15:57 UTC, ShaneDuncan602 commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeMulti.t.i.sol
> +        assertLe(previousTotal, RuleDataFacet(address(ruleProcessor)).addTokenMinTxSize(address(applicationAppManager), 1));
Yep, reworking this one.

2024-03-05 16:49 UTC, ShaneDuncan602 commented on test/protocol/economic/invariant/rules/tokenMinTxSize/RuleStorageTokenMinTxSizeActorManager.sol
> +    RuleStorageTokenMinTxSizeHandler[] handlers;
Going with actors. It's a good point because our use of handler will just confuse things. I don't like straying from foundry's terms but it makes sense for us.

2024-03-05 16:58 UTC, ShaneDuncan602 commented on test/util/TestCommonFoundry.sol
> +        _addProcessingFacetsToFacetCut();
Yeah, this was to allow foundry to pick up the facets and their functions automatically. However, we are using the actor manager model for the invariants so we define the actors and their interfaces ourselves. I'm fine with reverting this back, but I left it in case we want to incorporate the other model and I think it's good to have the facets defined now that the design is stable. That way, the compiler will keep us honest if we change things.

2024-03-06 00:37 UTC, oscarsernarosero approved these changes
Nice job!

2024-03-06 14:45 UTC, merged