Se 592 update solidity compiler version
thrackle-io/forte-rules-engine-v1 pull request #288
Opened 2024-03-05 20:31 UTC by mpetersoCode55

Updated solidity, foundry and OZ dependencies to use the latest versions of each.

2024-03-05 23:40 UTC, ShaneDuncan602 commented
We also need to change the main README to reflect the changes. It still has 4.9 for the versions and talks about npm install. That should have forge install with the proper version.

Also, it looks like there are also still dependencies in the github workflows.

2024-03-05 23:44 UTC, ShaneDuncan602 commented on script/python/get_selectors.py
> +    res = json.loads(line)
This was an awesome change.

2024-03-05 23:48 UTC, ShaneDuncan602 requested changes
Found a few missed dependencies but this is fantastic. Great work.

2024-03-06 00:31 UTC, oscarsernarosero approved these changes
Looks great Michael. Im glad it didn't require lots of detail fixing.

2024-03-06 00:31 UTC, oscarsernarosero commented on docs/userGuides/deployment/DEPLOY-PROTOCOL.md
> -   ```
great catch

2024-03-06 00:31 UTC, oscarsernarosero commented on package.json
> +    "@openzeppelin/contracts-upgradeable": "5.0.2"
nice

2024-03-06 15:15 UTC, merged