Revamp contributor guide
thrackle-io/forte-rules-engine-v1 pull request #297
Opened 2024-03-06 21:53 UTC by VoR0220

First pass attempt at altering the contribution guide. Any and all suggestions welcome! Any way that you think I can make this better, I am all ears to.

2024-03-06 22:33 UTC, excalq approved these changes

2024-03-06 22:33 UTC, excalq commented on docs/contributorGuides/README.md
> +We follow the Rust code of conduct which can be read [here](https://www.rust-lang.org/policies/code-of-conduct). Violations of this code of conduct can be reported to [The Captain](mailto:johnathan@t
Is doxxing The Captain's email address a violation of the code of conduct? Might want to recommend some group alias.

2024-03-06 22:33 UTC, excalq commented on docs/contributorGuides/README.md
> +Foundry can sometimes get finnicky. Make sure all code changes are commited on your branch or no changes have been made before you add fresh dependencies to the code in place. If you are adding a new
Perhaps simplify to recommending dependency changes occur as single commits or separate PRs as much as possible.

2024-03-06 22:33 UTC, excalq commented on docs/contributorGuides/README.md
> +In every way possible, please fill out all nat spec that is reasonable to fill out in the code and try to follow the official [solidity styling guide](https://docs.soliditylang.org/en/latest/style-gu
I think the phrasing could be better structured here. Great doc links though!

2024-03-07 15:13 UTC, TJ-Everett commented on docs/contributorGuides/README.md
> +
While this is industry standard to offer bug bounties, we will want to clear that with @jjbailey-io and @anne-thrackle before we put anything out there promising those.

2024-03-07 15:16 UTC, TJ-Everett commented on docs/contributorGuides/README.md
> +
I think we should add slither in there too

2024-03-07 15:20 UTC, TJ-Everett commented on docs/contributorGuides/README.md
> +
I reccomend deploy(ing) instead of "spinning up". 

"the current core contracts or spinning up a different contracts"  to "the current core contracts or deploying different contracts," 

Lastly, I love the "strenuous effort of having been tested on a local network and verified by external team members on a test network before being merged into mainnet release."  I wonder if we should take a stance that any code should be audited prior to mainnet release? This might be a JB question again.

2024-03-07 15:24 UTC, TJ-Everett requested changes
I think this is a great start. I have some questions that I think the business needs to answer. 

I am curios about your thoughts on if we should actually break this into two md's: one for the new Thrackle dev for internal processes and familiarity and one for open source contributors or if we are satisfied that those two paths should be similar enough?

2024-03-07 16:56 UTC, VoR0220 commented
@TJ-Everett I think we should be aiming as we open source this to try to make this feel as universal as possible in terms of contributing to it. The goal should be to make it feel as if one is committing to something like a Redhat. Anything that you feel could make your business better, you just add it as a composable piece, if you require something internal to contribute, you do so and have it go through the process of being approved. Agreed re: the business side too, I made an assumption here but figured it would need to go through that side first.

2024-03-07 17:28 UTC, TJ-Everett commented
That all makes sense to me @VoR0220  

Once we get the business side questions answered (what email to use and the bug bounties) this is approved for me.

2024-03-07 18:44 UTC, ShaneDuncan602 commented on docs/contributorGuides/README.md
> +
Agreed

2024-03-07 18:48 UTC, ShaneDuncan602 commented on docs/contributorGuides/README.md
> +We follow the Rust code of conduct which can be read [here](https://www.rust-lang.org/policies/code-of-conduct). Violations of this code of conduct can be reported to [the Thrackle Team](mailto:engin
Can we remove "the" from "the Thrackle Team" link?

2024-03-07 18:49 UTC, ShaneDuncan602 commented on docs/contributorGuides/README.md
> +If you have reviewed existing documentation and still have questions or are having problems, we are always a message away. You can reach out to us on the team slack or message [the Thrackle Team](mai
Can we remove "the" from "the Thrackle Team" link?

2024-03-07 18:49 UTC, ShaneDuncan602 commented on docs/contributorGuides/README.md
> +If you feel you have stumbled upon a particularly severe bug, please quietly message [the Thrackle Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so as to p
Can we remove "the" from "the Thrackle Team" link?

2024-03-07 20:35 UTC, VoR0220 commented on docs/contributorGuides/README.md
> +If you feel you have stumbled upon a particularly severe bug, please quietly message [the Thrackle Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so as to p
does the [Thrackle Team] work better?

2024-03-07 20:58 UTC, anne-thrackle approved these changes
This is quite good. Inviting and clear.

2024-03-07 20:58 UTC, anne-thrackle commented on docs/contributorGuides/README.md
> +If you have reviewed existing documentation and still have questions or are having problems, we are always a message away. You can reach out to us on the team slack or message the [Thrackle Team](mai
perhaps we remove the "team slack" part? I don't think our slack is public?

2024-03-07 20:58 UTC, anne-thrackle commented on docs/contributorGuides/README.md
> +
I suggest we remove the mention of a bug bounty for now. We probably should have a bug bounty program, but it'll take some work to set one up. So let's remove it for now and not hold up this PR.

2024-03-07 20:58 UTC, anne-thrackle commented on docs/contributorGuides/README.md
> +
I suggest we _not_ take a public stance on all code being audited prior to Mainnet release. We can work to establish an internal stance first. 

What do you mean by "verified by external team members"? External to Thrackle?

2024-03-07 21:03 UTC, VoR0220 commented on docs/contributorGuides/README.md
> +
I agree we should not take the stance of being audited prior to mainnet release, rather just that the team all clears that this should be added and deployed. Auditing is expensive and they don't catch everything. It's good to grab the bulk and occassionally reaudit while keeping the practices that helped you pass the first audit. External may be the inappropriate term? I meant external to the public but from our perspective internal to the team.

2024-03-07 21:13 UTC, jjbailey-io requested changes
Great start!

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +We're so glad you would want to come and contribute to Tron! We are a small team and we are always looking for help. There are multiple opportunities to contribute at all levels, be it in documentati
Avoid "Tron" in the docs. This is an internal project code name. The repository is actually pushed to another outward facing repository that customers have access  to which is called "rules-protocol". Avoiding names all together helps us manage that.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +We follow the Rust code of conduct which can be read [here](https://www.rust-lang.org/policies/code-of-conduct). Violations of this code of conduct can be reported to the [Thrackle Team](mailto:engin
1. While I agree with the code of conduct, it makes me nervous introducing an outside dependency on our repo. I'd prefer to copy it at a minimum, or remove code of conduct all together. 

2. Instead of "Thrackle Team", just use "Team." I tend to avoid littering code with company names to avoid renames, rebranding, or acquisitions.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +If you have reviewed existing documentation and still have questions or are having problems, we are always a message away. You can reach out to us on the team slack or message the [Thrackle Team](mai
Thrackle Team -> Team

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +If you have reviewed existing documentation and still have questions or are having problems, we are always a message away. You can reach out to us on the team slack or message the [Thrackle Team](mai
Correct. Slack is private.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +If you feel you have stumbled upon a particularly severe bug, please quietly message the [Thrackle Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so as to p
1. Thrackle Team -> Team.
2. Recommend rewording to:
`If you feel you have stumbled upon a particularly severe bug, please quietly message the [Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so the incident response team can react accordingly. If you have found a bug that is not severe or an optimization potential, please open an issue on the repository, and (if possible) a PR with a solution, and a test to show the bug and the fix.`

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +
Agreed.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +
Agreed. We should avoid any "audit" statements. I think we should also avoid introducing architectural concepts (diamond pattern) in the contributors guide.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +If possible, please use JIRA to create new branch names. If you do not have access to the team JIRA, do not fret! Just come up with a decently descriptive name that tracks an issue in Github!
I doubt Jira would ever b accessible to the public. I hesitate to mention it here but for internal members I understand the benefit.

2024-03-07 21:13 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +Always make sure your commits are descriptive. In order to ensure that commits have a chronological sensibility, it may make sense to squash many commits together. In the case of potential merge conf
Recommend:
`Always make sure your commits messages are informative and describe the changes within the commit at a high level. In order to ensure that commits have a chronological sensibility, it may make sense to squash many commits together. In the case of potential merge conflicts, the preferred methodology to resolve said conflicts is to rebase against the trunk and make corrections along the way.`

2024-03-12 13:50 UTC, jjbailey-io requested changes

2024-03-12 13:50 UTC, jjbailey-io commented on docs/contributorGuides/README.md
> +If you feel you have stumbled upon a particularly severe bug, please quietly message the [Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so as to protect cu
I think I mentioned this in my last PR but it must have gotten overlooked. I recommend:
`If you feel you have stumbled upon a particularly severe bug, please quietly message the [Team](mailto:engineering@thrackle.io) as soon as possible and keep the bug report private so the incident response team can react accordingly. If you have found a bug that is not severe or an optimization potential, please open an issue on the repository, and (if possible) a PR with a solution, and a test to show the bug and the fix.
`
We should avoid statements about funds or other financial things.

2024-03-12 13:50 UTC, TJ-Everett approved these changes
Approved.

2024-03-12 21:28 UTC, merged