Refactored tests to relegate pranks to single function scope.
thrackle-io/forte-rules-engine-v1 pull request #298
Opened 2024-03-06 22:50 UTC by mpetersoCode55

2024-03-07 16:26 UTC, TJ-Everett approved these changes
This looks amazing Michael! Well done. Approved

2024-03-07 18:55 UTC, oscarsernarosero requested changes
Nice job here Michael. I do have a suggestion to keep the pattern across all of our tests. I think it is only one file that doesn't follow the pattern, and also some missed `stopPrank()` to be removed and some others to be added. I still think we can improve the line count of our tests by adding a modifier to all of our tests instead of ending with a `stopPrank()`. Something like `endsWithStopPrank`. Idk. Might be worth revisiting the debate.

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> -        vm.startPrank(superAdmin);
nice catch

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> -        vm.stopPrank();
I like removing this from the start of each test since putting this at the end of the setup function saves a lot of lines, but we should then come to parity with the other tests. So I would say we should stick to this pattern where we don't start with stopPrank(). For this to work, obviously, we would have to put the stopPrank() at the end of the setup function.

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/application/deployment/ApplicationDeployment.t.sol
>          vm.stopPrank();
so we should remove these to establish a pattern.

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20.t.sol
> +        vm.stopPrank();
this should go in the setup function to maintain the pattern

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20.t.sol
> +        vm.stopPrank();
nm. I see we need this for the minting

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/token/ERC721/util/ERC721Util.sol
> +
we should end these with stopPrank() to maintain parity with the other tests (I know this is a utility function and not a test perse, but it maters more in these functions actually to end with the stopPrank()). Also to force the subsequent tests to explicitly indicate the address of tx.origin in the test.

2024-03-07 18:55 UTC, oscarsernarosero commented on test/client/token/TokenUtils.sol
> +
Same here. End with stopPrank()

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>              vm.stopPrank();
we should probably move this stop prank out of the if-else clause so we for sure end the setup function with a `stopPrank()`

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>          vm.stopPrank();
we can remove this line since `switchToSuperAdmin()` has it in it

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 18:55 UTC, oscarsernarosero commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
we can remove this one

2024-03-07 19:00 UTC, mpetersoCode55 commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> -        vm.stopPrank();
So the setup functions that have an explicit startPrank all have a stopPrank as well. For ones like this that don't explicitly call startPrank but instead call a setup function from TestCommonFoundry, all of the setup functions in that file have been updated to have a stopPrank at the end, so no prank is carried forward from any setup functions in our tests anymore.

2024-03-07 19:08 UTC, oscarsernarosero commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> -        vm.stopPrank();
Yes. I like this. I think we just have to apply the same to `test/client/application/deployment/ApplicationDeployment.t.sol`

2024-03-07 19:16 UTC, mpetersoCode55 commented on test/client/application/deployment/ApplicationDeployment.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 19:21 UTC, mpetersoCode55 commented on test/client/token/ERC721/util/ERC721Util.sol
> +
resolved

2024-03-07 21:13 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:14 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:14 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:14 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:15 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:15 UTC, mpetersoCode55 commented on test/client/token/TokenUtils.sol
> +
Resolved

2024-03-07 21:17 UTC, mpetersoCode55 commented on test/protocol/economic/deployment/DeploymentProcessor.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:18 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:18 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:19 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:19 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:19 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-07 21:19 UTC, mpetersoCode55 commented on test/protocol/economic/integration/RuleProcessorDiamond.t.sol
>          vm.stopPrank();
Resolved

2024-03-08 20:20 UTC, TJ-Everett commented on test/client/application/integration/AppManager.t.sol
> +    function testApplication_AppManager_IsAppAdministrator_Postive() public {
forgive me

positive*

2024-03-08 20:28 UTC, mpetersoCode55 commented on test/client/application/integration/AppManager.t.sol
> +    function testApplication_AppManager_IsAppAdministrator_Postive() public {
Resolved

2024-03-08 20:29 UTC, TJ-Everett approved these changes
This looks amazing. A well earned approved for me

2024-03-08 21:39 UTC, oscarsernarosero approved these changes
Super clean job Michael

2024-03-08 21:39 UTC, merged