Refactored Tron Tests.
thrackle-io/forte-rules-engine-v1 pull request #325
Opened 2024-03-21 20:50 UTC by mpetersoCode55

Broke tests out so each is testing exactly one thing. Added missing Negative Path tests.
Consolidated duplicate code from various related test files.

2024-03-21 21:18 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20ComplexFuzz.t.sol
> +    // event Log(string eventString, uint256 number);
we should remove this line

2024-03-21 21:20 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20ComplexFuzz.t.sol
> +        vm.stopPrank();
Looks like we are not using DraculaCoin in this testing file so we can rip that all out too

2024-03-21 21:35 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        // emit Log("transferAmount", _transferAmount);
we can remove this line

2024-03-21 21:35 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        // if the transferAmount is the max, adust so the internal arithmetic works
adjust*

2024-03-21 21:42 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        /// first we send only 1 token which shouldn't trigger any risk check
Think we should reword this to "Transfer 1 token to ensure valid transaction passes"

2024-03-21 21:44 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>          /// if the user's risk profile is in the second to the lowest range, this transfer should revert
"risk profile is in the lowest range"

2024-03-21 21:44 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        ///Give tokens to user1 and user2
just user 1 is given tokens here

2024-03-21 21:45 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        /// we set a risk score for user1 and user 2
only user 1 has a risk score set

2024-03-21 21:47 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>          console.log(risk);
The two expectReverts need errors added to them (lines 463, 467)

2024-03-21 21:48 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        applicationCoin.transfer(_user4, riskBalance1 * (10 ** 18) + 1);
These three expect reverts need errors added to them

2024-03-21 21:52 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>          vm.expectRevert();
This revert needs the error added to it

2024-03-21 21:55 UTC, TJ-Everett commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>              999990000000000000000000000000000000000000000000000000000000000000000000000
I created a constant called BIGNUMBER in testCommon that is 10**70 similar to how we do ATTO. These can be refined to 999999 * BIGNUMBER to condense them down if we like that pattern.

2024-03-21 22:26 UTC, TJ-Everett commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        // amm.swap(address(applicationCoin2), 60_000_000);
looks like we can remove this line

2024-03-22 14:52 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +        if (_risk >= riskScoresRuleA[4]) vm.expectRevert();
This revert needs the error added

2024-03-22 14:52 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +        if (_risk >= riskScoresRuleA[1]) vm.expectRevert();
This revert needs the error added

2024-03-22 14:52 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +        if (_risk >= riskScoresRuleA[0]) vm.expectRevert();
This revert needs the error added

2024-03-22 14:56 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>          applicationNFT.safeTransferFrom(_user3, _user4, 19);
The 4 reverts needs the errors added

2024-03-22 15:00 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +        if (risk >= riskScoresRuleB[0]) vm.expectRevert();
These reverts needs the errors added

2024-03-22 15:00 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +        if (risk >= riskScoresRuleB[0]) vm.expectRevert();
These reverts need the errors added

2024-03-22 15:01 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>              vm.expectRevert();
This revert needs the error added

2024-03-22 15:01 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>          if (priceA >= uint112(maxValueForUser2) * ATTO) vm.expectRevert();
This revert needs the error added

2024-03-22 15:03 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +    function testERC721_ApplicationERC721Fuzz_AccountMaxValueOutByAccessLevel(uint8 _addressIndex, uint8 accessLevel) public endWithStopPrank {
I am just realizing that some of these we removed the parens
We should standardize this across all test files so its all the same 

Might be worth making the call now for all modifiers on our preferred syntax (with or w/o parens)

2024-03-22 15:04 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>          applicationCoin.transfer(_user4, 25 * ATTO);
These reverts need the errors added

2024-03-22 15:04 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>              vm.expectRevert();
This revert needs the error added

2024-03-22 15:04 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>          vm.expectRevert();
This revert needs the error added

2024-03-22 15:05 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>                  if (priceA > uint(balanceAmounts[accessLevel]) * ATTO) vm.expectRevert();
This revert needs the error added

2024-03-22 15:05 UTC, TJ-Everett commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
>          vm.expectRevert();
This revert needs the error added

2024-03-22 16:04 UTC, TJ-Everett commented on test/client/application/fuzz/ApplicationAppManagerFuzz.t.sol
> +            applicationAppManager.addAppAdministrator(address(0xBABE));
For everyone's situational awareness Michael and I are going to try and use the selector pattern and abi.encode with selector to see if we can get the expected revert to work with the dynamic address 
If we can - I will go back and set all these with that pattern and remove the log statement and comments for access control errors

2024-03-22 16:26 UTC, TJ-Everett commented on test/client/token/ERC20/integration/ApplicationERC20Handler.t.sol
>          vm.expectRevert();
This revert should have the error added to it

2024-03-22 16:28 UTC, TJ-Everett reviewed
Man we really rock! Just a few typos and missed expectReverts() in here from what I can tell.

2024-03-22 19:01 UTC, ShaneDuncan602 commented on test/client/application/ApplicationCommonTests.t.sol
>          applicationAppManager.revokeRole(APP_ADMIN_ROLE,address(0xB0b));
This needs an assertion to make sure the role was revoked.

2024-03-22 19:02 UTC, ShaneDuncan602 commented on test/client/application/ApplicationCommonTests.t.sol
> +    function testApplication_ApplicationCommonTests_AddAppAdministratorAppManager() public endWithStopPrank() ifDeplomentTestsEnabled() {
Can we fix the typo in ifDeplomentTestsEnabled?

2024-03-22 19:59 UTC, ShaneDuncan602 commented on test/client/application/ApplicationCommonTests.t.sol
>      function testApplication_ApplicationCommonTests_UpdateRiskScore() public endWithStopPrank() ifDeplomentTestsEnabled() {
Wouldn't this need to be split into positive and negative where the negative was a non risk admin trying to update?

2024-03-22 20:31 UTC, ShaneDuncan602 commented on test/client/pricing/integration/ERC20Pricing.t.sol
> +    }
Isn't this the same?

2024-03-22 21:04 UTC, ShaneDuncan602 commented on test/client/token/ERC20/integration/ApplicationERC20.t.sol
> +    function testERC20_ApplicationERC20_TokenMaxSupplyVolatility_Fail() public endWithStopPrank() {
Probably want to stick with our "Negative" naming pattern

2024-03-22 22:06 UTC, ShaneDuncan602 commented on test/protocol/economic/RuleProcessorDiamondCommonTests.sol
> +    function testProtocol_RuleProcessorDiamond_AccountMinMaxTokenBalanceRuleNFT() public endWithStopPrank ifDeplomentTestsEnabled {
Should this one have _Positive in its name?

2024-03-22 22:07 UTC, ShaneDuncan602 commented on test/protocol/economic/RuleProcessorDiamondCommonTests.sol
> +    function testProtocol_RuleProcessorDiamond_AccountMinMaxTokenBalanceRuleNFTBurn() public endWithStopPrank ifDeplomentTestsEnabled {
_Positive?

2024-03-22 22:07 UTC, ShaneDuncan602 commented on test/protocol/economic/RuleProcessorDiamondCommonTests.sol
> +    function testProtocol_RuleProcessorDiamond_AccountApproveDenyOracleNFT() public endWithStopPrank ifDeplomentTestsEnabled {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero requested changes
Mostly found cosmetic stuff and missed opportunities for code encapsulation and code reduction

2024-03-23 21:26 UTC, oscarsernarosero commented on src/client/token/handler/diamond/HandlerDiamond.sol
> + * @title Asset Handler Diamond Contract
oops!

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/application/ApplicationCommonTests.t.sol
> +    function testApplication_ApplicationCommonTests_IsSuperAdmin() public view ifDeploymentTestsEnabled() {
`ifDeploymentTestsEnabled()` => `ifDeploymentTestsEnabled`

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/application/ApplicationCommonTests.t.sol
> +        applicationAppManager.proposeNewSuperAdmin(address(0x677));
Jesus. Why?

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/application/ApplicationCommonTests.t.sol
> +    function testApplication_ApplicationCommonTests_RevokeSuperAdmin_Negative() public endWithStopPrank() ifDeploymentTestsEnabled() {
`endWithStopPrank()` => `endWithStopPrank`

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user1 = addressList[0];
could be written in a single line

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        // Then we add the rule.
could be written in a single line

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint32 ruleId;
could be declared at initialization time

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user3;
could be encapsulated

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
>          address _user3 = addressList[2];
could be encapsulated

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user3 = addressList[2];
could be encapsulated

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user3 = addressList[2];
could be encapsulated

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint48 riskBalance4 = _amountSeed;
could be encapsulated

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user3 = addressList[2];
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint48 accessBalance4 = _amountSeed + 1000;
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user2 = addressList[1];
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint48 accessBalance4 = _amountSeed + 1000;
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user3 = addressList[2];
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint48 accessBalance4 = _amountSeed + 1000;
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        uint48 accessBalance4 = _amountSeed + 1000;
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address _user4 = addressList[3];
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        address toUser = addressList[2];
encapsulate

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        user1 = addressList[0];
reduce

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        user1 = addressList[0];
reduce

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/fuzz/ApplicationERC20Fuzz.t.sol
> +        user1 = addressList[0];
reduce

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_Transfer() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_testTokenMinTransactionSize_Fail() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_testTokenMinTransactionSize_Pass() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxSellSize_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxSellSize_BlankTag_Passes() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxSellSize_BlankTag_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxBuySizeRule_Passes() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxBuySizeRule_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxBuySizeRule_BlankTag_Passes() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_AccountMaxBuySizeRule_BlankTag_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_TokenMaxBuyVolumeRule_Passes() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_TokenMaxBuyVolumeRule_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_TokenMaxSellVolumeRule_Passes() public endWithStopPrank {
_Positive

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +    function testERC20_ERC20CommonTests_TokenMaxSellVolumeRule_Fails() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createAdminMinTokenBalanceRule(5, Blocktime + 500);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createAdminMinTokenBalanceRule(5, Blocktime + 500);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxSupplyVolatilityRule(6000, 8, Blocktime, 0);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxSupplyVolatilityRule(6000, 8, Blocktime, 0);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxTradingVolumeRule(5000, 2, Blocktime, 100_000 * ATTO);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxTradingVolumeRule(5000, 2, Blocktime, 100_000 * ATTO);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMinimumTransactionRule(5);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        ruleIds[4] = createTokenMinimumTransactionRule(5);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/fuzz/ApplicationERC721ComplexFuzz.t.sol
> +contract ApplicationERC721ComplexFuzzTest is TestCommonFoundry, ERC721Util {
this file is completely unnecessary because the tests that got broken up in the original file never lost a single drop of test coverage or case scenario. This was achieved by separating the test cases as expressed in [this document](https://thracklelabs.atlassian.net/wiki/spaces/THRACKLELA/pages/edit-v2/214401029).

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +    }
move to a common file

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ApplicationERC721U.t.sol
> +    function testERC721_ApplicationERC721U_AccountDenyOracle_Fail() public endWithStopPrank {
_Negative

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxDailyTradesRule("BoredGrape5", "DiscoPunk", 1, 45);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxDailyTradesRule("BoredGrape5", "DiscoPunk", 1, 45);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxSupplyVolatilityRule(6000, 8, Blocktime, 0);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxSupplyVolatilityRule(6000, 8, Blocktime, 0);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxTradingVolumeRule(5000, 2, Blocktime, 100_000 * ATTO);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMaxTradingVolumeRule(5000, 2, Blocktime, 100_000 * ATTO);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        periods[4] = 5;
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        periods[4] = 5;
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMinimumTransactionRule(5);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createTokenMinimumTransactionRule(5);
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createAccountMinMaxTokenBalanceRule(createBytes32Array("Shane"), createUint256Array(5), createUint256Array(5000));
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        ruleIds[4] = createAccountMinMaxTokenBalanceRule(createBytes32Array("Michael"), createUint256Array(5), createUint256Array(5000));
for loop

2024-03-23 21:26 UTC, oscarsernarosero commented on test/protocol/economic/RuleProcessorDiamondCommonTests.sol
> +        address newOwner = address(0xB00);
lol

2024-03-25 03:42 UTC, oscarsernarosero approved these changes
great job citizens of Tronland

2024-03-25 18:04 UTC, merged