SE-517-Create-Invariant-Tests-for-Client-Token
thrackle-io/forte-rules-engine-v1 pull request #326
Opened 2024-03-22 17:14 UTC by ShaneDuncan602

2024-03-25 19:07 UTC, oscarsernarosero requested changes
This looks really good in general. I left some suggestions trying to keep up lessons learnt during the swarm of death, and also some question on some tests.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +        target = addressList[3];
There is an encapsulated version of this that we should start using. It is in the swarm of death branch tho.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +        targetSender(USER3);
I would also suggest a for loop here. It would improve readability and reduce the code size.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +        targetSender(USER3);
I would also try to avoid magic numbers and declare what the expected totalSupply is as a constant, and mint those evenly as a function of that expected totalSupply.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +        assertLe(
shouldn't this be `assertEq`?

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +            vm.expectRevert();
Just to avoid ToB come to us with this later, I'm going to say it now, we should specify a revert reason.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +    }
I love the way you built this test

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20MintBurn.t.i.sol
> +        targetSender(USER3);
same as previous one

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Pause.t.i.sol
> +        targetSender(USER3);
same. This should probably go into a common encapsulated function if possible.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +        targetSender(USER3);
same here

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    function invariant_ERC721_external_balanceOfZeroAddressMustRevert() public virtual {
Im curious about the reason to use `virtual` when there is no contract that can possibly override the function

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +        if(!(target != target))return;
could you explain a bit this line?

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    }
Im not sure about this test. There is the `approve` function which modifies an address in the NFT contract, and there is a `setApprovalForAll` function which modifies a mapping in the NFT contract. Essentially, you can have only one approved address, but multiple "operators". I think this test kinda combines these 2 functionalities. They should have separate invariant tests.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    }
I read recently about this. Like who the hell can have the address 0 private key lol. It is still good practice to have this until the full industry comes in agreement about this tho.

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    }
In another thought tho, should we try to `startPrank(address(0))` and try to move an asset?

2024-03-25 19:07 UTC, oscarsernarosero commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    // Transfer to self reset approval
maybe we should test `Transfer to any address resets approval`

2024-03-26 22:07 UTC, ShaneDuncan602 commented on test/client/token/ERC20/invariant/ApplicationERC20Basic.t.i.sol
> +        assertLe(
No, the invariant run will actually mint other tokens to different addresses.

2024-03-27 13:53 UTC, ShaneDuncan602 commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +        if(!(target != target))return;
Copy/paste error

2024-03-27 13:53 UTC, ShaneDuncan602 commented on test/client/token/ERC721/invariant/ApplicationERC721Base.t.i.sol
> +    }
This came directly from ToB

2024-03-27 16:39 UTC, oscarsernarosero approved these changes
Great job man

2024-03-27 16:39 UTC, oscarsernarosero commented on test/client/token/ERC20/invariant/ApplicationERC20Common.t.i.sol
> +}
Nice

2024-03-27 16:42 UTC, merged