invariant tests on rule processing
thrackle-io/forte-rules-engine-v1 pull request #327
Opened 2024-03-23 18:47 UTC by oscarsernarosero

2024-03-27 14:00 UTC, ShaneDuncan602 commented on docs/userGuides/development/invariants/protocol/Protocol-invariants.md
We need to figure out what to do with this file. If we aren't ever going to test the other invariants in here, they need to be moved out so that only the ones that have tests connected remain in the repo for ToB.

2024-03-27 14:03 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxBuySize/RuleProcessingAccountMaxBuySizeMulti.t.i.sol
> +                nftPricer
nice

2024-03-27 14:12 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxBuySize/RuleProcessingAccountMaxBuySizeMulti.t.i.sol
> +    function invariant_multipleAppsCanShareSameRule() public {
This test name doesn't seem to match the comment. By the test name, I would think it was for different handlers having the same rule and ruleId in use.

2024-03-27 14:42 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxSellSize/RuleProcessingAccountMaxSellSizeMulti.t.i.sol
> +    function invariant_amountSoldCanNeverExcedeTheMostRestrictiveTag() public view {
Excede --> Exceed

2024-03-27 14:43 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxSellSize/RuleProcessingAccountMaxSellSizeMulti.t.i.sol
> +    function invariant_multipleAppsCanShareSameRule() public {
Same as above

2024-03-27 14:44 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxTxValueByRiskScore/RuleProcessingAccountMaxTxValueByRiskScoreMulti.t.i.sol
> +    function invariant_amountTransactedCanNeverExcedeTheRiskProfileMaximum() public view {
Excede --> Exceed

2024-03-27 14:45 UTC, ShaneDuncan602 commented on test/client/token/invariant/accountMaxValueOutByAccessLevel/RuleProcessingAccountMaxValueOutByAccessLevelMulti.t.i.sol
> +    function invariant_amountOutCanNeverExcedeMaximumOfAccessLevel() public view {
Excede --> Exceed

2024-03-27 14:50 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxBuyVolume/RuleProcessingTokenMaxBuyVolumeMulti.t.i.sol
> +    function invariant_multipleAppsCanShareSameRule() public {
See above

2024-03-27 15:29 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSellVolume/RuleProcessingTokenMaxSellVolumeMulti.t.i.sol
> +    function invariant_amountSoldCanNeverExcedeRulesMaxPctOfTotalSupply() public view {
Excede

2024-03-27 15:29 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSellVolume/RuleProcessingTokenMaxSellVolumeMulti.t.i.sol
> +    function invariant_multipleAppsCanShareSameRule() public {
Same as above

2024-03-27 15:31 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityActor.sol
> +            (success, res) = _token.call(abi.encodeWithSignature("mint(address,uint256)", address(this), _amount));
Why this style of call?

2024-03-27 15:32 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityMulti.t.i.sol
> +    function invariant_supplyChangeInPeriodCanNeverExcedeRulesMax() public view {
Excede

2024-03-27 15:33 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityMulti.t.i.sol
> +            if (minted > burnt) assertLe(((minted - burnt) * 10000) / TOTAL_SUPPLY, tokenMaxSupplyVolatilityRuleA.max);
Nice

2024-03-27 15:33 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxTradingVolume/RuleProcessingTokenMaxTradingVolumeMulti.t.i.sol
> +    function invariant_amountTransactedCanNeverExcedeRulesPctOfTotalSupply() public view {
Excede

2024-03-27 15:35 UTC, ShaneDuncan602 requested changes
Great job here. Just found some little bitty things.

2024-03-27 16:54 UTC, oscarsernarosero commented on test/client/token/invariant/accountMaxSellSize/RuleProcessingAccountMaxSellSizeMulti.t.i.sol
> +    function invariant_amountSoldCanNeverExcedeTheMostRestrictiveTag() public view {
I always do this. I hate it.

2024-03-27 16:58 UTC, oscarsernarosero commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityActor.sol
> +            (success, res) = _token.call(abi.encodeWithSignature("mint(address,uint256)", address(this), _amount));
So, tbh, it was complaining about not using the right interface for minting ERC20s, and I couldn't find the interface in the OZ lib in like the first 30 seconds so I just decided to do a low level call (I got lazy). I think it is still a good idea to have this in our repo to have it as an example. I can change it if you feel really strong about it.

2024-03-27 17:05 UTC, ShaneDuncan602 commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityActor.sol
> +            (success, res) = _token.call(abi.encodeWithSignature("mint(address,uint256)", address(this), _amount));
It's not a big deal. I was curious more than anything. The only drawback i see is if the api changes it won't get flagged during compile time.

2024-03-27 17:27 UTC, oscarsernarosero commented on docs/userGuides/development/invariants/protocol/Protocol-invariants.md
We did a good chunk of it through explicit invariant tests. The other ones look more like fuzz tests.

2024-03-28 23:03 UTC, oscarsernarosero commented on test/client/token/invariant/tokenMaxSupplyVolatility/RuleProcessingTokenMaxSupplyVolatilityActor.sol
> +            (success, res) = _token.call(abi.encodeWithSignature("mint(address,uint256)", address(this), _amount));
that's true, although "mint" will most likely never change. Almost as standard as the main ERC20 functions.

2024-03-29 15:12 UTC, ShaneDuncan602 approved these changes
Great job!

2024-04-01 15:00 UTC, merged