Se 565 add targeted action based rule tests
thrackle-io/forte-rules-engine-v1 pull request #330
Opened 2024-03-28 01:39 UTC by oscarsernarosero

2024-04-10 19:10 UTC, ShaneDuncan602 commented on script/DeployAllModulesPt4.s.sol
> + * @author @ShaneDuncan602, @oscarsernarosero, @TJ-Everett, @mpetersoCode55
For new files we should be adding RJ to the author line.

2024-04-10 19:23 UTC, ShaneDuncan602 commented on src/client/application/ProtocolApplicationHandler.sol
> +        ruleProcessor.validateAccountMaxValueOutByAccessLevel(_actions, _ruleId);
Seems like these validation functions should only be in the update and not in the two functions that call the update. It's a gas savings for standard setting, but this is a one time thing done by devs so it doesn't really matter.

2024-04-10 19:26 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +        }
I'm really glad we did this.

2024-04-10 19:49 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC20TaggedRuleFacet.sol
> +
We need comments in here to explain why we did this and what is expected for each action. Personally, I would prefer 1 if-else block to handle them. It's easier to read when broken up into like categories.

2024-04-10 19:57 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC721HandlerMainFacet.sol
> +                IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).checkAdminMinTokenBalance(lib.adminMinTokenBalanceStorage().adminMinTokenBalance[action].ruleId, balanceFrom, _amount);
This was a great catch

2024-04-10 19:58 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +        }
Same, need comments here

2024-04-10 19:58 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC721TaggedRuleFacet.sol
> +
Same, need comments here

2024-04-10 21:04 UTC, ShaneDuncan602 requested changes
Mainly some comments and modularization of the rule application validation functions.

2024-04-10 21:04 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleApplicationValidationFacet.sol
> +    }
These functions all need NatSpec comments

2024-04-10 21:21 UTC, oscarsernarosero commented on docs/userGuides/rules/addingNewRules/tokenLevelRules/ADDING_TOKEN_RULE_TO_HANDLER_DIAMOND.md
>              data.tokenMinTxSize[_actions[i]].active = true;
why are we posting the whole function body here?

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
>                  lastTxDateRiskRule[_from] = uint64(block.timestamp);
This looks cool. I would just suggest to encapsulate this _from side and also the _to side, so we only call these 2 functions with maybe the _from/_to address and the action type as parameters so we can cut off some code duplication and help readability and maintainability.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
> +            }
and also use those functions here.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
> +        if (accountMaxValueOutByAccessLevel[_action].active && !appManager.isRegisteredAMM(_from)) {
I don't think the `!appManager.isRegisteredAMM(_from)` is really necessary in both lines 204 and 209 because accountMaxValueOutByAccessLevel will be checked only in the SELL action and not the BUY action. The SELL action will check the address _from where the tokens are being transferred by a a third party (not the case of an AMM).

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
> +        if (accountMaxValueOutByAccessLevel[_action].active && !appManager.isRegisteredAMM(_from)) {
the case where the AMM "sells" tokens would be seen in the token as a BUY action

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
> +        IRuleProcessor(ruleProcessor).validateAccountMaxValueByRiskScore(createActionTypesArray(_action), _ruleId);
this line is unnecessary because the other functions are already doing this check.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/application/ProtocolApplicationHandler.sol
> +        ruleProcessor.validateAccountMaxValueOutByAccessLevel(_actions, _ruleId);
Gas savings was my criteria to implement this in the 2 functions since other wise we would have to loop through the action array unnecessarily since we already have an API that supports this kind of call. But Im not sure I understand the one-time thing

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/common/ActionTypesArray.sol
> +}
I didn't know we already had this in the test file. I think we should use that one since it is already heavily used, and get rid of this one.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721HandlerMainFacet.sol
> +                IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).checkAdminMinTokenBalance(lib.adminMinTokenBalanceStorage().adminMinTokenBalance[action].ruleId, balanceFrom, _amount);
good catch!

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            IRuleProcessor(handlerBaseStorage.ruleProcessor).checkAccountApproveDenyOracles(accountApproveDenyOracle[action], _to);
No real difference in the behavior of the code, but I think `else` would be more readable.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateAdminMinTokenBalance(createActionTypesArray(_action), _ruleId);
this check shouldn't be here since we are already performing this check in the other 2 functions.

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxBuySellVolume.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxBuySellVolume(createActionTypesArray(_action), _ruleId);
this check shouldn't be here

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxDailyTrades(createActionTypesArray(_action), _ruleId);
these 2 checks shouldn't be here

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +            if (_actions[i] == ActionTypes.BURN) revert InvalidAction();
Im thinking we should call the protocol to validate these as well

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSupplyVolatility.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxSupplyVolatility(createActionTypesArray(_action), _ruleId);
this shouldn't be here

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMaxTradingVolume.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxTradingVolume(createActionTypesArray(_action), _ruleId);
this shouldn't be here

2024-04-10 21:21 UTC, oscarsernarosero commented on src/client/token/handler/ruleContracts/HandlerTokenMinTxSize.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMinTxSize(createActionTypesArray(_action), _ruleId);
this shouldn't be here

2024-04-10 21:21 UTC, oscarsernarosero commented on src/protocol/economic/ruleProcessor/RuleApplicationValidationFacet.sol
we should remove this

2024-04-11 14:04 UTC, TJ-Everett reviewed
Just a couple of things I found

2024-04-11 14:04 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-MIN-MAX-TOKEN-BALANCE.md
> +9. Step 4-8 are repeated for each of the account's tags.
line 92 and 95 need an "is" 
balance as it "is" a transfer

2024-04-11 14:04 UTC, TJ-Everett commented on src/protocol/economic/IRuleProcessor.sol
> +     * @dev Check the AccountMaxTokenBalance hald of the AccountMinMaxTokenBalance rule. This rule ensures that the to account does not
half*

2024-04-11 14:36 UTC, mpetersoCode55 approved these changes
Outside of the PR feedback already provided (and one small typo fix I suggested) I approve.

2024-04-11 14:36 UTC, mpetersoCode55 commented on test/client/token/ERC721/fuzz/ApplicationERC721Fuzz.t.sol
> +    function _buildAccountMaxTransactionValueByRiskScoreRuleNFTBuySell(
Should remove the Sell from this name as it has it's own dedicated build function (I did this, cmon Michael get it together)

2024-04-11 14:57 UTC, mpetersoCode55 commented on src/client/application/ProtocolApplicationHandler.sol
> +        ruleProcessor.validateAccountMaxValueOutByAccessLevel(_actions, _ruleId);
I believe we have decided to hold off on this change in favor of closing this ticket so we can get other pre-audit work done. I'm resolving the conversation, but we can always reopen it if needed.

2024-04-11 15:25 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMinTxSize.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMinTxSize(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:25 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxTradingVolume.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxTradingVolume(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:25 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSupplyVolatility.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxSupplyVolatility(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:26 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxBuySellVolume.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxBuySellVolume(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:26 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateTokenMaxDailyTrades(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:26 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +            if (_actions[i] == ActionTypes.BURN) revert InvalidAction();
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:26 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerAdminMinTokenBalance.sol
> +        IRuleProcessor(lib.handlerBaseStorage().ruleProcessor).validateAdminMinTokenBalance(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:27 UTC, mpetersoCode55 commented on src/client/application/ProtocolApplicationHandler.sol
> +        IRuleProcessor(ruleProcessor).validateAccountMaxValueByRiskScore(createActionTypesArray(_action), _ruleId);
Decided not to remove these, since we're going with the internal check design vs multiple external checks.

2024-04-11 15:32 UTC, mpetersoCode55 commented on src/client/common/ActionTypesArray.sol
> +}
The test files are all actually using this implementation. This appears to be the only implementation in the repo and everyone is using it (src and test)

2024-04-11 16:29 UTC, TJ-Everett commented on src/client/application/ProtocolApplicationHandler.sol
> +        if (accountMaxValueOutByAccessLevel[_action].active && !appManager.isRegisteredAMM(_from)) {
I agree but after removing those checks several of the tests broke. I think that we should spin this off into its own ticket and explore removing the redundant check at a later time.

2024-04-11 19:14 UTC, merged