Combine Buy Sell and Buy Sell Volume Rules
thrackle-io/forte-rules-engine-v1 pull request #331
Opened 2024-03-28 14:27 UTC by TJ-Everett

2024-03-28 18:40 UTC, mpetersoCode55 requested changes
Two very minor findings, other than that it looks great!

2024-03-28 18:40 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerAccountMaxTradeSize.sol
> +            delete data.accountMaxTradeSize[ActionTypes(i)];
should we delete boughtInPeriod, lastPurchaseTime, etc here as well

2024-03-28 18:40 UTC, mpetersoCode55 commented on src/protocol/economic/ruleProcessor/RuleCodeData.sol
> +bytes32 constant TOKEN_MAX_BUY_SELL_VOLUME = "TOKEN_MAX_SELL_VOLUME";
Missed the BUY in the string

2024-03-28 20:16 UTC, ShaneDuncan602 commented on docs/userGuides/rules/ACCOUNT-MAX-TRADE-SIZE.md
> +   -If it is a new period and the action type is sell, the processor sets the cumulative buys to the current buy amount.
Shouldn't this be "sets the cumulative sells to the current sell amount"  instead of "sets the cumulative buys to the current buy amount"

2024-03-28 20:27 UTC, ShaneDuncan602 commented on src/client/token/handler/ruleContracts/HandlerAccountMaxTradeSize.sol
> +            delete data.accountMaxTradeSize[ActionTypes(i)];
A delete issued on the action will also delete the child data.

2024-03-28 20:28 UTC, ShaneDuncan602 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxBuySellVolume.sol
> +            emit AD1467_ApplicationHandlerActionApplied(TOKEN_MAX_BUY_VOLUME, _actions[i], _ruleId);
TOKEN_MAX_BUY_VOLUME

2024-03-28 20:29 UTC, ShaneDuncan602 commented on src/common/ErrorSelectors.md
> +| 0x523976c2 | OverMaxSize()                                                 |
Spacing looks off on the last divider

2024-03-28 20:35 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleCodeData.sol
>  bytes32 constant TOKEN_MAX_SELL_VOLUME = "TOKEN_MAX_SELL_VOLUME";
Do we still need these?

2024-03-28 20:42 UTC, ShaneDuncan602 requested changes
Looks great. Just found a couple of tiny things.

2024-03-28 21:28 UTC, mpetersoCode55 commented on src/client/token/handler/ruleContracts/HandlerAccountMaxTradeSize.sol
> +            delete data.accountMaxTradeSize[ActionTypes(i)];
I did a dumb

2024-03-29 14:18 UTC, ShaneDuncan602 approved these changes
Looks great

2024-03-29 14:30 UTC, mpetersoCode55 approved these changes

2024-03-29 14:47 UTC, merged