added tests to attempt to break gas limit on getTotalAccValuation
thrackle-io/forte-rules-engine-v1 pull request #336
Opened 2024-04-05 20:35 UTC by VoR0220

Findings: 

1. Nft limit valuation will do the trick, it will take unbounded gas usage that can reach 100 million units of gas used and convert it downwards to levels of about 69k units of gas used. Going forward, this should be assumed to be 0 when interacting with the protocol unless given a significant suggestion as to why not (perhaps around discussions of potential arbitrage from values not being counted properly from NFT standpoint). 

2. A large set of NFTs and ERC20s (which we've set to about 20 for a default but can be configurable beyond here), will yield  a gas usage of 278047. Thats 278k to evaluate 20 NFTs and 20 ERC20s for their price and how it tracks when used within the EVM. 

3. Created a new file to handle application manager interactions that use both tokens.

2024-04-08 13:50 UTC, ShaneDuncan602 commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        assertLt(gasBegin - gasEnd, 70000); // assert that this is less than 70k. This gives us a baseline to understand what our lower bound should be.
These tests need to also work as fork tests. Will these numbers still work when run against a mainnet fork?

2024-04-08 13:55 UTC, ShaneDuncan602 commented on test/client/application/ProtocolApplicationHandlerTests.t.sol
> +        uint loops = vm.envOr("SLAM_TOKEN_LOOPS", uint(20));
I don't see this variable in the .env. It's currently in the .gitIgnore so you may have to manually add it.

2024-04-08 13:56 UTC, ShaneDuncan602 requested changes
Looks really good. Just have some minor feedback.

2024-04-08 23:51 UTC, VoR0220 commented on test/client/token/ERC721/integration/ERC721CommonTests.t.sol
> +        assertLt(gasBegin - gasEnd, 70000); // assert that this is less than 70k. This gives us a baseline to understand what our lower bound should be.
They absolutely should as gas as a unit is generally speaking a constant. The difference is the cost per unit across platforms. As long as we're forking onto anvil I don't see an issue.

2024-04-08 23:52 UTC, VoR0220 commented on test/client/application/ProtocolApplicationHandlerTests.t.sol
> +        uint loops = vm.envOr("SLAM_TOKEN_LOOPS", uint(20));
Added

2024-04-09 14:33 UTC, ShaneDuncan602 approved these changes
Looks good!

2024-04-09 16:12 UTC, merged