SE-755-High-level-overview-doc-aggregation-for-Tron
thrackle-io/forte-rules-engine-v1 pull request #349
Opened 2024-04-17 22:06 UTC by Palmerg4

Ticket [SE-755](https://thracklelabs.atlassian.net/jira/software/c/projects/SE/boards/1?quickFilter=8&selectedIssue=SE-755) Added docs/OVERVIEW.md, a high level aggregation of current docs for Tron repo.

[SE-755]: https://thracklelabs.atlassian.net/browse/SE-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-18 16:34 UTC, TJ-Everett approved these changes
This is amazing Gordon! Approved for me.

2024-04-18 16:54 UTC, jjbailey-io commented
Can we combine this new page with [https://github.com/thrackle-io/tron/blob/main/docs/userGuides/ARCHITECTURE-OVERVIEW.md](https://github.com/thrackle-io/tron/blob/main/docs/userGuides/ARCHITECTURE-OVERVIEW.md). I think this page gives that diagram more substance. (We could delete the other page and incorporate these diagrams into your new page?)

2024-04-18 17:40 UTC, VoR0220 approved these changes
Overall like the work and think this gives a great overview.

2024-04-18 18:00 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +| TokenHandler              | Deployed by Protocol Supported ERC721's and Protocol Supported ERC20 tokens. Allow for applying, activating, and deactivating token specific rules.          |
This shouldn't say that the handler is deployed by the token. That's the previous version. The current version requires that the handlers be deployed manually.

2024-04-18 18:05 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +| Protocol Supported ERC721 | An ERC721 token that implements the protocol ProtocolERC721.                                                                                                |
We also need an entry for "Protocol Supported ERC20". This definition is close but, we can have a protocol supported ERC721 that does not implement the ProtocolERC721. Implementing ProtocolERC721 is one of the options. The other is manual addition of the protocol hook.

2024-04-18 18:07 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +| Access-Level Provider      | An external provider that rates or segments users based on external criteria for access level solutions.                                     |
We probably need to include reference to the fact that the protocol has default access level mechanisms that allow devs to save their own access levels for their users.

2024-04-18 18:08 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +| Permission Roles          | Roles used by AppManager. They include: Admin, Access Level Admin, and Risk Admin.                                                                            |
We also have Rule Admin and Rule Bypass Admin

2024-04-18 18:32 UTC, Palmerg4 commented on docs/OVERVIEW.md
> +| Protocol Supported ERC721 | An ERC721 token that implements the protocol ProtocolERC721.                                                                                                |
Does this apply to protocol supported ERC20s as well?

2024-04-18 18:34 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +- Pauable (external to the protocol)
Pauable

2024-04-18 18:40 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +- [x] ERC721
We don't currently support ERC721 fees

2024-04-18 18:40 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +The token loops through each applicable fee and sends that amount from the transfer total to the `feeCollectorAccount` for that fee. The total amount of fees assesed is tracked within the transfer as
complettion

2024-04-18 18:45 UTC, ShaneDuncan602 requested changes
This is amazing. I found a few small things but I love this.

2024-04-18 20:28 UTC, ShaneDuncan602 approved these changes
Looks great. Approved!

2024-04-18 21:06 UTC, anne-thrackle requested changes
Swooping in with readability nits. Sorry I only got through the first part of the doc, will finish in the morning but wanted to share these first comments today. 

Overall I'm very excited that we have this now! Very helpful content.

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +This document serves as a high level aggregation of the full protocol documentation. Use this to gain surface level knowledge of the Tron repo and structure of the Rules Protocol.
```suggestion
This document offers a high level overview of the rules protocol - what it does and how it works. Read this to gain an initial understanding of the tron repo and the structure of the rules protocol.
```

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The diamond pattern allows the handler to upgrade, add new features and improvements through the use of a proxy contract. New facet contracts can be deployed and connected to the diamond via a specia
Don't have to use my exact suggestion here, but I think this paragraph should start with saying we use the diamond pattern. 
```suggestion
Tron uses the _diamond_ pattern. The diamond pattern allows the handler to upgrade or add new features and improvements through the use of a proxy contract. New facet contracts can be deployed and connected to the diamond via a specialized function called diamondCut. New facets and functions allow the handler to grow while maintaining address immutability with the proxy contract. Calling contracts will only need to set the address of the diamond proxy at deployment, without having to worry about that address changing over time. The Handler Diamond follows ERC 2535 standards for storage and functions. 
```

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +## Access level structure
```suggestion
## Access Level Structure
```
(matching title case of the other section titles)

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +## Diamond Pattern
it feels a little bit random that this section is the first one on this page, above the Glossary. 

And for this whole document overall, I think perhaps we could improve the organization of the sections - the different sections at the same level are covering different types of topics. 

Also there are enough sections / this doc is long enough that I think we should have a table of contents at the top.

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +| AppManager                | Allows for creation/maintenance of permission roles, application rules, pause windows, user account metadata. |
But what is AppManager? What kind of thing? An admin role?

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +| AppManager                | Allows for creation/maintenance of permission roles, application rules, pause windows, user account metadata. |
I guess same comment for some of the other definitions in this list - not totally clear to me what type of entities we're defining based on the definitions.

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The protocol allows [rule administrators](./userGuides/permissions/ADMIN-ROLES.md) to add rules to the Rule Processor Diamond. The rule id generated by the protocol is then used within an application
I haven't heard us call them _economic_ actions anywhere before. How about some phrasing like "different transaction actions (mint, burn, buy, sell, and peer-to-peer transfer)"

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The protocol allows [rule administrators](./userGuides/permissions/ADMIN-ROLES.md) to add rules to the Rule Processor Diamond. The rule id generated by the protocol is then used within an application
> The rules are immutable and cannot be removed or modified once created.

This might be true in some technical sense, but I think it might give the wrong impression of what can be done. We can in fact stop having a rule be applied. So maybe adding a sentence about that to clarify?

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Token level rules are applied in token handlers and application level rules in the application handler. Within each rule document above is the scope of that rule and the level in which it applies. Wi
maybe link "documentation" to the Rule Guide MD
```suggestion
_Token level_ rules are applied in token handlers and _application level_ rules in the application handler. Each rule's documentation explains the scope of that rule and the level at which it applies. Within the handler contract is a set rule function that receives the rule id for each applicable rule for that handler. A token handler does not have an activate function for application level rules and vice versa. The set rule function sets the rule per applicable [action type](./userGuides/rules/ACTION-TYPES.md). Each rule will only apply to the action types set in the activate rule function. Multiple action types may be used for each rule by sending all the desired types to the set rule function. 
```

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Rule application is a two step process. First, the rule admin must obtain a rule id, either from creating a rule or using an already created rule. Then, they must apply the rule id to the applicable
I personally don't think we need to link to the actions documentation here since we just did it already in the previous paragraph (and additional links decrease readability). 
```suggestion
Rule application is a two step process. First, the rule admin must obtain a rule id, either from creating a rule or using an already created rule. Then, they must apply the rule id to the applicable handler through the appropriate set rule function. Once the rule is added to the protocol and set in the handler, all actions of that type will validate the action through the protocol using the provided rule parameters. The application developer sets the rule applicability and may activate and deactivate as needed. One or many rules may be active at a time. 
```

I don't understand the meaning of this phrase: 
> all actions of that type will validate the action through the protocol using the provided rule parameters.

2024-04-18 21:06 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Rule deactivation is done by sending a "false" boolean with the desired [economic action types](./userGuides/rules/ACTION-TYPES.md) to the activate function. When rule active status is set to "false"
"desired" = the ones we desire to deactivate, or the ones we desire to keep active? 
```suggestion
Rule deactivation is done by sending a "false" boolean with the desired action types to the activate function. When rule active status is set to "false", the action type will not be validated through the protocol. Rule admins can check the activation status of a rule at any time. Within the handler contracts are functions that return the activation status of the rule. The rule id for each rule and action type may be retrieved through the get rule id functions in each handler.
```

2024-04-19 14:52 UTC, anne-thrackle requested changes
Re:organization of this information, I wonder if some of these sections should be subpages with links instead of all in one doc. 

This document is a mix of how it works - from the user's perspective - and how it's implemented. I know this is possibly a major rework and I don't think it's necessary for a first version (this is all pretty good already), but some clearer delineation of those two types of information would make this all easier to digest. I can say more if you want me to. 

I also wonder about all the various levels of control over the rules. app-level, token-level, account-based (tag-based, access-level-based, risk-score-based, oracle), that are not always mutually exclusive... how can we better explain all that at the start? Is there a picture we could draw to help?

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The protocol uses tags to assess fees and perform rule checks for tag-based rules. Based on a user's tags different rule values will be assessed. Users with "TagA" may have a max balance limit of 100
```suggestion
The protocol uses tags to assess fees and perform rule checks for [tag-based rules](./userGuides/tags/TAGGED-RULES.md). A user's transactions will be subject to tag-based rules based on the tags assigned to that user. For example, users with "TagA" may have a max balance limit of 1000 protocol supported tokens where users with "TagB" may have a 10,000 token limit, and users with "TagC" may have no limit at all.  
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Rules may utilize a "blank tag" where no specific tag is provided to the protocol when the rule is created. These rules will apply to all users of the protocol supported token that do not have a tag
```suggestion
Rules may utilize a "blank tag" where no specific tag is provided to the protocol when the rule is created. These rules will apply to all users of the protocol supported token that do not have a tag assigned to them. For example, if an [Account Min/Max Token Balance rule](./userGuides/rules/ACCOUNT-MIN-MAX-TOKEN-BALANCE.md) is active with a blank tag, every user that is not assigned a tag for that rule will be subject to the minimum and maximum limits of that rule. 
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Tags can be applied to individual accounts or addresses of contracts. Tags are used to assess fees or facilitate tagged rule checks throughout the procotol. When an account (user) is tagged, they wil
```suggestion
Tags can be applied to individual accounts or addresses of contracts. Tags are used to assess fees or facilitate tagged rule checks throughout the protocol. When an account (user) is tagged, they will be subject to all rules that are active that utilize that tag. 
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +### Tagged Rules
I don't think we should include this section since it's redundant with an existing page, which we've already linked just above.

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +### Access Level Rules
same comment as above, I think we should be good with the link and not include redundant info (so I suggest removing this section)

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +## Protocol Tags Structure
An organization suggestion: Create a section one level above this (same level as "How Rules Work" section, I think) called something like "What Determines Whether a Rule Applies" or "Rule Applicability Controls" with a little intro like "There are several mechanisms to control whether a rule applies to a particular user's transactions: tags, access levels, and risk scores".
 
and then have subsections for: 
- tags
- access level
- risk score

We could debate whether the oracle allow/deny rule is the same type of thing, that could also be included here I think.

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Access Levels can be assigned to accounts and addresses by Access Level Administrators through the [AppManager](../src/client/application/AppManager.sol). They are predefined as 0,1,2,3,4 and are sto
accounts _and_ addresses? 
I guess we should decide which word we want to use and stick with it throughout the doc - I think you've mostly been using the word account or user so far.

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Access Levels can be assigned to accounts and addresses by Access Level Administrators through the [AppManager](../src/client/application/AppManager.sol). They are predefined as 0,1,2,3,4 and are sto
I think you only need to link to an external page once per section at most. So I would remove additional links to AppManager.

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The protocol uses access levels to perform access level related rule checks. The levels may be used as needed to suit the needs of the application and the rules.
```suggestion
The protocol uses access levels to perform access-level-based rule checks. 
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +Access Levels are applied to addresses. When an access level related rule is activated, all users will be subject to any limitations set by the rule related to their individual access level.
```suggestion
Access Levels are applied to addresses. When an access-level-based rule is activated, all users will be subject to any limitations set by the rule related to their individual access level. 
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +### Super Admin Special Case
```suggestion
#### Super Admin Special Case
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +### Roles
```suggestion
### Admin Roles
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +| Application Level Rules | Purpose |
same comment as above, link > duplicate copy of this info

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The Protocol Asset Handler Diamond serves as the access point to the protocol for a protocol supported asset. The protocol supported asset stores the Handler Diamond proxy address and uses it to call
```suggestion
The Protocol Asset Handler Diamond serves as the access point to the protocol for a protocol supported asset. The protocol supported asset stores the Handler Diamond proxy address and uses it to call the `check all rules function`. The Handler Diamond stores all asset level rule data, rule activation status, and connects the token to the App Manager for role based access control. 
```

2024-04-19 14:52 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +## Protocol Asset Handler Diamond Structure
another terminology thing that is probably not unique to this document... should we use "token" everywhere instead of "asset"? 

or is there a difference in meaning in your view?

2024-04-19 17:46 UTC, Palmerg4 commented on docs/OVERVIEW.md
> +The protocol allows [rule administrators](./userGuides/permissions/ADMIN-ROLES.md) to add rules to the Rule Processor Diamond. The rule id generated by the protocol is then used within an application
In the rules README they are referred to as economic actions and economic action types. Maybe this is outdated.

2024-04-19 18:16 UTC, anne-thrackle commented on docs/OVERVIEW.md
> +The protocol allows [rule administrators](./userGuides/permissions/ADMIN-ROLES.md) to add rules to the Rule Processor Diamond. The rule id generated by the protocol is then used within an application
ah I see it, indeed it looks like it appears mostly in that file (I see 6 instances of "economic action" appearing in documentation, and I assume the word "economic" doesn't appear in the code itself). I suggest we remove that verbiage from tron. @jjbailey-io wdyt?

2024-04-19 19:16 UTC, Palmerg4 commented on docs/OVERVIEW.md
> +## Protocol Asset Handler Diamond Structure
These terms are used seemingly interchangeably throughout the docs. I don't mind switching exclusively to one or the other.

2024-04-22 14:15 UTC, anne-thrackle requested changes
2 things I still think would help a lot here: 
- a table of contents at the top that links to the various sections of this doc. 
- For the first 4 items in the Glossary, explaining what all these things _are_, not just what they do. I think you did it for the rest of the list (their descriptions start with a subject, not a verb). I hope that makes sense. If the concept is too vague to come up with a good subject, then maybe that's indicative of a problem 

Other than that, looks good to me.

2024-04-22 16:43 UTC, anne-thrackle approved these changes
I like the new glossary definitions! Clear to me now. 

lgtm, nice work.

2024-04-24 14:04 UTC, merged