Se 519 create system level invariant tests for erc721
thrackle-io/forte-rules-engine-v1 pull request #351
Opened 2024-04-23 14:09 UTC by TJ-Everett

2024-04-23 17:20 UTC, VoR0220 commented on docs/userGuides/development/invariants/client/token/ERC721/ProtocolERC721-invariants.md
>  # Not Implemented
Let's get rid of this if these have now in fact been implemented.

2024-04-23 18:31 UTC, Palmerg4 requested changes
Noticed that the last test has logic commented out. Is this intentional?

2024-04-23 18:31 UTC, Palmerg4 commented on test/client/token/ERC721/invariant/ApplicationERC721System.t.i.sol
> +    function invariant_ERC721_external_ProposeAppManager_ConfirmAppManager_EventEmission() public {
What is the reason this test logic is commented out?

2024-04-23 18:45 UTC, TJ-Everett commented on test/client/token/ERC721/invariant/ApplicationERC721System.t.i.sol
> +    function invariant_ERC721_external_ProposeAppManager_ConfirmAppManager_EventEmission() public {
That's embarrassing. That was me trying to troubleshoot something and didn't go back to fix that test

2024-04-23 18:48 UTC, TJ-Everett commented on docs/userGuides/development/invariants/client/token/ERC721/ProtocolERC721-invariants.md
>  # Not Implemented
I thought this was the list of ones we have tested / want to test. Is the idea to remove them once tests are implemented?

2024-04-23 21:22 UTC, ShaneDuncan602 approved these changes
Great job. These invariant tests can be tricky. I love the use of excludeContracts and the dummyAcceptor contract.

2024-04-24 12:37 UTC, Palmerg4 approved these changes
Lgtm. Nice tests!

2024-04-24 14:00 UTC, merged