Implement Ways to Handle 4337 Account Abstraction
thrackle-io/forte-rules-engine-v1 pull request #360
Opened 2024-04-25 21:11 UTC by VoR0220

I have added some changes to determineTransferAction that will enable us to reasonably assume when a contract is a smart contract account. In addition I have added tests for NFTs for action handling and modified the testing suite in the ERC20s to account for SCAs.

2024-04-26 14:43 UTC, Palmerg4 requested changes
Looks good! Maybe just update PROTOCOL-ASSET-HANDLER-DIAMOND.md documenting how correctEntryPointAndHasUserOpValidation is used for SCAs and why there are "different" entryPoint method checks

2024-04-26 16:15 UTC, oscarsernarosero requested changes
This looks good RJ!. I just found a couple minor stuff, but the ERC721 side is still incomplete since we need to emulate a marketplace and not an NFT AMM. Your logic seems sound and efficient regarding the action identification tho. Nice job.

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
We need to test the SELL and BUY her with `wallet` instead of `user1`

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
> +        assertEq(uint8(ActionTypes.BUY), uint8(determineTransferAction({_from: address(amm), _to: user1, _sender: address(amm)})));
same here. Instead of `user1` we should plug `wallet`

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
> +        vm.stopPrank();
these lines usually make our Necessist checks to fail. If you look closely, you don't need the `vm.startPrank(eoa);` from line 343. If you remove that line, you can get rid of this one as well.

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
> +        vm.stopPrank();
same here

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
> +        vm.stopPrank();
same here

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC20/integration/ApplicationERC20Actions.t.sol
> +        vm.prank(address(wallet));
oh nice!

2024-04-26 16:15 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ApplicationERC721Actions.t.sol
> +        DummyNFTAMM amm = initializeERC721AMM(address(applicationCoin), address(applicationNFTv2));
although this is a valuable test, we are mostly interested in tests against marketplaces instead of AMMs. So, for instance, OpenSea, Blur, etc. The difference being that in a marketplace, usually the flow is different than in a AMM, and it goes something like this:

1. Approve your NFT to the marketplace (usually as operator).
2. List it for a price.
3. A buyer approves the marketplace to take his money (ETH/MATIC or an ERC20).
4. Buyer then calls the "buy" function in the marketplace.
5. Marketplace takes buyer's money (it usually holds it, and then it becomes claimable for the seller. Not relevant here tho.)
6. **Marketplace transfers the NFT from seller to buyer directly.**

This last piece is super important because this means that we have to check 2 actions simultaneously in the NFT case. These being BUY and SELL since a trade happens between 2 people in the same transaction, and not between a person an a contract. Or at least that is the suspicion. That was the intent for the ticket that was merged into this one.

2024-04-30 14:56 UTC, VoR0220 commented on test/client/token/ERC721/integration/ApplicationERC721Actions.t.sol
> +        DummyNFTAMM amm = initializeERC721AMM(address(applicationCoin), address(applicationNFTv2));
See bottom of the testing suite.

2024-04-30 16:17 UTC, Palmerg4 reviewed
Looks good, but what is the difference between a SBA and a SCA wallet? The contract is named SBAWallet but the tests are marked as SCA tests. Is there a difference?

2024-04-30 16:52 UTC, oscarsernarosero requested changes
Nice job at introducing the marketplace tests. I left some minor suggestions and a request to properly handle the marketplace trades since rn the BUY action is never triggered.

2024-04-30 16:52 UTC, oscarsernarosero commented on src/client/token/handler/common/HandlerUtils.sol
> +        } else if(_isContract(_from) && !_isSmartContractAccount(_from)) {
I would still put an EOA check here to filter a bit more false positives in the EOA cases:
```
else if(_isContract(_from) && (tx.origin == _to || !_isSmartContractAccount(_from))) {
```
This can also make the code more efficient for EOAs because it would skip the calls to check if _from is an SCA.

2024-04-30 16:52 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ApplicationERC721Actions.t.sol
> +        applicationNFTv2.safeMint(user1);
since these lines are becoming repetitive, I would create some global variables and do the repetitive steps in the setUp function.

2024-04-30 16:52 UTC, oscarsernarosero commented on test/client/token/ERC721/integration/ApplicationERC721Actions.t.sol
> +        emit Action(uint8(ActionTypes.SELL));
There is no BUY action being triggered with current implementation. This needs to be taken care of properly.

2024-05-01 18:11 UTC, VoR0220 commented
> Looks good, but what is the difference between a SBA and a SCA wallet? The contract is named SBAWallet but the tests are marked as SCA tests. Is there a difference?

Noted, I'm going to rename it to SCA Wallet to alleviate confusion.

2024-05-02 15:57 UTC, ShaneDuncan602 commented on src/client/token/handler/common/HandlerUtils.sol
We should not be making any implementation changes on this ticket. It is strictly intended to be research and noting change suggestions for future tickets.

2024-05-02 18:47 UTC, oscarsernarosero approved these changes
Looks good RJ! amazing job

2024-05-02 18:47 UTC, oscarsernarosero commented on src/client/token/handler/common/HandlerUtils.sol
I don't agree with this. The research ticket was done already and the ticket itself has the word  "implement" in it.

2024-05-02 19:20 UTC, ShaneDuncan602 commented on foundry.toml
> +
Don't think we want to commit this version.

2024-05-02 19:24 UTC, VoR0220 commented on foundry.toml
> +
Are you sure? The last compiler run we were running 0.8.25...

2024-05-02 19:24 UTC, ShaneDuncan602 commented on lib/forge-std
Was this an intentional update of the submodule?

2024-05-02 19:28 UTC, ShaneDuncan602 commented on foundry.toml
> +
We have always handled this with our local version. It might be something we want to discuss as a team, but I don't think we want to change it here.

2024-05-02 19:29 UTC, VoR0220 commented on lib/forge-std
not intentional, but afaiu it's not upgrading the branch we're using.

2024-05-02 19:38 UTC, VoR0220 commented on foundry.toml
> +
I shall nix it then

2024-05-02 19:45 UTC, ShaneDuncan602 commented on lib/forge-std
I'm not sure. Those submodules don't generally show up unless updated.

2024-05-02 20:23 UTC, VoR0220 commented on lib/forge-std
Do we want to get rid of it here?

2024-05-02 20:34 UTC, ShaneDuncan602 commented on lib/forge-std
Did you do a submodule update at some point?

2024-05-02 20:44 UTC, VoR0220 commented on lib/forge-std
I did not. It feels as though I randomly get the lib/forge-std update as I'm developing throughout other initiatives, possibly due to `foundryup`.

2024-05-02 21:01 UTC, ShaneDuncan602 approved these changes
Ready to rock.

2024-05-03 14:57 UTC, Palmerg4 approved these changes
Looks great! Nice work

2024-05-03 15:16 UTC, merged