SE-779-Modify-Token-Level-Period-Based-Rule-Data-Accumulation
thrackle-io/forte-rules-engine-v1 pull request #366
Opened 2024-05-02 19:23 UTC by ShaneDuncan602

…g Volume

2024-05-02 21:08 UTC, TJ-Everett approved these changes
This looks great Shane! It took me a minute to understand the changes here with the active flag and where that is stored now. Very clever!! Approved

2024-05-03 14:56 UTC, Palmerg4 requested changes
Just a couple unchecked increments I think aren't intended

2024-05-03 14:56 UTC, Palmerg4 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSupplyVolatility.sol
>              unchecked {
The unchecked increment is still present

2024-05-03 14:56 UTC, Palmerg4 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxTradingVolume.sol
>              unchecked {
Here as well. Extra unchecked incrementation

2024-05-03 15:00 UTC, ShaneDuncan602 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxSupplyVolatility.sol
>              unchecked {
Good catch. This must've been a merge issue.

2024-05-03 15:16 UTC, Palmerg4 approved these changes
Look awesome, nice work!

2024-05-03 18:37 UTC, merged