Resolve Audit Finding number 4 Remove Admin Min Token Balance Rule
thrackle-io/forte-rules-engine-v1 pull request #371
Opened 2024-05-03 18:11 UTC by VoR0220

2024-05-03 19:44 UTC, TJ-Everett commented on docs/userGuides/rules/ACCOUNT-MIN-MAX-TOKEN-BALANCE.md
Was this file supposed to be removed? The Account Min Max Token Balance?

2024-05-03 19:47 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20HandlerMainFacet.sol
>              }
The event should still be emitted when a bypass Account / Treasury Account bypasses the rule. This is in case an application wants to track this.

2024-05-03 19:48 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721HandlerMainFacet.sol
> -            }
Same here for the event

2024-05-03 19:53 UTC, VoR0220 commented on docs/userGuides/rules/ACCOUNT-MIN-MAX-TOKEN-BALANCE.md
oof I might have accidentally caught that with the deletions.

2024-05-03 19:53 UTC, TJ-Everett commented on src/client/token/handler/diamond/StorageLib.sol
> -    /**
Line 18 has the ADMIN_MIN_TOKEN_BALANCE_HANDLER_POSITION that needs to be removed as well.

2024-05-03 19:56 UTC, TJ-Everett commented on src/protocol/economic/ruleProcessor/IRuleStorage.sol
> -    /// ******** Admin Min Token Balance ********
Idk where else to put it but src/protocol/economic/ruleProcessor/RuleCodeData.sol also contains rule data that needs the admin token balance removed from it.

2024-05-03 19:59 UTC, TJ-Everett requested changes
Just a couple of missed things and one accidental cut.

2024-05-03 22:42 UTC, TJ-Everett approved these changes
Approved for me!

2024-05-06 15:31 UTC, ShaneDuncan602 approved these changes
Looks great, RJ.

2024-05-06 15:35 UTC, ShaneDuncan602 requested changes
There is still a reference to admin min token balance in:
src/client/token/handler/diamond/ERC721HandlerMainFacet.sol:33:46

2024-05-06 21:04 UTC, merged