Se 745 deployment script and documentation for protocol erc 721 u
thrackle-io/forte-rules-engine-v1 pull request #379
Opened 2024-05-08 18:40 UTC by VoR0220

2024-05-09 17:52 UTC, TJ-Everett commented on script/DeployProtocolERC721U.sol
> + * @author @VoR0220
I have been bad about this but we need to have everyone from the Tron team on the Author line :) 
You, Shane, Gordon, and myself moving forward

2024-05-09 17:57 UTC, TJ-Everett commented on script/DeployProtocolERC721U.sol
> + */
After the first sentence here I would remove the other two and replace with: 
** Requires .env variables to be set with correct addresses and Protocol Diamond addresses **
This fits better with the other deploy script commenting pattern we have 

I would also add in the other scripts before and after this one for successful deployment
i.e. we want to then have a pt2 that sets up, initializes and connects the handler 

This should be basically interchangeable with:
example/script/Application_Deploy_04_ApplicationNFT.s.sol --ffi --rpc-url $RPC_URL --broadcast -vvvv

So someone could run example/script/Application_Deploy_04_ApplicationNFTUpgradable.s.sol --ffi --rpc-url $RPC_URL --broadcast -vvvv for example then continue with the other scripts without them breaking the chain

2024-05-09 18:01 UTC, TJ-Everett commented on script/DeployProtocolERC721U.sol
> +    }
We should also write an export script in parseApplicationDeploy.sh that will export these to the command line for the user. You can copy existing bash commands in there (If I can do it you can do it haha!) that will parse out the _applicationNFTU address 

My thinking is that we will want this to the ApplicationNFT for the remaining scripts not its own variable to make those usable - but we should probably confirm that with everyone at scrum. What I mean by that is that this script should be completely swappable with the other NFT deployment in that it is setting the proxy address as the Application NFT variable in the script series. This also means we would never want to run the NFT and NFTU scripts at the same time to avoid collisions

2024-05-09 18:02 UTC, TJ-Everett requested changes
We want this one to be interchangeable with the current NFT deployment script schema.

2024-05-09 18:02 UTC, VoR0220 commented on script/DeployProtocolERC721U.sol
> + */
so effectively be able to interchange this with other protocol erc721

2024-05-09 18:04 UTC, VoR0220 commented on script/DeployProtocolERC721U.sol
> +    }
Agreed.

2024-05-09 18:19 UTC, ShaneDuncan602 commented on script/DeployProtocolERC721U.sol
> + */
Those are my thoughts as well. We need to be as full service in the docs as possible.

2024-05-09 18:21 UTC, ShaneDuncan602 commented on script/DeployProtocolERC721U.sol
> +    }
Great suggestion. We definitely want to reuse all the scripts we can. As long as we are setting the env variable to the proxy address, everything will function like a non upgradeable NFT.

2024-05-13 18:48 UTC, ShaneDuncan602 commented on docs/userGuides/deployment/DEPLOY-UPGRADEABLE-TOKEN-AND-HANDLERS.md
> +2. Inside the [ApplicationNFT script](../../../script/clientScripts/Application_Deploy_04_ApplicationNFTUpgradeable.s.sol) change the `DAWGUniversity` name, `DAWGU` symbol and `https://dawgieboisuniv
I think we need to stick with our common example theme of public domain classic monsters, Frankenstein, Dracula, etc.

2024-05-13 18:50 UTC, ShaneDuncan602 commented on script/clientScripts/Application_Deploy_04_ApplicationNFTUpgradeablePt2.s.sol
> + * ** Requires .env variables to be set with correct addresses and Protocol Diamond addresses **
need an author line in here

2024-05-13 19:30 UTC, VoR0220 commented on docs/userGuides/deployment/DEPLOY-UPGRADEABLE-TOKEN-AND-HANDLERS.md
> +2. Inside the [ApplicationNFT script](../../../script/clientScripts/Application_Deploy_04_ApplicationNFTUpgradeable.s.sol) change the `DAWGUniversity` name, `DAWGU` symbol and `https://dawgieboisuniv
Is that what it is? Let me go find a monster then.

2024-05-13 19:44 UTC, ShaneDuncan602 approved these changes
Great job!

2024-05-14 19:31 UTC, TJ-Everett commented on docs/userGuides/deployment/DEPLOY-UPGRADEABLE-TOKEN-AND-HANDLERS.md
> +
We should put the new sh script right here as well sh script/SubUpgradeableTokenForRegularToken.sh 
That way if someone is here going doc by doc for deployment it will be more smooth for them.

2024-05-14 19:31 UTC, TJ-Everett approved these changes
One tiny thing in the docs otherwise approved for me!

2024-05-14 19:33 UTC, VoR0220 commented on docs/userGuides/deployment/DEPLOY-UPGRADEABLE-TOKEN-AND-HANDLERS.md
> +
Good point.

2024-05-14 23:24 UTC, merged