SE-784-Resolve-Audit-finding-Number-6-Prune-state-data-when-rule-is-deactivated-or-updated
thrackle-io/forte-rules-engine-v1 pull request #380
Opened 2024-05-08 19:48 UTC by ShaneDuncan602

2024-05-09 19:28 UTC, VoR0220 commented on src/client/token/handler/ruleContracts/HandlerAccountMaxTradeSize.sol
> +        for (uint i; i < data.transactors.length; ++i) {
This has me concerned. This could be a very large list of transactors. Are we sure we won't effectively be bricked here?

2024-05-09 19:30 UTC, VoR0220 commented on src/client/token/handler/ruleContracts/HandlerTokenMinHoldTime.sol
> +        }
perhaps something more gas efficient might be to make a note of when the tokenMinHoldTime rule was activated, and then add a conditional to check if the ownershipStart field of the token was before the ruleActivation period and if so to delete it, or if the rule is not active, to delete the tokenId field on any action.

2024-05-09 19:34 UTC, VoR0220 commented on test/client/token/ERC20/integration/ERC20CommonTests.t.sol
> +        TradingRuleFacet(address(applicationCoinHandler)).activateAccountMaxTradeSize(createActionTypeArray(ActionTypes.SELL), true);
I think we need to replicate this test but with a lot more accounts in the mix. Try to expand the transactors field and see if we run into issues where the gas field is constrained to what we would normally expect from a regular transaction in a live environment.

2024-05-09 19:39 UTC, VoR0220 commented on src/client/token/handler/ruleContracts/HandlerTokenMaxDailyTrades.sol
> +        for (uint i; i < data.tokenIdsByRuleId[_ruleId].length; ++i) {
Similar concerns here. If you have 10k token Ids, this quickly falls into bricking territory. You'd need to either have a way to paginate or find a way thats a bit more passive in how it prunes itself.

2024-05-09 19:42 UTC, VoR0220 requested changes
To summarize: I have concerns that the current implementation is brickable and leaves you unable to activate a rule if you have too many registered token IDs in various places in the rules accumulator clearers. If you wouldn't mind putting together a test and/or an explanation for why I'm wrong to think this, I would be appreciative.

2024-05-13 20:42 UTC, TJ-Everett approved these changes
Great work on this one Shane. Approved for me.

2024-05-13 21:03 UTC, VoR0220 approved these changes
Much better. Approved.

2024-05-13 21:04 UTC, Palmerg4 approved these changes
Looks great!

2024-05-13 21:18 UTC, merged