SE-846-Modify-Implementation-Strategy-to-Support-only-IProtocolToken
thrackle-io/forte-rules-engine-v1 pull request #403
Opened 2024-06-13 16:59 UTC by Palmerg4

2024-06-14 21:16 UTC, ShaneDuncan602 commented on docs/OVERVIEW.md
> +| Protocol Supported ERC20  | An ERC20 token that implements the protocol ApplicationERC20 or the protocol hook.
I think that we should say, "An ERC721 token that implements the IProtocolToken.sol and contains the protocol hook. "

2024-06-18 21:54 UTC, ShaneDuncan602 commented on .gitmodules
> +	url = https://github.com/OpenZeppelin/openzeppelin-contracts
Not really sure why this would change.

2024-06-18 21:56 UTC, ShaneDuncan602 commented on docs/userGuides/architecture/client/PROTOCOL-ERC-20.md
I believe this file name should change.

2024-06-18 21:57 UTC, ShaneDuncan602 commented on docs/userGuides/development/invariants/client/token/ERC20/ProtocolERC20-invariants.md
this file name should change as well

2024-06-18 21:58 UTC, ShaneDuncan602 commented on docs/userGuides/rules/CUSTOMIZATIONS.md
> +Protocol supported NFT's implement OpenZeppelin AccessControl, ERC721, ReetrancyGuard, and AccessControl. These interfaces may be utilized in application NFT's.
AccessControl is listed twice. The second should be ERC721Enumerable

2024-06-18 22:01 UTC, ShaneDuncan602 commented on src/example/ERC721/ApplicationERC721.sol
> +contract ApplicationERC721 is ERC721, AccessControl, IProtocolToken, IZeroAddressError, ReentrancyGuard, ERC721Burnable {
This needs to have enumerable as well. Some rules won't work without it. I'm a little concerned those tests haven't been failing without it.

2024-06-18 22:04 UTC, ShaneDuncan602 commented on test/util/UtilProtocolERC721.sol
> +contract UtilProtocolERC721 is ERC721Burnable, ERC721URIStorage, ERC721Enumerable, ProtocolTokenCommon, AppAdministratorOrOwnerOnly, ReentrancyGuard {
Ah, this is why the tests are failing. This includes enumerable. We probably want to add it to the ApplicationERC721 as well though.

2024-06-18 22:15 UTC, ShaneDuncan602 requested changes
Great job here. Just found a few things. Mostly around docs and Enumerable.

2024-06-18 22:42 UTC, TJ-Everett commented on docs/userGuides/development/invariants/client/token/ERC721/ProtocolERC721-invariants.md
This file name should change too I believe

2024-06-18 22:46 UTC, TJ-Everett reviewed
Awesome work on this Gordon. Really really close just the one file name for me and then Shane's feedback.

2024-06-21 15:07 UTC, TJ-Everett approved these changes
This looks good to go to me!

2024-06-21 19:27 UTC, merged