Se 817 create a testnet token deployment of an lp in the amm with the token
thrackle-io/forte-rules-engine-v1 pull request #404
Opened 2024-06-13 18:15 UTC by mpetersoCode55

2024-06-13 20:31 UTC, ShaneDuncan602 commented on script/clientScripts/Application_Deploy_Example.sh
> +forge script script/clientScripts/Application_Deploy_03_ApplicationFT2Pt2.s.sol --ffi --broadcast --rpc-url $ETH_RPC_URL --gas-price $GAS_NUMBER
So this is expecting the deployed ERC20 to not already be protocol supported. I have a feeling that people will likely set up their token, set rules, and then connect to the AMM. I think this probably needs to handle that. Can we add another conditional prompt once they select "y" for "Do you already have an ERC20 deployed (y or n)?" that allows them to choose whether it is protocol supported already?

2024-06-13 21:09 UTC, ShaneDuncan602 requested changes
Great job. I just have one suggestion to handle protocol supported tokens that are already deployed.

2024-06-14 15:27 UTC, mpetersoCode55 commented on script/clientScripts/Application_Deploy_Example.sh
> +forge script script/clientScripts/Application_Deploy_03_ApplicationFT2Pt2.s.sol --ffi --broadcast --rpc-url $ETH_RPC_URL --gas-price $GAS_NUMBER
Good point! Implemented

2024-06-14 15:31 UTC, ShaneDuncan602 approved these changes
Love it.

2024-06-14 21:19 UTC, merged