Se 862 tron determine action updates add conditionals for non custodial marketplace trades in handlers
thrackle-io/forte-rules-engine-v1 pull request #410
Opened 2024-06-20 20:51 UTC by VoR0220

2024-06-20 20:55 UTC, VoR0220 commented on src/client/application/ProtocolApplicationHandler.sol
> +                if (accountMaxTxValueByRiskScore[_action].active) _checkAccountMaxTxValueByRiskScore(_action, _to,riskScoreTo, _transferValuation);
Lets rewrite this in a fallthrough style so it's cleaner and more efficient
```
            if (isContract(_sender) && _from != _sender){ /// non custodial buy 
                if (accountMaxTxValueByRiskScore[ActionTypes.SELL].active) _checkAccountMaxTxValueByRiskScore(_action, _from, riskScoreFrom, _transferValuation);
            } 
            if (accountMaxTxValueByRiskScore[_action].active) _checkAccountMaxTxValueByRiskScore(_action, _to,riskScoreTo, _transferValuation);```

2024-06-20 20:56 UTC, VoR0220 commented on src/client/application/ProtocolApplicationHandler.sol
> +import "forge-std/console.sol";
I missed this one. Needs deleting.

2024-06-20 20:58 UTC, VoR0220 commented on src/client/application/ProtocolApplicationHandler.sol
> +    }
Feels like this should be in a common file across all of them at this point but we can choose to not do that at this point if its a hassle.

2024-06-20 20:59 UTC, VoR0220 commented on src/client/token/handler/diamond/ERC20HandlerMainFacet.sol
> +                0xcf2eaa37,
Love the consistency

2024-06-20 20:59 UTC, VoR0220 commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +contract ERC20NonTaggedRuleFacet is AppAdministratorOrOwnerOnlyDiamondVersion, HandlerUtils, HandlerAccountApproveDenyOracle, HandlerTokenMaxSupplyVolatility, HandlerTokenMaxTradingVolume, HandlerTok
Do we need this?

2024-06-20 21:00 UTC, VoR0220 commented on src/client/token/handler/diamond/ERC20TaggedRuleFacet.sol
> +contract ERC20TaggedRuleFacet is HandlerAccountMinMaxTokenBalance, HandlerUtils, AppAdministratorOrOwnerOnlyDiamondVersion{
Do we need this?

2024-06-21 11:43 UTC, mpetersoCode55 requested changes
Looks really good guys, just two questions

2024-06-21 11:43 UTC, mpetersoCode55 commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial sell
Should this be _to != _sender since it's a sell?

2024-06-21 11:43 UTC, mpetersoCode55 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial sell
Should this be _to != _sender since it's a sell?

2024-06-21 13:43 UTC, TJ-Everett commented on src/client/application/ProtocolApplicationHandler.sol
> +                if (accountMaxTxValueByRiskScore[_action].active) _checkAccountMaxTxValueByRiskScore(_action, _to,riskScoreTo, _transferValuation);
Lets do it!

2024-06-21 13:44 UTC, TJ-Everett commented on src/client/application/ProtocolApplicationHandler.sol
> +    }
We do not want to use the same common import in the facets and we do the app handler to avoid the circular imports problem we had in Pacman. That is why I dropped the function into the handler directly.

2024-06-21 13:45 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +contract ERC20NonTaggedRuleFacet is AppAdministratorOrOwnerOnlyDiamondVersion, HandlerUtils, HandlerAccountApproveDenyOracle, HandlerTokenMaxSupplyVolatility, HandlerTokenMaxTradingVolume, HandlerTok
Yes, this allows the isContract()

2024-06-21 13:45 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20TaggedRuleFacet.sol
> +contract ERC20TaggedRuleFacet is HandlerAccountMinMaxTokenBalance, HandlerUtils, AppAdministratorOrOwnerOnlyDiamondVersion{
Same here

2024-06-21 13:49 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC20NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial sell
If I am understanding the Action Determination sheet correctly - you are right for better determining the custodial trades (AMM style). In non custodial it doesn't appear to matter, as if the from or to is the sender it is a custodial trade. For logical consistency though I agree and I think we should change this.

2024-06-21 13:49 UTC, TJ-Everett commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial sell
Same

2024-06-21 14:12 UTC, TJ-Everett commented on src/client/application/ProtocolApplicationHandler.sol
> +                if (accountMaxTxValueByRiskScore[_action].active) _checkAccountMaxTxValueByRiskScore(_action, _to,riskScoreTo, _transferValuation);
@Palmerg4 Since you are also working on app level rules refactor part deux - I think you can have the final say here - if we should change this over and if yes, did you want it changed in this ticket or your ticket?

2024-06-21 14:16 UTC, TJ-Everett approved these changes
Giving my approval as the feedback thus far is fantastic. I left comments with agreements / explanations for questions I could answer

2024-06-21 18:02 UTC, oscarsernarosero requested changes
Looks good RJ. I left some suggestions. Some are small and some are related to the logic of the action identification process for non custodial cases. I also didn't see any test specific for the identification of the actions in the case of non-custodial marketplaces. We should have those to be sure we are doing this vital process correctly.

2024-06-21 18:02 UTC, oscarsernarosero commented on docs/userGuides/rules/TOKEN-MAX-BUY-SELL-VOLUME.md
> +7. The processor evaluates whether the current time is within a new `period`.
it looks like the `6.` and `7.` got messed up.

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial buy
I think this can be optimized a bit.  Currently, the `isContract(_sender)` is already checked in the `determineAction` function which is what tells us if a transfer is a BUY/SELL action. So, no need to do this again here. I like the application of the `_from != _sender` to determine if it is non custodial. So in other words, this conditional should look `if (_from != _sender){ /// non custodial buy `

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial sell
I have the same suggestion here. Although, Im not sure how this is working. I think we should check the `to` address instead of the `from`. So my suggestion is having in this line: `if (_to != _sender){ /// non custodial sell `

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721TaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial buy
same here

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/ERC721TaggedRuleFacet.sol
> +            if (isContract(_sender)&& _to != _sender){ /// non custodial sell
and here

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/TradingRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial buy
same here

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/TradingRuleFacet.sol
> +            if (isContract(_sender) && _to != _sender){ /// non custodial sell
and here

2024-06-21 18:02 UTC, oscarsernarosero commented on src/client/token/handler/diamond/TradingRuleFacet.sol
> +        if (lib.accountMaxTradeSizeStorage().accountMaxTradeSize[ActionTypes.BUY].active) {
nice catch!

2024-06-21 18:02 UTC, oscarsernarosero commented on test/client/token/ERC721/marketplace/BuyerMarketplaceTests.t.sol
> +    function test_inBuyersOperatorMarketplace_accountDenyForNoAccessLevel_ERC20Sell() public endWithStopPrank() {
Not a biggie, but we should try to stick to the test naming convention to avoid a future mess.

2024-06-21 18:02 UTC, oscarsernarosero commented on test/client/token/ERC721/marketplace/BuyerMarketplaceTests.t.sol
> +        vm.revertTo(snapshot);
I love it!

2024-06-21 18:05 UTC, VoR0220 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +            if (isContract(_sender) && _from != _sender){ /// non custodial buy
We looked at this but this would require modifying the function signature further. I'm unsure if this has downhill consequences for Tron but yea, it was brought up that we're checking this multiple times and we want to eliminate this. I'll try it in the tests but I have a feeling this might not pass.

2024-06-21 18:06 UTC, VoR0220 commented on test/client/token/ERC721/marketplace/BuyerMarketplaceTests.t.sol
> +    function test_inBuyersOperatorMarketplace_accountDenyForNoAccessLevel_ERC20Sell() public endWithStopPrank() {
Test naming convention here is?

2024-06-21 18:07 UTC, VoR0220 commented on docs/userGuides/rules/TOKEN-MAX-BUY-SELL-VOLUME.md
> +7. The processor evaluates whether the current time is within a new `period`.
ok let me fix these up.

2024-06-21 20:06 UTC, mpetersoCode55 approved these changes

2024-06-21 20:06 UTC, merged