Rename Tron -> Aquifi-rules-v1
thrackle-io/forte-rules-engine-v1 pull request #417
Opened 2024-07-15 21:03 UTC by excalq

# Repository Naming Changes 

- Update mlc_config.json

2024-07-15 21:25 UTC, bfcoursewool approved these changes

2024-07-16 13:25 UTC, jjbailey-io requested changes

2024-07-16 13:25 UTC, jjbailey-io commented on .github/workflows/mlc_config.json
>        "pattern": "https://github.com/thrackle-io/Tron",
This reference should also be updated.

2024-07-17 20:56 UTC, VoR0220 commented on .github/workflows/slither.yml
> +          # May 2, 2024 - Must be a release (nightly) tag
Why are we defining the nightly twice?

2024-07-17 20:58 UTC, VoR0220 approved these changes
Generally accomplishes the goal of renaming things. Just a question about the CI.

2024-07-17 21:00 UTC, jjbailey-io commented on .github/workflows/slither.yml
> +          # May 2, 2024 - Must be a release (nightly) tag
Because they're two separate workflows that are being executed and both are installing foundry. By omitting the version in the second, it was not using the same version.

2024-07-17 21:20 UTC, merged