Update TokenRegistered Event & Add UpdateRegisteredToken fn
thrackle-io/forte-rules-engine-v1 pull request #424
Opened 2024-08-06 16:00 UTC by TJ-Everett

2024-08-06 17:21 UTC, Palmerg4 commented on test/util/TestCommonFoundry.sol
> +        emit AD1467_TokenRegistered(name, address(erc721), 1);
Missing an expectEmit here

2024-08-06 17:25 UTC, Palmerg4 commented on src/client/application/AppManager.sol
> +                tokenType = 0;
Why set tokenType to 0 here?

2024-08-06 17:42 UTC, TJ-Everett commented on src/client/application/AppManager.sol
> +                tokenType = 0;
My thought on the try catch was 
try sets the isERC721 bool 
>>>>If true - set to 1 
>>>>>else set to 0 
on catch 
>>>>>>>set to 0 
This way if the ERC721 doesn't support erc165 it can still register the token - they just need to use the new update function

2024-08-06 17:43 UTC, Palmerg4 commented on src/client/application/AppManager.sol
> +        emit AD1467_TokenRegistered(_token, _tokenAddress, _tokenType);
This event seems a bit redundant, do we want this event to fire when only updating the token name?

2024-08-06 17:44 UTC, Palmerg4 commented on src/client/application/AppManager.sol
> +        if (!isTokenRegistered[_tokenAddress]) {
I think we can just call registerToken here, it has this check included

2024-08-06 17:45 UTC, TJ-Everett commented on src/client/application/AppManager.sol
> +        emit AD1467_TokenRegistered(_token, _tokenAddress, _tokenType);
I was thinking that this would be better on Doom since they are already listening for this specific event to set the token type in the indexer. If we want this to be more specific we can have a different event name since its being updated? 

Idea here is that we are not actually storing the tokenType on chain just a trigger for the indexer.

2024-08-06 17:52 UTC, Palmerg4 commented on src/client/application/AppManager.sol
> +                tokenType = 0;
Shouldnt it be an else block though?

2024-08-06 17:54 UTC, TJ-Everett commented on src/client/application/AppManager.sol
> +                tokenType = 0;
Ahh, yes. Thank you!

2024-08-06 18:23 UTC, Palmerg4 requested changes
Just a few small things. One question I have is do we want to support 1155 here as well in this ticket?

2024-08-06 18:31 UTC, TJ-Everett commented
> Just a few small things. One question I have is do we want to support 1155 here as well in this ticket?

I don't think so. I think we should (if we go the 1155 route in V1) do an entire planned effort for that. We could write tests and integration strategies and include any updates in that. However I can happily be overruled on that.

2024-08-07 14:30 UTC, ShaneDuncan602 commented on src/client/application/AppManager.sol
> +            try IERC165(_tokenAddress).supportsInterface(0x80ac58cd) returns (bool isERC721) {
Can we add a comment in here that explains which interface this is checking for and the value meaning for tokenType?

2024-08-07 17:14 UTC, ShaneDuncan602 approved these changes
Great job.

2024-08-07 17:20 UTC, Palmerg4 approved these changes
Looks great!

2024-08-07 17:21 UTC, merged