SE-863-Document-Process-for-renouncing-and-removing-roles
thrackle-io/forte-rules-engine-v1 pull request #428
Opened 2024-08-08 18:01 UTC by Palmerg4

Added documentation for revoking and renouncing roles, updated some outdated script paths, added some ENV variables for role accounts and private keys used in documentation.

2024-08-08 19:18 UTC, ShaneDuncan602 commented on docs/userGuides/permissions/ADMIN-ROLES.md
> +The following is an example of the command used to add a risk admin by the app admin. Replace `DESIRED_ACCESS_LEVEL_ADMIN_ADDRESS` in the following cast command with the address that is being granted
This line still references risk admin. The command here is actually to add an access level rather than the admin as well. It should be addAccessLevelAdmin

2024-08-08 19:24 UTC, ShaneDuncan602 requested changes
Just found a couple typos. Almost there.

2024-08-08 19:28 UTC, Palmerg4 commented on docs/userGuides/permissions/ADMIN-ROLES.md
> +The following is an example of the command used to add a risk admin by the app admin. Replace `DESIRED_ACCESS_LEVEL_ADMIN_ADDRESS` in the following cast command with the address that is being granted
Ahh nice catch

2024-08-08 23:14 UTC, VoR0220 commented
LGTM

2024-08-08 23:14 UTC, VoR0220 approved these changes

2024-08-09 14:58 UTC, TJ-Everett commented on docs/userGuides/permissions/ADMIN-ROLES.md
>  ### Capabilities
Right below this line is a reference to "player" - should rephrase to user.

2024-08-09 14:58 UTC, TJ-Everett commented on docs/userGuides/permissions/ADMIN-ROLES.md
>  ### Capabilities
Right below this line is a reference to "player" - should rephrase to user.

2024-08-09 14:59 UTC, TJ-Everett reviewed
Really really close! I think we should add in Proxy and Token Admin roles and their hashes to this doc too. Future us will thank us.

2024-08-09 17:40 UTC, TJ-Everett approved these changes
Thanks for adding the additional roles in there. Approved for me!

2024-08-12 14:48 UTC, VoR0220 approved these changes

2024-08-12 15:12 UTC, merged