Update Min Hold Time
thrackle-io/forte-rules-engine-v1 pull request #429
Opened 2024-08-08 22:34 UTC by TJ-Everett

2024-08-08 23:05 UTC, VoR0220 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
> +import "forge-std/console.sol";
We need to drop this

2024-08-08 23:09 UTC, VoR0220 commented on test/client/token/ERC721/util/ERC721Util.sol
> +    //TODO Remove this function once tests are complete
So...uhhh...we removing this?

2024-08-08 23:10 UTC, VoR0220 commented
Very very minute things to change. This looks very gtg assuming tests all pass.

2024-08-09 13:48 UTC, ShaneDuncan602 commented on src/client/application/AppManager.sol
> +import "forge-std/console.sol";
I think this got left behind.

2024-08-09 13:53 UTC, ShaneDuncan602 commented on src/client/token/handler/diamond/ERC721NonTaggedRuleFacet.sol
>          }
This is no longer a simple rule and should probably not be in this function any more. I think it should either go into nontagged rules check or we change the name of the function to _checkMinHoldTime.

2024-08-09 13:57 UTC, ShaneDuncan602 commented on src/client/token/handler/ruleContracts/HandlerTokenMinHoldTime.sol
> +    // slither-disable-next-line calls-loop
Is this needed here?

2024-08-09 14:00 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleDataFacet.sol
> +
Missing natspec comments

2024-08-09 14:01 UTC, ShaneDuncan602 commented on src/protocol/economic/ruleProcessor/RuleStoragePositionLib.sol
> +
Missing natspec comments

2024-08-09 14:08 UTC, ShaneDuncan602 requested changes
Really fast turnaround on this. Great job. I just found a few small things.

2024-08-09 14:25 UTC, Palmerg4 reviewed
Looks great, same suggestions as the other guys. Nice work

2024-08-09 15:04 UTC, TJ-Everett commented on src/client/token/handler/ruleContracts/HandlerTokenMinHoldTime.sol
> +    // slither-disable-next-line calls-loop
I think so, the validate function right below it calls a looped function in the createArray function.

2024-08-09 17:59 UTC, ShaneDuncan602 approved these changes
You rocked it!

2024-08-09 18:01 UTC, VoR0220 approved these changes

2024-08-09 18:07 UTC, Palmerg4 approved these changes

2024-08-09 18:09 UTC, merged