Se 804 modify abi scripts to replace diamond json in deployment directory
thrackle-io/forte-rules-engine-v1 pull request #465
Opened 2024-10-29 15:20 UTC by VoR0220

This fixes UpgradeAFacet script and also fixes Revert A Facet. The flow works like this. You input the name of the facet you want to upgrade and the timestamp directory of which diamond you want to upgrade. Likewise for Revert a Facet but also requires the address of what Facet you want to revert to. Adding documentation clarification now.

2024-10-29 17:53 UTC, TJ-Everett commented on script/RevertAFacetUpgrade.s.sol
> -        recordAllChains = vm.envBool("RECORD_DEPLOYMENTS_FOR_ALL_CHAINS");
Is the idea for removing this, that we technically already have this recorded since this is reverting back to a different facet?

2024-10-29 17:59 UTC, TJ-Everett approved these changes
Looks great, approved for me.

2024-10-29 18:06 UTC, VoR0220 commented on script/RevertAFacetUpgrade.s.sol
> -        recordAllChains = vm.envBool("RECORD_DEPLOYMENTS_FOR_ALL_CHAINS");
iirc this is because it's never used again.

2024-10-29 18:50 UTC, ShaneDuncan602 commented on docs/userGuides/architecture/common/DIAMOND-UPGRADE-REVERSION.md
> +    FACET_TIMESTAMP=<THE_TIMESTAMP_OF_THE_DIAMOND_TO_REVERT> # Find this in the deployments directory, its the name of the folder for when the diamond was deployed
I don't see this variable in the .env

2024-10-29 20:46 UTC, ShaneDuncan602 requested changes
This looks really close. I just tested a live update though and found that it isn’t updating the address of the facet with the diamonds.json. Since that file is the new source of truth for facet addresses, it should also replace the address of the old facet with the new one. Also, we should have the FACET_TIMESTAMP in the .env

2024-10-30 15:38 UTC, ShaneDuncan602 approved these changes
Great job. This looks ready to me.

2024-10-30 15:39 UTC, merged