Remove docs from the repo
thrackle-io/forte-rules-engine-v1 pull request #479
Opened 2024-12-06 21:56 UTC by dmulvi

This removes docs from the repo and points users to the documentation site instead. 

- move contributorGuides from /docs to root
- delete /docs directory
- update README to point to docs site (note the links is to as of yet NOT live https://docs.forterulesengine.io)
- update markdown.yml to remove paths that no longer exist

2024-12-09 14:02 UTC, jjbailey-io requested changes
The following should be completed too:

1. Remove .github/workflows/docs.yml 
2. Add "https://docs.forterulesengine.io/" to the ignore patterns in .github/workflows/mlc_config.json.

2024-12-09 14:02 UTC, jjbailey-io commented on README.md
> +
Incomplete thoughts?

2024-12-09 14:02 UTC, jjbailey-io commented on CONTRIBUTING.md
> +[upgradeSubmodules-url]: contributorGuides/SUBMODULE-UPGRADE.md
I recommend we keep any docs in a docs folder. Let's rename contributorGuides to docs. Then the path is just docs/CHECKOUT-REPO.md and docs/SUBMODULE-UPGRADE.md

2024-12-10 21:37 UTC, dmulvi commented on README.md
> +
haha up, nice catch!

2024-12-11 16:10 UTC, anne-thrackle reviewed
I just reviewed the main README. It's close but I suggest a couple minor edits.

2024-12-11 16:10 UTC, anne-thrackle commented on README.md
I feel like we should actually link to the docs at the top of the main README somewhere, e.g. right before "Installation". So people don't have to scroll down to find the docs.

2024-12-11 16:10 UTC, anne-thrackle commented on README.md
> +For complete usage information and documentation, please visit the docs at https://docs.forterulesengine.io.
```suggestion
For complete usage information and documentation, please visit [our docs](https://docs.forterulesengine.io).
```
This might be contentious, so I'm ok leaving it as is, but I personally this looks more professional. Although I see you did it differently in the next section - is there a reason you presented the URL plainly here?

2024-12-11 16:10 UTC, anne-thrackle commented on README.md
>  ### Example Application
I'm not sure it's useful to have this "Example Application" section here, maybe we remove it given our move to the docs platform? Feels a little random in this context in my opinion.

2024-12-11 16:11 UTC, anne-thrackle commented on README.md
>  ### Example Application
Come to think of it - If we add a link at the top of the README to the docs, then maybe we don't need the "User Guide" section either here.

2024-12-12 20:35 UTC, anne-thrackle approved these changes
good for me on the main README.

2024-12-12 21:51 UTC, TJ-Everett approved these changes
Approved for me.

2024-12-12 21:55 UTC, merged