inconsistent implementation of risk processing (17)
thrackle-io/forte-rules-engine-v1 pull request #60
Opened 2023-07-25 20:05 UTC by TJ-Everett

2023-07-25 21:34 UTC, ShaneDuncan602 approved these changes
Looks good.

2023-07-26 01:52 UTC, oscarsernarosero requested changes
Some changes to the logic and documentation is needed. We should make sure all the risk rules are written in the same manner in this ticket, and make sure the tests are thorough enough to catch any edge-case misbehavior.

2023-07-26 01:52 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RiskTaggedRuleProcessorFacet.sol
> +     *    25             1000            0-24  =  1000
Haven't seen the code yet, but this documentation is already wrong. There shouldn't be any limit in the first range which makes the txLimit array and the risk score array to have the same length (not +1 on the TxLimit as illustrated here). Therefore 0-24 should have no limit other than the imposed by the data size.

2023-07-26 01:52 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RiskTaggedRuleProcessorFacet.sol
> +            if (_riskScore < rule.riskLevel[i]) {
Actual table should be something like:

| Risk Score | TxLimit | Means |
| - | - | - |
| 0* | No Limit * | 0 -> 24: No Limit * |
| 25 | 1000 | 25 -> 49: 1000 max |
| 50 | 500 | 50 -> 74: 500 max |
| 75 | 250 |  75 -> 100: 250 max |

##### * This refers to implied values and therefore it is not necessary to be written as part of the rule (They are already part of every rule implicitly )

This means that this logic here should be refactored since current logic would behave differently than expected.

2023-07-26 01:52 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RiskTaggedRuleProcessorFacet.sol
> +            if (_riskScore < rule.riskLevel[i]) {
Assuming that both input arrays have the same length, there are a couple things that this in bringing up here and most likely needs to be fixed in the other rules as well:

- We might want to check if the risk score is less than the lowest risk score in the rule since this would mean that the risk score is too low, which means it has no limit ( 0 - lowest risk score) and therefore it automatically passes the check (basically no check needed) This would reward well-behaved users with low-cost transactions.

- This also means that the for loop should start with *i* on *1* and not on *0*.  ```for (uint256 i=1; i < rule.riskLevel.length ; )```

It would be beneficial to discuss with @ShaneDuncan602  about the the limits being inclusive or exclusive at the bottom or at the top, and then making sure all the rules have the same strategy. I personally keep going back and forth with this, but right now --if you ask me-- I think the rules being inclusive at the bottom and exclusive at the top makes sense, but this also mean that rules can have risk scores of 100. Since these rules have been touched many times by some of us, this is the chance we have to standardize them.

2023-07-26 06:34 UTC, oscarsernarosero approved these changes
Since we still have the old implementation in place, this logic adjustments are perfect.

2023-07-26 06:34 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RiskTaggedRuleProcessorFacet.sol
> +            if (_riskScore < rule.riskLevel[i]) {
Ok sorry. I think I was confused about the state of the implementation of the rules. Since we still have the implementation of the rule with different array sizes, this logic is perfect. We're good to go!

2023-08-02 15:39 UTC, TJ-Everett commented
This is now issue 17 in the ToB final report

2023-08-21 19:49 UTC, ShaneDuncan602 commented
merged with external

2023-08-21 19:49 UTC, closed without merging