External 36
thrackle-io/forte-rules-engine-v1 pull request #84
Opened 2023-08-01 21:03 UTC by TJ-Everett

Audit - Unbounded loop in getAccTotalValuation could result in denial of service (14)

2023-08-02 16:39 UTC, ShaneDuncan602 commented on src/example/pricing/CustomERC721Pricing.sol
> +
Can we add comments to this that explain that chainlink only provides the floor price so this function and the tokenId specific one are doing the same thing?

2023-08-02 16:42 UTC, ShaneDuncan602 commented on src/token/ProtocolERC721Handler.sol
> +        setNFTValuationLimit(100);
Can we add a comment, "Defaulted to 100 but may be changed at any time" ?

2023-08-02 16:49 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +
This is a great and well documented test. Can we add one additional test where the valuation limit is increased to show that it will go back to individual pricing? Also, we may need a test to ensure it behaves as we think it should when the balance is exactly the limit.

2023-08-02 16:51 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +
Is this necessary since it is set to 100 in the constructor?

2023-08-02 16:51 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +        applicationNFTHandler.setNFTValuationLimit(100);
same

2023-08-02 16:54 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +        applicationNFTHandler.setNFTValuationLimit(20);
I think in order to fuzz this we have to make the limit variable part of the fuzzing. It would probably be better to make it a fuzz variable and the mint amount static.

2023-08-02 16:54 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +        applicationNFTHandler.setNFTValuationLimit(100);
same as above

2023-08-02 16:55 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +
same

2023-08-02 16:55 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +        applicationNFTHandler.setNFTValuationLimit(100);
same

2023-08-02 16:55 UTC, ShaneDuncan602 commented on test/ApplicationERC721Fuzz.t.sol
> +
same

2023-08-02 16:55 UTC, ShaneDuncan602 commented on test/ApplicationERC721U.t.sol
>          ///Set Risk Scores for users
same

2023-08-02 16:55 UTC, ShaneDuncan602 commented on test/ApplicationERC721U.t.sol
> +
same

2023-08-02 16:56 UTC, ShaneDuncan602 commented on test/ApplicationERC721U.t.sol
> +
same

2023-08-02 16:56 UTC, ShaneDuncan602 requested changes
Really good. Just some minor suggestions.

2023-08-02 18:20 UTC, TJ-Everett commented on test/ApplicationERC721U.t.sol
> +
Thanks for catching these. Added to get the tests passing before the constructor updated and forgot to pull them back out.

2023-08-02 18:20 UTC, TJ-Everett commented on test/ApplicationERC721Fuzz.t.sol
> +        applicationNFTHandler.setNFTValuationLimit(20);
I just added additional testing scenarios instead of replacing. Since more testing is always better!

2023-08-03 15:56 UTC, ShaneDuncan602 approved these changes
Love this!

2023-08-21 19:51 UTC, ShaneDuncan602 commented
merged with external

2023-08-21 19:51 UTC, closed without merging