Audit 1 - Fixing date rules logic
thrackle-io/forte-rules-engine-v1 pull request #85
Opened 2023-08-03 15:31 UTC by ShaneDuncan602

Completely rewired period based date rules to store a timestamp and use it for determining the period. All logic runs through the same library for these checks so that date check logic needs to be thoroughly checked. Closes #23

2023-08-03 16:33 UTC, TJ-Everett approved these changes
looks great Shane. Approved

2023-08-03 20:33 UTC, oscarsernarosero requested changes
This looks really good. It works fine as it is, but I do have several suggestions regarding gas efficiency for which I think it is important to go through each one.

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +    }
this looks good

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +        }
great

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +            currentPeriodStart = _startTimestamp;
Is this conditional necessary? If you do the math in the calculation down below, it would take care of that itself:
```
_startTimestamp = 1000
block.timestamp = 1001
secondsSinceStart = 1
_period = 24

 _startTimestamp + (_period * ((secondsSinceStart / (_period * 1 hours)) * 1 hours))
 1000 + (24 * ((1/(24*3600)*3600) --> since solidity always rounds to floor, (1/(24*3600)) = 0; even (86399/86400) = 0
1000 + (24 * 0 * 3600)
1000 + 0
1000
 ```

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +            currentPeriodStart = _startTimestamp + (_period * ((secondsSinceStart / (_period * 1 hours)) * 1 hours));
All this work until here is really great, and I know you don't like the old logic, but I think it is just way more efficient. Since we are building this as a helper function, I don't think we would have to worry about it being too fancy. So I would just stick to the efficient calculation:
```
 currentPeriodStart = block.timestamp - secondsSinceStart % (_period * 1 hours);
```

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            totalPurchasedWithinPeriod = amountToTransfer; /// resets value for purchases outside of purchase period
I think we should initialize the variable at creation time in line 90 for more gas efficiency

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                totalPurchasedWithinPeriod = amountToTransfer;
this here is unnecessary since ```totalPurchasedWithinPeriod``` is already ```amountToTransfer```

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            if (percentagePurchaseRule.totalSupply == 0) totalSupply = currentTotalSupply;
Ok I see what you're doing here. This is all good. So this is just a suggestion that I think helps readability, but it's up to you. You can save some gas by only doing one initialization of the variable like this:
```
uint256 totalSupply = percentagePurchaseRule.totalSupply == 0 ? currentTotalSupply : percentagePurchaseRule.totalSupply;
```

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            uint256 totalSupply = percentageSellRule.totalSupply;
same suggestion from above with the ternary conditional for initialization

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            }
same here. This is not necessary since the variable is already ```amountToTransfer```

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
>      function checkTotalSupplyVolatilityPasses(
this function is lacking documentation

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                if (_tokenTotalSupply == 0) _tokenTotalSupply = _supply;
I don't fully understand here why we have tokenTotalSupply and supply variables. It's hard for me to review the logic until I understand that fully.

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC721RuleProcessorFacet.sol
>                          uint256 tradesAllowedPerDay = rule.tradesAllowedPerDay;
we don't really need this variable. We can just access the rule data directly since it is only read once.

2023-08-03 20:33 UTC, oscarsernarosero commented on src/economic/ruleStorage/RuleStorageCommonLib.sol
> +    }
nice

2023-08-03 21:13 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +            currentPeriodStart = _startTimestamp;
I agree. I was originally getting a weird divide by 0 error, but that was unrelated. I'm removing this.

2023-08-04 13:45 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +            currentPeriodStart = _startTimestamp + (_period * ((secondsSinceStart / (_period * 1 hours)) * 1 hours));
Ok. I see your point. We all don't have to understand what it's doing. As long as we know how to use it we are good. I'll change it.

2023-08-04 14:04 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                if (_tokenTotalSupply == 0) _tokenTotalSupply = _supply;
The tokenTotalSupply has to be adjusted because if the token's totalSupply is used it skews the results in the period. Since this rule is for mints/burns it changes that total. A bunch of small mints and burns pushes the goal post if the token's total supply is used. It has to use the supply at the beginning of the period.

2023-08-04 18:53 UTC, oscarsernarosero approved these changes
This looks great Shane. I just pointed at some documentation fixes that I consider necessary, but the code itself looks great except for one initialization but that's not a biggie at all. I'll approve this and leave it up to you if you want to implement the suggested changes.

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +            totalPurchasedWithinPeriod = amountToTransfer; /// resets value for purchases outside of purchase period
By default in Solidity, every uint variable is initialized in 0. I meant to say to change line 90 for:
```uint256 totalPurchasedWithinPeriod = amountToTransfer;```

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                if (_tokenTotalSupply == 0) _tokenTotalSupply = _supply;
lol ah yeah. I actually did this with Tayler. I had already forgotten.

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
>      function checkTotalSupplyVolatilityPasses(
the _supply parameter is missing here

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
>      function checkTotalSupplyVolatilityPasses(
I think _supply refers to the value gotten from calling the token's contract totalSupply() function.

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                if (_tokenTotalSupply == 0) _tokenTotalSupply = _supply;
ok I should remember pretty easy this logic cuz I basically made it with Tayler not that long ago, but I had a really hard time remembering, so I would suggest to do a favor for our future selves and write more documentation on this code. I can help you if you need me to.

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +        uint256 currentPeriodStart = block.timestamp - ((block.timestamp - _startTimestamp) % (_period * 1 hours));
beautiful

2023-08-04 18:53 UTC, oscarsernarosero commented on src/economic/ruleProcessor/RuleProcessorCommonLib.sol
> +        // current timestamp subtracted by the remainder of seconds since the rule was active divided by period in hours
this is perfect. I would just take off the last part (in hours) since we are actually converting those hours into seconds when we multiply by ```1 hours```

2023-08-21 19:48 UTC, ShaneDuncan602 commented
merged with external

2023-08-21 19:48 UTC, closed without merging