External 76
thrackle-io/forte-rules-engine-v1 pull request #99
Opened 2023-08-11 16:20 UTC by TJ-Everett

Audit - Application Rules can unintentionally prevent token burning(21)

2023-08-14 14:08 UTC, ShaneDuncan602 commented on src/application/ProtocolApplicationHandler.sol
> +            if (_to != address(0)){
Shouldn't this "if" statement only be on the to address portion of this rule check? If someone is burning, the "from address" risk score should still be checked to make sure this wouldn't violate their risk imposed transaction limit.

2023-08-14 14:10 UTC, ShaneDuncan602 commented on src/application/ProtocolApplicationHandler.sol
> +            } else if (_to == address(0)) {
Oh, I see. You put it in  this else. This seems a little redundant. Unless I'm missing something, you should be able to just wrap the "to account" check in the if and that's all you need.

2023-08-14 14:11 UTC, ShaneDuncan602 commented on src/application/ProtocolApplicationHandler.sol
> +        if (AccessLevel0RuleActive && !appManager.isRegisteredAMM(_from) && _to != address(0)) ruleProcessor.checkAccessLevel0Passes(fromScore);
It should still check the from address regardless of the the "to address"

2023-08-14 14:14 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ApplicationRiskProcessorFacet.sol
> +                    ++i;
perfect

2023-08-14 14:16 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                    if (_address != address(0)) {
Can you add a comment in here? Like, "If allow list oracle rule implemented, exempt address(0) to allow burning"

2023-08-14 14:17 UTC, ShaneDuncan602 commented on src/economic/ruleProcessor/ERC20RuleProcessorFacet.sol
> +                    /// Deny List type
Can you add a comment in here? Like, "If deny list oracle rule implemented, any registered address is denied, including address(0)"

2023-08-14 14:19 UTC, ShaneDuncan602 commented on src/token/ProtocolERC20Handler.sol
> +            }
Kind of the same thing as above. This same logic can be accomplished with a single if around the "to" portion of the check. It will save some lines of code.

2023-08-14 14:19 UTC, ShaneDuncan602 commented on src/token/ProtocolERC721Handler.sol
> +
same

2023-08-14 14:21 UTC, ShaneDuncan602 commented on src/token/ProtocolHandlerCommon.sol
> +        } else {
This is good thinking. This short circuit will save unnecessary gas, especially in an app with many tokens.

2023-08-14 14:26 UTC, ShaneDuncan602 commented on test/ApplicationERC20.t.sol
> +        vm.startPrank(rich_user);
This would be invalid. If the from account is 0, they should not be able to burn when the accessLevel0 rule is active. I think I may have confused you with my answer to a question about this last week. Sorry about that. I went and looked at my answer and it was pretty vague.

2023-08-14 14:27 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +        applicationNFT.burn(3);
Probably need additional tests here to ensure that burning an amount of tokens that would put the from account below their allowed minimum would be prohibited.

2023-08-14 14:29 UTC, ShaneDuncan602 commented on test/ApplicationERC721.t.sol
> +        applicationNFT.burn(5);
We need additional testing to make sure the burn won't all the from address to get over their max transaction limit.

2023-08-14 14:32 UTC, ShaneDuncan602 requested changes
Just some fine tuning. Also, I think we need some tests in here to make sure that the zero address checks are working for general tags, risk, and access level.

2023-08-14 15:12 UTC, TJ-Everett commented on src/application/ProtocolApplicationHandler.sol
> +            } else if (_to == address(0)) {
Great point. I'll condense these down.

2023-08-14 15:16 UTC, TJ-Everett commented on test/ApplicationERC20.t.sol
> +        vm.startPrank(rich_user);
This helps alot. Thank you for clarifying this. 

No burns for accessLevel0 but if they have accessLevelWithdrawalLimits active for example that may allow for an amount at access0 and those burns would be allowed but count towards their limit?

2023-08-14 15:24 UTC, ShaneDuncan602 commented on test/ApplicationERC20.t.sol
> +        vm.startPrank(rich_user);
Not sure that I understand that question. Essentially, if the rule currently checks for general tags, risk, or access levels on the "from address" we still want to perform those checks. We just want to skip the ones that can restrict based on address(0) not having that data associated to it. Lack of tags on address(0) should never restrict a burn.

2023-08-15 21:28 UTC, oscarsernarosero approved these changes
I think this is really good job Tayler.

2023-08-15 21:28 UTC, oscarsernarosero commented on src/token/ProtocolERC20Handler.sol
> +                ruleProcessor.checkTransactionLimitByRiskScore(transactionLimitByRiskRuleId, riskScoreFrom, _transferValuation);
incorrect indentation. No biggie tho.

2023-08-15 22:23 UTC, TJ-Everett commented on src/token/ProtocolERC20Handler.sol
> +                ruleProcessor.checkTransactionLimitByRiskScore(transactionLimitByRiskRuleId, riskScoreFrom, _transferValuation);
Fixed. Thank you!

2023-08-15 23:56 UTC, ShaneDuncan602 approved these changes
Looks great.

2023-08-21 19:51 UTC, ShaneDuncan602 commented
merged with external

2023-08-21 19:51 UTC, closed without merging